Repository home-assistant/supervisor, pull requests merged in 2018-11, with the labels that each got.

#767 fix: use a different convention to handle multiple devices on same card
  hassio/const.py
  hassio/host/alsa.py
  hassio/misc/hardware.py
Labels: cla-signed, in progress

#793 Allow discovery default config
  hassio/discovery.py
Labels: cla-signed, in progress

#795 Fix discovery update
  hassio/discovery.py
Labels: cla-signed, in progress

#796 Release 139
  API.md
  hassio/addons/addon.py
  hassio/api/auth.py
  hassio/api/proxy.py
  hassio/const.py
  hassio/discovery.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/host/alsa.py
  hassio/misc/hardware.py
  hassio/snapshots/__init__.py
  hassio/tasks.py
  requirements.txt
  tox.ini
Labels: cla-signed, in progress

#803 Bugfix Add-on validate on RO
  hassio/addons/validate.py
Labels: cla-signed, in progress

#817 Add tests for hass.io
  tests/__init__.py
  tests/addons/__init__.py
  tests/addons/test_config.py
  tests/common.py
  tests/fixtures/basic-addon-config.json
  tox.ini
Labels: cla-signed, in progress

#818 Update uvloop to version 0.11.3
  requirements.txt
Labels: cla-signed, in progress

#810 Bugfix Add-on validate correct image url
  hassio/addons/validate.py
  tests/addons/test_config.py
Labels: cla-error, cla-signed

#814 Provide options for legacy add-ons
  hassio/docker/addon.py
Labels: cla-signed, in progress

#819 Rating add-on better they implement hass auth
  hassio/addons/utils.py
Labels: cla-signed, in progress

#820 Master
  hassio/addons/utils.py
Labels: in progress

#821 Add tests for add-ons map
  tests/addons/test_config.py
Labels: cla-signed, in progress

#822 Small code cleanups
  hassio/homeassistant.py
Labels: cla-signed, in progress

#824 Downgrade discovery duplicate logging
  hassio/discovery.py
Labels: cla-signed, in progress

#829 Add support for the Orange Pi Prime
  hassio/addons/validate.py
Labels: cla-signed

#842 Bugfix stack trace on remove
  hassio/addons/utils.py
Labels: cla-signed, in progress
