Repository home-assistant/supervisor, pull requests merged in 2018-10, with the labels that each got.

#733 Don't allow add-on to update itself
  hassio/api/security.py
Labels: cla-signed, hacktoberfest, in progress

#734 Cleanup discovery data
  API.md
  hassio/api/discovery.py
  hassio/const.py
  hassio/discovery.py
  hassio/validate.py
Labels: cla-signed, in progress

#735 Bugfix message handling
  hassio/discovery.py
Labels: cla-signed, in progress

#736 Release 133
  API.md
  hassio/api/discovery.py
  hassio/api/security.py
  hassio/const.py
  hassio/discovery.py
  hassio/validate.py
Labels: cla-signed, in progress

#738 Fix manager access to `/addons`
  hassio/api/security.py
Labels: cla-signed, hacktoberfest, in progress

#744 Fix machine 'odroid-c2'
  hassio/addons/validate.py
Labels: cla-signed, hacktoberfest

#743 Adds support for privilege DAC_READ_SEARCH
  hassio/addons/utils.py
  hassio/addons/validate.py
  hassio/const.py
Labels: cla-signed, hacktoberfest, in progress

#740 small code cleanups
  hassio/addons/addon.py
  hassio/api/addons.py
  hassio/api/homeassistant.py
  hassio/docker/__init__.py
  hassio/homeassistant.py
Labels: cla-signed, in progress

#747 Add missing tinker board
  hassio/addons/validate.py
Labels: cla-signed, hacktoberfest

#748 Add hostname into version API call
  hassio/api/version.py
Labels: cla-signed, in progress

#749 Release 135
  hassio/addons/validate.py
  hassio/api/version.py
  hassio/const.py
Labels: cla-signed, in progress

#750 Rename info
  API.md
  hassio/api/__init__.py
  hassio/api/info.py
  hassio/api/security.py
Labels: cla-signed, in progress

#755 Create role for backup add-ons
  hassio/addons/validate.py
  hassio/api/security.py
  hassio/const.py
Labels: cla-signed, in progress

#760 Fix proxy handling with failing connection
  hassio/api/proxy.py
  requirements.txt
Labels: cla-signed, in progress

#765 Don't clean cache on fake auth
  hassio/auth.py
Labels: cla-signed, in progress

#764 Rename login_backend to auth_api
  API.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/api/auth.py
  hassio/const.py
Labels: cla-signed, in progress

#766 Release 138
  API.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/api/auth.py
  hassio/auth.py
  hassio/const.py
Labels: cla-signed, in progress

#772 Grammar and spelling fixes
  API.md
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/snapshots/__init__.py
Labels: cla-signed, hacktoberfest

#771 Support full basic auth flow
  hassio/api/auth.py
Labels: cla-signed, in progress

#778 Catch exception on watchdog for pretty log
  hassio/tasks.py
Labels: cla-signed, in progress
