Repository home-assistant/supervisor, pull requests merged in 2019-08, with the labels that each got.

#1187 Fix time adjustments on latest boot
  hassio/core.py
Labels: cla-signed

#1175 Don't relay on latest with HA/Addons
  .devcontainer/devcontainer.json
  azure-pipelines.yml
  hassio/__main__.py
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/bootstrap.py
  hassio/core.py
  hassio/docker/__init__.py
  hassio/docker/addon.py
  hassio/docker/hassos_cli.py
  hassio/docker/homeassistant.py
  hassio/docker/interface.py
  hassio/docker/supervisor.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/misc/dns.py
  hassio/supervisor.py
  hassio/validate.py
Labels: cla-signed

#1170 Repair / fixup docker overlayfs issues
  API.md
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/api/__init__.py
  hassio/api/supervisor.py
  hassio/core.py
  hassio/docker/__init__.py
  hassio/docker/addon.py
  hassio/docker/interface.py
  hassio/docker/supervisor.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/supervisor.py
Labels: cla-signed

#1189 Start API server before he beform a self update
  hassio/core.py
Labels: cla-signed

#1190 Release 171
  .devcontainer/devcontainer.json
  API.md
  azure-pipelines.yml
  hassio/__main__.py
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/api/__init__.py
  hassio/api/supervisor.py
  hassio/bootstrap.py
  hassio/const.py
  hassio/core.py
  hassio/docker/__init__.py
  hassio/docker/addon.py
  hassio/docker/hassos_cli.py
  hassio/docker/homeassistant.py
  hassio/docker/interface.py
  hassio/docker/supervisor.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/misc/dns.py
  hassio/supervisor.py
  hassio/validate.py
  requirements.txt
Labels: cla-needed

#1191 Add better log output for repair
  hassio/core.py
Labels: cla-signed

#1193 Fix Version detection with exists container
  hassio/homeassistant.py
Labels: cla-signed

#1194 Release 172
  .devcontainer/devcontainer.json
  hassio/const.py
  hassio/core.py
  hassio/homeassistant.py
Labels: cla-signed

#1196 Fix hanging landingpage
  hassio/homeassistant.py
Labels: cla-signed

#1197 Release 173
  hassio/const.py
  hassio/homeassistant.py
Labels: cla-signed

#1195 Add CoreDNS as DNS backend
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .dockerignore
  .gitignore
  .vscode/tasks.json
  API.md
  hassio/addons/model.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/dns.py
  hassio/arch.py
  hassio/bootstrap.py
  hassio/config.py
  hassio/const.py
  hassio/core.py
  hassio/coresys.py
  hassio/data/arch.json
  hassio/data/asound.tmpl
  hassio/data/audiodb.json
  hassio/data/coredns.tmpl
  hassio/data/hosts.tmpl
  hassio/dns.py
  hassio/docker/__init__.py
  hassio/docker/addon.py
  hassio/docker/dns.py
  hassio/docker/homeassistant.py
  hassio/docker/interface.py
  hassio/docker/network.py
  hassio/docker/supervisor.py
  hassio/exceptions.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/host/alsa.py
  hassio/misc/forwarder.py
  hassio/tasks.py
  hassio/updater.py
  hassio/validate.py
  script/test_env.sh
  script/update-frontend.sh
Labels: cla-signed

#1202 Rename scripts folder
  .vscode/tasks.json
  scripts/test_env.sh
  scripts/update-frontend.sh
Labels: cla-signed

#1203 Add debug output to gdbus
  hassio/utils/gdbus.py
Labels: cla-signed

#1204 Add DNS to add-on
  API.md
  hassio/addons/addon.py
  hassio/addons/model.py
  hassio/api/addons.py
Labels: cla-signed

#1205 Stats percent
  .vscode/tasks.json
  API.md
  hassio/api/addons.py
  hassio/api/dns.py
  hassio/api/homeassistant.py
  hassio/api/supervisor.py
  hassio/bootstrap.py
  hassio/config.py
  hassio/const.py
  hassio/docker/stats.py
Labels: cla-signed

#1206 Addon provide his own udev support
  API.md
  hassio/addons/model.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/api/hardware.py
  hassio/const.py
  hassio/docker/addon.py
  hassio/misc/hardware.py
Labels: cla-signed

#1209 Release 174
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .dockerignore
  .vscode/tasks.json
  API.md
  hassio/addons/addon.py
  hassio/addons/model.py
  hassio/addons/validate.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/dns.py
  hassio/api/hardware.py
  hassio/api/homeassistant.py
  hassio/api/supervisor.py
  hassio/arch.py
  hassio/bootstrap.py
  hassio/config.py
  hassio/const.py
  hassio/core.py
  hassio/coresys.py
  hassio/data/arch.json
  hassio/data/asound.tmpl
  hassio/data/audiodb.json
  hassio/data/coredns.tmpl
  hassio/data/hosts.tmpl
  hassio/dns.py
  hassio/docker/__init__.py
  hassio/docker/addon.py
  hassio/docker/dns.py
  hassio/docker/homeassistant.py
  hassio/docker/interface.py
  hassio/docker/network.py
  hassio/docker/stats.py
  hassio/docker/supervisor.py
  hassio/exceptions.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/host/alsa.py
  hassio/misc/forwarder.py
  hassio/misc/hardware.py
  hassio/tasks.py
  hassio/updater.py
  hassio/utils/gdbus.py
  hassio/validate.py
  requirements.txt
  scripts/test_env.sh
  scripts/update-frontend.sh
Labels: cla-signed

#1211 Fix socat command
  hassio/misc/forwarder.py
Labels: cla-signed

#1212 Add CoreDNS to update process
  hassio/dns.py
  hassio/tasks.py
Labels: cla-signed

#1213 Release 175
  hassio/const.py
  hassio/dns.py
  hassio/misc/forwarder.py
  hassio/tasks.py
Labels: cla-signed

#1214 Fix latest issue
  hassio/docker/interface.py
  hassio/supervisor.py
Labels: cla-signed

#1215 Call update of resolv later
  hassio/dns.py
Labels: cla-signed

#1217 Revert "Call update of resolv later"
  hassio/dns.py
Labels: cla-signed

#1218 Release 176
  hassio/const.py
  hassio/dns.py
  hassio/docker/interface.py
  hassio/supervisor.py
  requirements.txt
Labels: cla-needed, cla-signed

#1219 Allow manager role to access DNS API
  hassio/api/security.py
Labels: cla-signed

#1220 Cleanup ingress panel on add-on uninstall
  hassio/addons/__init__.py
Labels: cla-signed

#1221 Validate dns better
  hassio/validate.py
Labels: cla-signed

#1222 Release 177
  hassio/addons/__init__.py
  hassio/api/security.py
  hassio/const.py
  hassio/validate.py
Labels: cla-signed

#1223 Change handling with host files
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/dns.py
  hassio/tasks.py
Labels: cla-signed

#1225 Fix issue on isntalled add-ons
  hassio/addons/__init__.py
  hassio/addons/addon.py
Labels: cla-signed

#1226 Stripe resolv
  hassio/dns.py
Labels: cla-signed

#1224 Release 178
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/const.py
  hassio/dns.py
  hassio/tasks.py
Labels: cla-signed

#1228 Use hosts as list
  hassio/dns.py
  hassio/docker/addon.py
Labels: cla-signed

#1229 Release 179
  hassio/const.py
  hassio/dns.py
  hassio/docker/addon.py
  requirements_tests.txt
Labels: cla-needed

#1238 Adjust coredns to use upstream fowarding server in order
  hassio/data/coredns.tmpl
Labels: cla-signed

#1240 Add localhost to hosts file
  hassio/dns.py
Labels: cla-signed

#1237 Adjust coredns do not forward local.hass.io
  hassio/data/coredns.tmpl
Labels: cla-signed

#1242 Add restart function / options change
  API.md
  hassio/api/__init__.py
  hassio/api/dns.py
Labels: cla-signed

#1235 Replace Google DNS by Quad9, prefer CloudFlare
  hassio/const.py
Labels: cla-signed

#1243 Release 180
  API.md
  hassio/api/__init__.py
  hassio/api/dns.py
  hassio/const.py
  hassio/data/coredns.tmpl
  hassio/dns.py
Labels: cla-signed

#1244 Update setting on startup
  hassio/dns.py
Labels: cla-signed

#1245 Log coredns errors
  hassio/data/coredns.tmpl
Labels: cla-signed

#1246 Fix AAAA resolv for nginx
  hassio/data/coredns.tmpl
  hassio/dns.py
Labels: cla-signed

#1247 Release 181
  hassio/const.py
  hassio/data/coredns.tmpl
  hassio/dns.py
Labels: cla-signed

#1253 Improve handling with nested objects
  hassio/utils/gdbus.py
  tests/utils/test_gvariant_parser.py
Labels: cla-signed

#1255 Add support to read Host DNS
  API.md
  hassio/api/dns.py
  hassio/const.py
  hassio/core.py
  hassio/dbus/__init__.py
  hassio/dbus/hostname.py
  hassio/dbus/interface.py
  hassio/dbus/nmi_dns.py
  hassio/dns.py
  hassio/host/__init__.py
  hassio/host/info.py
  hassio/host/network.py
  hassio/utils/gdbus.py
Labels: cla-signed

#1258 Add support for gvariant annotations
  hassio/utils/gdbus.py
  tests/utils/test_gvariant_parser.py
Labels: cla-signed

#1259 Release 183
  hassio/const.py
  hassio/utils/gdbus.py
  tests/utils/test_gvariant_parser.py
Labels: cla-signed

#1263 Preserve ordering of locals
  hassio/host/network.py
Labels: cla-signed

#1264 Release 184
  hassio/const.py
  hassio/host/network.py
Labels: cla-signed
