Repository home-assistant/supervisor, pull requests merged in 2019-05, with the labels that each got.

#1070 Debugger
  API.md
  Dockerfile
  README.md
  hassio/__main__.py
  hassio/api/supervisor.py
  hassio/bootstrap.py
  hassio/config.py
  hassio/const.py
  hassio/coresys.py
  hassio/validate.py
  requirements.txt
Labels: cla-signed, in progress

#1073 Fix validation of image and last_version
  hassio/api/homeassistant.py
Labels: cla-signed

#1067 WIP: Split add-on store logic
  Dockerfile
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/addons/build.py
  hassio/addons/data.py
  hassio/addons/model.py
  hassio/addons/utils.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/api/supervisor.py
  hassio/bootstrap.py
  hassio/core.py
  hassio/coresys.py
  hassio/docker/addon.py
  hassio/ingress.py
  hassio/services/interface.py
  hassio/snapshots/__init__.py
  hassio/snapshots/snapshot.py
  hassio/store/__init__.py
  hassio/store/addon.py
  hassio/store/built-in.json
  hassio/store/data.py
  hassio/store/git.py
  hassio/store/repository.py
  hassio/store/utils.py
  hassio/store/validate.py
  hassio/tasks.py
Labels: cla-signed, in progress

#1077 Bugfixes / increase Home Assistant timeout
  hassio/docker/homeassistant.py
  hassio/snapshots/__init__.py
  hassio/tasks.py
Labels: cla-signed, in progress

#1078 Fix device bug
  hassio/addons/model.py
  hassio/docker/addon.py
Labels: cla-signed, in progress

#1079 Release 163
  API.md
  Dockerfile
  README.md
  azure-pipelines.yml
  hassio/__main__.py
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/addons/build.py
  hassio/addons/data.py
  hassio/addons/model.py
  hassio/addons/utils.py
  hassio/addons/validate.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/homeassistant.py
  hassio/api/panel/hassio-app.html
  hassio/api/panel/hassio-app.html.gz
  hassio/api/panel/hassio-main-es5.html
  hassio/api/panel/hassio-main-es5.html.gz
  hassio/api/panel/hassio-main-latest.html
  hassio/api/panel/hassio-main-latest.html.gz
  hassio/api/supervisor.py
  hassio/bootstrap.py
  hassio/config.py
  hassio/const.py
  hassio/core.py
  hassio/coresys.py
  hassio/docker/addon.py
  hassio/docker/homeassistant.py
  hassio/homeassistant.py
  hassio/ingress.py
  hassio/services/interface.py
  hassio/snapshots/__init__.py
  hassio/snapshots/snapshot.py
  hassio/store/__init__.py
  hassio/store/addon.py
  hassio/store/built-in.json
  hassio/store/data.py
  hassio/store/git.py
  hassio/store/repository.py
  hassio/store/utils.py
  hassio/store/validate.py
  hassio/tasks.py
  hassio/validate.py
  requirements.txt
  requirements_tests.txt
Labels: cla-needed, in progress

#1088 Fix error with repository without repository.json
  hassio/store/repository.py
Labels: cla-signed

#1101 Add black support
  azure-pipelines.yml
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/addons/build.py
  hassio/addons/data.py
  hassio/addons/model.py
  hassio/addons/validate.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/auth.py
  hassio/api/hardware.py
  hassio/api/host.py
  hassio/api/proxy.py
  hassio/api/services.py
  hassio/api/snapshots.py
  hassio/api/utils.py
  hassio/auth.py
  hassio/bootstrap.py
  hassio/coresys.py
  hassio/dbus/hostname.py
  hassio/dbus/rauc.py
  hassio/dbus/systemd.py
  hassio/dbus/utils.py
  hassio/docker/addon.py
  hassio/docker/interface.py
  hassio/docker/stats.py
  hassio/homeassistant.py
  hassio/host/__init__.py
  hassio/host/alsa.py
  hassio/host/apparmor.py
  hassio/host/control.py
  hassio/host/info.py
  hassio/host/services.py
  hassio/ingress.py
  hassio/misc/dns.py
  hassio/misc/hardware.py
  hassio/misc/scheduler.py
  hassio/snapshots/__init__.py
  hassio/snapshots/snapshot.py
  hassio/store/__init__.py
  hassio/store/git.py
  hassio/store/repository.py
  hassio/store/validate.py
  hassio/updater.py
  hassio/utils/apparmor.py
  hassio/utils/gdbus.py
Labels: cla-signed

#1104 Fix error on add-on comparing
  hassio/addons/model.py
Labels: cla-signed

#1105 Release 165
  azure-pipelines.yml
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/addons/build.py
  hassio/addons/data.py
  hassio/addons/model.py
  hassio/addons/validate.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/auth.py
  hassio/api/hardware.py
  hassio/api/host.py
  hassio/api/proxy.py
  hassio/api/services.py
  hassio/api/snapshots.py
  hassio/api/utils.py
  hassio/auth.py
  hassio/bootstrap.py
  hassio/const.py
  hassio/coresys.py
  hassio/dbus/hostname.py
  hassio/dbus/rauc.py
  hassio/dbus/systemd.py
  hassio/dbus/utils.py
  hassio/docker/addon.py
  hassio/docker/interface.py
  hassio/docker/stats.py
  hassio/homeassistant.py
  hassio/host/__init__.py
  hassio/host/alsa.py
  hassio/host/apparmor.py
  hassio/host/control.py
  hassio/host/info.py
  hassio/host/services.py
  hassio/ingress.py
  hassio/misc/dns.py
  hassio/misc/hardware.py
  hassio/misc/scheduler.py
  hassio/snapshots/__init__.py
  hassio/snapshots/snapshot.py
  hassio/store/__init__.py
  hassio/store/git.py
  hassio/store/repository.py
  hassio/store/validate.py
  hassio/updater.py
  hassio/utils/apparmor.py
  hassio/utils/gdbus.py
  requirements.txt
Labels: cla-needed

#1106 Don't follow requests itself
  azure-pipelines.yml
  hassio/api/ingress.py
  setup.py
  tests/__init__.py
  tests/addons/__init__.py
  tests/addons/test_config.py
Labels: cla-signed
