Repository home-assistant/supervisor, pull requests merged in 2019-10, with the labels that each got.

#1327 Add support for Home Panel Discovery
  hassio/discovery/services/home_panel.py
Labels: cla-signed

#1336 Check path on extractall
  hassio/addons/addon.py
  hassio/snapshots/snapshot.py
  hassio/utils/tar.py
  tests/utils/test_tarfile.py
Labels: cla-signed

#1337 Add snapshot_exclude option
  hassio/addons/addon.py
  hassio/addons/model.py
  hassio/addons/validate.py
  hassio/const.py
  hassio/snapshots/utils.py
  hassio/store/git.py
  hassio/utils/tar.py
  tests/utils/test_tarfile.py
Labels: cla-signed

#1339 Add discovery support for Almond
  hassio/discovery/services/almond.py
  tests/discovery/test_almond.py
  tests/discovery/test_home_panel.py
Labels: cla-signed

#1340 Prune network/interface on repair
  hassio/addons/__init__.py
  hassio/docker/__init__.py
  hassio/docker/network.py
  hassio/homeassistant.py
Labels: cla-signed

#1341 Release 190
  .devcontainer/devcontainer.json
  hassio/__main__.py
  hassio/addons/__init__.py
  hassio/addons/addon.py
  hassio/addons/model.py
  hassio/addons/validate.py
  hassio/bootstrap.py
  hassio/const.py
  hassio/discovery/__init__.py
  hassio/discovery/services/almond.py
  hassio/discovery/services/home_panel.py
  hassio/docker/__init__.py
  hassio/docker/network.py
  hassio/homeassistant.py
  hassio/host/alsa.py
  hassio/host/services.py
  hassio/snapshots/snapshot.py
  hassio/snapshots/utils.py
  hassio/store/git.py
  hassio/utils/tar.py
  requirements.txt
  requirements_tests.txt
  tests/discovery/test_almond.py
  tests/discovery/test_home_panel.py
  tests/utils/test_tarfile.py
Labels: cla-needed

#1342 Downgrade aiohttp to 3.6.1 to fix lost connections
  requirements.txt
Labels: cla-signed

#1343 Release 191
  hassio/const.py
  requirements.txt
Labels: cla-signed

#1345 Fix secrets containing unsupported types
  hassio/secrets.py
Labels: cla-signed

#1347 Gracefully allow loading duplicate keys in secrets
  hassio/secrets.py
Labels: Hacktoberfest, cla-signed

#1349 Release 192
  Dockerfile
  hassio/const.py
  hassio/secrets.py
  requirements_tests.txt
Labels: cla-needed

#1350 Better proxy handling
  hassio/api/ingress.py
Labels: cla-signed

#1355 Pin Black
  .devcontainer/Dockerfile
  azure-pipelines.yml
  hassio/utils/tar.py
  requirements_tests.txt
  tox.ini
Labels: cla-signed
