Repository home-assistant/supervisor, pull requests merged in 2019-04, with the labels that each got.

#988 Update uvloop 0.12.2
  hassio/__main__.py
  requirements.txt
Labels: cla-signed, in progress

#989 Update API data for deconz
  hassio/discovery/const.py
  hassio/discovery/services/deconz.py
  tests/discovery/test_deconz.py
Labels: cla-signed, in progress

#992 Downgrade add-on API access logging to debug
  hassio/api/proxy.py
Labels: cla-signed

#991 Add Ingress support
  API.md
  hassio/__main__.py
  hassio/addons/addon.py
  hassio/addons/utils.py
  hassio/addons/validate.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/hassos.py
  hassio/api/homeassistant.py
  hassio/api/ingress.py
  hassio/api/security.py
  hassio/api/supervisor.py
  hassio/const.py
  hassio/docker/__init__.py
  hassio/docker/addon.py
  hassio/docker/homeassistant.py
  hassio/docker/interface.py
  hassio/docker/network.py
  hassio/docker/supervisor.py
  hassio/exceptions.py
  hassio/hassos.py
  hassio/homeassistant.py
  hassio/snapshots/snapshot.py
  hassio/supervisor.py
  hassio/utils/__init__.py
  pylintrc
  requirements.txt
  setup.cfg
Labels: cla-signed, in progress

#995 Init ingress session boarder / lookup
  API.md
  hassio/addons/addon.py
  hassio/api/__init__.py
  hassio/api/ingress.py
  hassio/bootstrap.py
  hassio/const.py
  hassio/core.py
  hassio/coresys.py
  hassio/homeassistant.py
  hassio/ingress.py
  hassio/tasks.py
  hassio/utils/__init__.py
  hassio/utils/dt.py
  hassio/validate.py
  tests/conftest.py
  tests/test_ingress.py
Labels: cla-signed, in progress

#996 Fix token handling with new secrets
  hassio/addons/validate.py
  hassio/validate.py
Labels: cla-signed, in progress

#998 Fix ingress_url with not installed add-ons
  API.md
  hassio/addons/addon.py
Labels: cla-signed, in progress

#1004 Panel ingress fix
  hassio/api/panel/chunk.14e484610f8259469e31.js
  hassio/api/panel/chunk.14e484610f8259469e31.js.gz
  hassio/api/panel/chunk.a6e3bc73416702354e6d.js
  hassio/api/panel/chunk.a6e3bc73416702354e6d.js.gz
  hassio/api/panel/entrypoint.js
  hassio/api/panel/entrypoint.js.gz
Labels: cla-signed, in progress

#1006 Add add-ons reload for manager
  hassio/api/security.py
Labels: cla-signed, in progress

#1010 Fix add-on build / install
  hassio/docker/addon.py
Labels: cla-signed, in progress

#1011 Improve add-on rebuild
  hassio/addons/addon.py
Labels: cla-signed, in progress

#1012 Cleanup last_version with latest_version inside code
  hassio/addons/addon.py
  hassio/api/addons.py
  hassio/api/homeassistant.py
  hassio/api/supervisor.py
  hassio/homeassistant.py
  hassio/snapshots/snapshot.py
  hassio/supervisor.py
  hassio/tasks.py
Labels: cla-signed, in progress

#1014 Release 154
  hassio/addons/addon.py
  hassio/api/addons.py
  hassio/api/homeassistant.py
  hassio/api/supervisor.py
  hassio/const.py
  hassio/docker/addon.py
  hassio/homeassistant.py
  hassio/snapshots/snapshot.py
  hassio/supervisor.py
  hassio/tasks.py
Labels: cla-signed, in progress

#1015 Support dynamic ingress port
  API.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/api/ingress.py
  hassio/ingress.py
  hassio/validate.py
  tests/test_ingress.py
Labels: cla-signed, in progress

#1017 Fix content-type response
  hassio/api/ingress.py
Labels: cla-signed, in progress

#1020 Release 155
  API.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/api/ingress.py
  hassio/const.py
  hassio/ingress.py
  hassio/validate.py
  tests/test_ingress.py
Labels: cla-signed, in progress

#1023 Allow to add a description for a port
  API.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/addons.py
  hassio/const.py
  hassio/docker/addon.py
  hassio/validate.py
Labels: cla-signed, in progress

#1027 Fix protocol handling
  hassio/api/ingress.py
Labels: cla-signed, in progress

#1029 Panel Fixes
  hassio/api/panel/chunk.183d719f6ced86001f8e.js
  hassio/api/panel/chunk.183d719f6ced86001f8e.js.gz
  hassio/api/panel/chunk.352e12b12df29c09b455.js
  hassio/api/panel/chunk.352e12b12df29c09b455.js.gz
  hassio/api/panel/entrypoint.js
  hassio/api/panel/entrypoint.js.gz
Labels: cla-signed, in progress

#1030 Release 157
  hassio/api/panel/chunk.183d719f6ced86001f8e.js
  hassio/api/panel/chunk.183d719f6ced86001f8e.js.gz
  hassio/api/panel/chunk.352e12b12df29c09b455.js
  hassio/api/panel/chunk.352e12b12df29c09b455.js.gz
  hassio/api/panel/entrypoint.js
  hassio/api/panel/entrypoint.js.gz
  hassio/const.py
Labels: cla-signed, in progress

#1032 Support for central log level handling
  API.md
  hassio/api/info.py
  hassio/api/supervisor.py
  hassio/config.py
  hassio/const.py
  hassio/validate.py
Labels: cla-signed, in progress

#1035 Allow to update logger
  hassio/bootstrap.py
  hassio/config.py
Labels: cla-signed, in progress

#1037 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: cla-signed, in progress

#1040 Fix: Websocket detection case sensitive
  hassio/api/ingress.py
Labels: in progress

#1041 Fix handling with Firefox
  hassio/api/ingress.py
Labels: cla-signed, in progress

#1042 Release 160
  .hadolint.yaml
  README.md
  azure-pipelines.yml
  hassio/api/ingress.py
  hassio/const.py
Labels: cla-signed, in progress

#1047 Ingress panel support
  API.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/__init__.py
  hassio/api/addons.py
  hassio/api/ingress.py
  hassio/const.py
  hassio/ingress.py
Labels: cla-signed

#1049 Downgrade logger for audio to debug
  hassio/misc/hardware.py
Labels: cla-signed, in progress

#1053 Remove potential tag when pulling new image
  hassio/docker/interface.py
Labels: cla-signed

#1054 Rename panel config attributes
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/ingress.py
  hassio/const.py
Labels: cla-signed, in progress

#1056 Release 162
  README.md
  hassio/addons/addon.py
  hassio/addons/validate.py
  hassio/api/ingress.py
  hassio/api/panel/chunk.1b30ffdc501071af245c.js
  hassio/api/panel/chunk.1b30ffdc501071af245c.js.gz
  hassio/api/panel/chunk.61f4e5888ff9846fe4b8.js
  hassio/api/panel/chunk.61f4e5888ff9846fe4b8.js.gz
  hassio/api/panel/entrypoint.js
  hassio/api/panel/entrypoint.js.gz
  hassio/const.py
  hassio/docker/interface.py
Labels: cla-signed, in progress

#1065 Force auto API password
  hassio/api/homeassistant.py
  hassio/homeassistant.py
Labels: cla-signed, in progress

#1066 Remove old panels < 0.70
  hassio/api/__init__.py
  hassio/api/panel/hassio-app.html
  hassio/api/panel/hassio-app.html.gz
  hassio/api/panel/hassio-main-es5.html
  hassio/api/panel/hassio-main-es5.html.gz
  hassio/api/panel/hassio-main-latest.html
  hassio/api/panel/hassio-main-latest.html.gz
Labels: cla-signed, in progress
