Repository home-assistant/supervisor, pull requests merged in 2020-12, with the labels that each got.

#2317 Use persistent MAC address instead clone / don't touch default
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/setting.py
  supervisor/dbus/payloads/interface_update.tmpl
  supervisor/host/network.py
  tests/api/test_network.py
  tests/dbus/payloads/test_interface_update_payload.py
Labels: cla-signed

#2318 Fix NM naming schema
  supervisor/dbus/payloads/generate.py
  tests/dbus/payloads/test_interface_update_payload.py
Labels: cla-signed

#2319 Add network reload to api
  supervisor/api/__init__.py
  supervisor/api/network.py
  tests/api/test_network.py
Labels: cla-signed

#2321 Send list of images to sentry
  supervisor/misc/filter.py
  supervisor/resolution/evaluate.py
  supervisor/resolution/evaluations/container.py
  tests/misc/test_filter_data.py
  tests/resolution/evaluation/test_evaluate_container.py
Labels: cla-signed

#2323 Fix sentry with sets
  supervisor/misc/filter.py
  tests/misc/test_filter_data.py
Labels: cla-signed

#2324 Support OTA url over version files
  supervisor/const.py
  supervisor/hassos.py
  supervisor/updater.py
  supervisor/validate.py
Labels: cla-signed

#2325 Make dbus connection more robust
  supervisor/dbus/__init__.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/rauc.py
  supervisor/dbus/systemd.py
Labels: cla-signed

#2326 Fix sentry stdlib spam
  supervisor/bootstrap.py
Labels: cla-signed

#2322 Improve error handling with job condition
  supervisor/addons/__init__.py
  supervisor/exceptions.py
  supervisor/homeassistant/core.py
  supervisor/jobs/decorator.py
  supervisor/snapshots/__init__.py
  supervisor/supervisor.py
  supervisor/updater.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed

#2331 Fix issue on store git clone
  supervisor/bootstrap.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/exceptions.py
  supervisor/resolution/__init__.py
  supervisor/resolution/fixup.py
  supervisor/resolution/fixups/store_execute_reset.py
  supervisor/resolution/module.py
  supervisor/store/__init__.py
  supervisor/store/git.py
  supervisor/store/repository.py
Labels: cla-signed

#2336 Fix KeyError in connectivity_enabled
  supervisor/dbus/network/__init__.py
Labels: cla-signed

#2337 Adds vlan_struct
  supervisor/api/network.py
  supervisor/const.py
Labels: cla-signed

#2340 Check NetworkManager Version if it is supported
  supervisor/dbus/const.py
  supervisor/dbus/interface.py
  supervisor/dbus/network/__init__.py
  tests/dbus/network/test_network_manager.py
Labels: cla-signed

#2342 Fix NM byte switch for ipv6 nameserver
  supervisor/dbus/payloads/generate.py
  tests/dbus/payloads/test_interface_update_payload.py
Labels: cla-signed

#2344 Upgrade json config handler logging to critical
  supervisor/utils/json.py
Labels: cla-signed

#2345 Fix issue with mark system wrong as rollback
  supervisor/core.py
Labels: cla-signed

#2347 Actually use the vlan_struct
  supervisor/api/network.py
Labels: cla-signed

#2349 Add changes to release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ci, cla-signed

#2353 Add note for unsupported system
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: cla-signed

#2354 Show link for help user with unsupported systems
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#2367 Fix typo in log message when completing snapshot
  supervisor/snapshots/__init__.py
Labels: cla-signed

#2371 Fix filtering with docker 20.10.x
  requirements.txt
Labels: bugfix, cla-signed

#2372 Fix typo
  supervisor/snapshots/__init__.py
Labels: cla-signed

#2390 Bump docker to 4.4.1
  requirements.txt
Labels: cla-signed, dependencies

#2392 Refacture version handling with AwesomeVersion
  requirements.txt
  supervisor/addons/addon.py
  supervisor/addons/build.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/utils.py
  supervisor/config.py
  supervisor/core.py
  supervisor/docker/__init__.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/docker/supervisor.py
  supervisor/hassos.py
  supervisor/homeassistant/__init__.py
  supervisor/homeassistant/core.py
  supervisor/plugins/__init__.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/utils/json.py
  supervisor/validate.py
  tests/misc/test_filter_data.py
Labels: cla-signed
