Repository home-assistant/supervisor, pull requests merged in 2021-11, with the labels that each got.

#3287 Fix typo in HA startup message
  supervisor/homeassistant/core.py
Labels: cla-signed, refactor

#3286 Using rolling token on observer
  supervisor/plugins/observer.py
Labels: cla-signed, refactor

#3293 Handle whoami SSL error less strict
  supervisor/utils/whoami.py
Labels: cla-signed, bugfix

#3297 Fix: using deep merge for test update schema
  supervisor/addons/addon.py
Labels: cla-signed, bugfix

#3292 Reload secrets on options config
  supervisor/api/addons.py
Labels: cla-signed, refactor

#3300 Add /supervisor/available_updates endpoint
  supervisor/api/__init__.py
  supervisor/api/const.py
  supervisor/api/supervisor.py
  tests/api/test_supervisor.py
  tests/conftest.py
Labels: cla-signed, new-feature

#3317 WS connection fix
  supervisor/addons/addon.py
  supervisor/exceptions.py
  supervisor/homeassistant/module.py
  supervisor/homeassistant/websocket.py
Labels: cla-signed, bugfix

#3329 Bump aiohttp and friends
  requirements.txt
Labels: cla-signed, dependencies

#3330 Bump pylint from 2.11.1 to 2.12.1
  requirements_tests.txt
  tests/addons/test_options.py
Labels: cla-signed, dependencies

#3333 Allow to clear explicit image name
  supervisor/api/homeassistant.py
  supervisor/homeassistant/module.py
Labels: cla-signed, bugfix
