Repository home-assistant/supervisor, pull requests merged in 2021-12, with the labels that each got.

#3328 Fix path name for build file
  .github/workflows/builder.yml
Labels: cla-signed, bugfix

#3363 Update ruamel.yaml to 0.17.17
  requirements.txt
  supervisor/utils/yaml.py
Labels: cla-signed, dependencies

#3347 Address pytest warnings
  supervisor/hardware/data.py
  supervisor/store/__init__.py
Labels: cla-signed, chore

#3311 De-duplicate Backup/Restore logic
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/backups/__init__.py
  tests/backups/conftest.py
  tests/backups/test_manager.py
  tests/conftest.py
Labels: cla-signed, refactor

#3364 Don't remove add-on repos if add-on is installed
  supervisor/store/__init__.py
  tests/fixtures/add-on.json
  tests/store/test_custom_repository.py
Labels: cla-signed, bugfix

#3366 Log if board reported by HAOS isn't in version file
  supervisor/updater.py
Labels: cla-signed, chore

#3348 Enable asyncio debug in developer mode
  supervisor/__main__.py
  supervisor/store/__init__.py
  supervisor/store/data.py
Labels: cla-signed, python, chore

#3377 Change CI cache restore policy
  .github/workflows/ci.yaml
Labels: cla-signed, ci

#3369 Create backup of add-ons and core before update
  supervisor/addons/__init__.py
  supervisor/addons/model.py
  supervisor/api/homeassistant.py
  supervisor/api/store.py
  supervisor/const.py
  supervisor/homeassistant/core.py
Labels: cla-signed, new-feature

#3307 Exclude old log files from backup
  supervisor/backups/backup.py
Labels: cla-signed, bugfix
