Repository home-assistant/supervisor, pull requests merged in 2021-08, with the labels that each got.

#3049 Replace abstractproperty with abstractmethod
  supervisor/plugins/base.py
  supervisor/resolution/checks/base.py
  supervisor/resolution/evaluations/base.py
  supervisor/resolution/fixups/base.py
Labels: cla-signed, refactor

#3054 Fix flaky tests when CI did not have access to /run/supervisor
  tests/conftest.py
Labels: cla-signed, bugfix

#2999 Add bus system for handling events hw/pulse/docker
  supervisor/bootstrap.py
  supervisor/bus.py
  supervisor/const.py
  supervisor/coresys.py
  supervisor/hardware/monitor.py
  supervisor/host/__init__.py
  supervisor/host/manager.py
  tests/test_bus.py
Labels: cla-signed, new-feature

#3055 Fix vcn install on CI
  .github/workflows/ci.yaml
Labels: cla-signed, ci

#3056 Give audio plugin machine data for mixer evaluation
  supervisor/docker/audio.py
Labels: cla-signed, refactor

#3037 Relax check_system_runtime timeout to 10 seconds
  supervisor/plugins/observer.py
Labels: cla-signed, refactor

#3066 Add Debian 11: Bulleyes to support systems check
  supervisor/resolution/evaluations/operating_system.py
Labels: cla-signed, new-feature

#3070 Codenotary vcn 0.9.8 - System trust check
  .devcontainer/Dockerfile
  Dockerfile
  build.json
  supervisor/docker/interface.py
  supervisor/homeassistant/core.py
  supervisor/resolution/checks/core_security.py
  supervisor/resolution/checks/core_trust.py
  supervisor/resolution/checks/supervisor_trust.py
  supervisor/resolution/const.py
  supervisor/security.py
  supervisor/supervisor.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_core_trust.py
  tests/resolution/check/test_check_system_trust.py
Labels: cla-signed, dependencies, refactor

#3080 Add check for plugin trust
  supervisor/bootstrap.py
  supervisor/coresys.py
  supervisor/plugins/__init__.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/manager.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  supervisor/resolution/checks/plugin_trust.py
  tests/resolution/check/test_check_core_trust.py
  tests/resolution/check/test_check_plugin_trust.py
  tests/resolution/check/test_check_supervisor_trust.py
Labels: cla-signed, new-feature
