Repository home-assistant/supervisor, pull requests merged in 2021-05, with the labels that each got.

#2851 Check integritiy of core
  supervisor/bootstrap.py
  supervisor/coresys.py
  supervisor/docker/addon.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/homeassistant/__init__.py
  supervisor/homeassistant/module.py
Labels: cla-signed, new-feature

#2862 Bump awesomeversion to 21.5.0
  requirements.txt
Labels: cla-signed, dependencies

#2854 Validate secrets on options/validate UI check
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/addons/options.py
  supervisor/api/__init__.py
  supervisor/api/addons.py
  supervisor/api/middleware_security.py
  supervisor/api/security.py
  supervisor/api/supervisor.py
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/const.py
  supervisor/coresys.py
  supervisor/docker/interface.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/resolution/evaluations/content_trust.py
  supervisor/resolution/evaluations/source_mods.py
  supervisor/security.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/utils/pwned.py
  supervisor/validate.py
  tests/api/test_middleware_security.py
  tests/api/test_security.py
  tests/api/test_supervisor.py
  tests/resolution/check/test_check_addon_pwned.py
  tests/resolution/evaluation/test_evaluate_content_trust.py
  tests/resolution/evaluation/test_evaluate_source_mods.py
  tests/test_updater.py
Labels: cla-signed, new-feature

#2879 Enable connectivity on startup
  supervisor/core.py
  supervisor/jobs/decorator.py
  supervisor/plugins/dns.py
  supervisor/supervisor.py
Labels: cla-signed, refactor

#2883 Fix tests
  tests/jobs/test_job_decorator.py
Labels: chore, cla-signed

#2861 Cleanup websession with new aiohttp ssl
  supervisor/addons/addon.py
  supervisor/api/proxy.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/homeassistant/api.py
  supervisor/homeassistant/websocket.py
  tests/conftest.py
Labels: cla-signed, refactor

#2885 Fix wheels host
  .github/workflows/builder.yml
Labels: ci, cla-signed

#2886 Python 3.9
  .devcontainer/Dockerfile
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  build.json
  pylintrc
  requirements_tests.txt
  supervisor/bootstrap.py
Labels: cla-signed, refactor

#2888 Update builder builder-2021.05.0
  .github/workflows/builder.yml
Labels: cla-signed, dependencies

#2903 Fix Watchdog port being used as string
  supervisor/addons/addon.py
Labels: bugfix, cla-signed

#2909 Update OS on intel-nuc to generic-x86-64 image
  supervisor/addons/validate.py
  supervisor/data/arch.json
  supervisor/hassos.py
  tests/conftest.py
  tests/test_hassos.py
Labels: cla-signed, haos, new-feature

#2923 Adjust content-trust core version
  supervisor/docker/homeassistant.py
Labels: bugfix, cla-signed
