Repository home-assistant/supervisor, pull requests merged in 2021-03, with the labels that each got.

#2646 Fixed typos in resolution notify
  supervisor/resolution/notify.py
Labels: chore, cla-signed

#2644 Add support for loading add-on translation files
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/const.py
  supervisor/store/data.py
  tests/store/test_translation_load.py
Labels: cla-signed, missing-documentation, new-feature

#2651 Create FileConfiguration baseclass
  supervisor/addons/addon.py
  supervisor/addons/build.py
  supervisor/addons/data.py
  supervisor/arch.py
  supervisor/auth.py
  supervisor/config.py
  supervisor/discovery/__init__.py
  supervisor/docker/__init__.py
  supervisor/exceptions.py
  supervisor/homeassistant/__init__.py
  supervisor/ingress.py
  supervisor/jobs/__init__.py
  supervisor/plugins/base.py
  supervisor/plugins/dns.py
  supervisor/services/data.py
  supervisor/store/data.py
  supervisor/store/repository.py
  supervisor/updater.py
  supervisor/utils/__init__.py
  supervisor/utils/common.py
  supervisor/utils/json.py
  supervisor/utils/yaml.py
  tests/utils/test_yaml.py
Labels: cla-signed, new-feature

#2652 Allow dynamic lookup cgroup rules based on Host udev
  supervisor/hardware/const.py
  supervisor/hardware/policy.py
  tests/hardware/test_policy.py
Labels: bugfix, cla-signed

#2655 Adjust CPU runtime allocation to support multiple add-ons
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
Labels: bugfix, cla-signed

#2654 Fix translation schema
  supervisor/addons/data.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/const.py
  supervisor/store/data.py
  tests/store/test_translation_load.py
Labels: bugfix, cla-signed

#2656 Fix add-on is not installed anymore
  supervisor/resolution/checks/addon_pwned.py
  tests/resolution/check/test_check_addon_pwned.py
Labels: bugfix, cla-signed

#2660 Add network description to translation files
  supervisor/addons/validate.py
  tests/store/test_translation_load.py
Labels: cla-signed, new-feature

#2664 Guard for missing repository file
  supervisor/store/data.py
Labels: bugfix, cla-signed

#2666 Fix error handling with new config handling
  supervisor/exceptions.py
  supervisor/utils/common.py
Labels: bugfix, cla-signed

#2675 Fix defaults for builds
  supervisor/addons/build.py
  supervisor/store/data.py
  supervisor/utils/common.py
  tests/utils/test_common.py
  tests/utils/test_yaml.py
Labels: bugfix, cla-signed

#2686 Set connectivity state on network tasks
  supervisor/exceptions.py
  supervisor/hassos.py
  supervisor/host/network.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/utils/pwned.py
Labels: cla-signed, refactor

#2697 Abort on Connection Error
  supervisor/resolution/checks/addon_pwned.py
Labels: cla-signed, refactor

#2704 Fix typos
  supervisor/homeassistant/websocket.py
  tests/homeassistant/test_websocket.py
Labels: chore

#2711 Disable secomp global
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
Labels: bugfix, cla-signed

#2712 Cache hits on pwned
  supervisor/utils/pwned.py
Labels: cla-signed, refactor

#2713 Fix landingpage on first boot
  supervisor/homeassistant/__init__.py
  supervisor/homeassistant/api.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/core.py
  supervisor/homeassistant/validate.py
  supervisor/validate.py
Labels: bugfix, cla-signed

#2703 Check management
  supervisor/api/__init__.py
  supervisor/api/discovery.py
  supervisor/api/ingress.py
  supervisor/api/resolution.py
  supervisor/api/utils.py
  supervisor/const.py
  supervisor/exceptions.py
  supervisor/resolution/check.py
  supervisor/resolution/checks/base.py
  supervisor/resolution/checks/free_space.py
  supervisor/resolution/const.py
  supervisor/resolution/module.py
  supervisor/resolution/validate.py
  tests/api/test_ingress.py
  tests/api/test_resolution.py
  tests/conftest.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_addon_pwned.py
  tests/resolution/check/test_check_core_security.py
  tests/resolution/check/test_check_free_space.py
Labels: cla-signed, new-feature

#2714 Tweak check API path
  supervisor/api/__init__.py
  tests/api/test_resolution.py
Labels: cla-signed, refactor

#2718 Revert "Tweak check API path"
  supervisor/api/__init__.py
  tests/api/test_resolution.py
Labels: cla-signed, refactor

#2716 Dynamically load resolution checks
  supervisor/resolution/check.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/resolution/checks/core_security.py
  supervisor/resolution/checks/free_space.py
  supervisor/resolution/validate.py
  tests/resolution/check/test_check.py
Labels: cla-signed, refactor

#2719 Resolution: API call for run check manual
  supervisor/api/__init__.py
  supervisor/api/resolution.py
  tests/api/test_resolution.py
Labels: cla-signed, new-feature

#2721 CoreNotary Image singing
  .github/workflows/builder.yml
Labels: chore, cla-signed

#2680 New error handling
  supervisor/addons/__init__.py
  supervisor/exceptions.py
  supervisor/hassos.py
  supervisor/homeassistant/core.py
  supervisor/snapshots/__init__.py
Labels: cla-signed, new-feature

#2726 Use github context object for workspace
  .github/workflows/builder.yml
Labels: ci, cla-signed

#2727 Install vcn inside docker container
  .hadolint.yaml
  Dockerfile
  build.json
Labels: cla-signed, new-feature

#2728 Fix access to needs.init.outputs.publish
  .github/workflows/builder.yml
  Dockerfile
Labels: ci, cla-signed

#2724 Detect haos as well
  supervisor/hassos.py
Labels: cla-signed, haos

#2722 Addons can access systemd journal logs
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/const.py
  supervisor/docker/addon.py
  tests/docker/__init__.py
  tests/docker/test_addon.py
  tests/fixtures/journald-addon-config.json
Labels: cla-signed, new-feature

#2731 Add CodeNotary / for version file
  supervisor/coresys.py
  supervisor/exceptions.py
  supervisor/updater.py
  supervisor/utils/codenotary.py
  supervisor/utils/pwned.py
  tests/utils/test_codenotary.py
Labels: cla-signed, new-feature

#2738 Fix sentry logs with None
  supervisor/exceptions.py
Labels: bugfix, cla-signed

#2741 remove git from build-dependencies
  Dockerfile
Labels: chore, cla-signed

#2740 fix signerID command
  supervisor/utils/codenotary.py
Labels: bugfix, cla-signed

#2742 Fix journald add-on option to work with default Debian
  supervisor/const.py
  supervisor/docker/addon.py
  tests/docker/test_addon.py
Labels: bugfix, cla-signed

#2745 Add link to cli on pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, cla-signed

#2744 Force / Enforce security if service is not available
  .github/workflows/builder.yml
  build.json
  supervisor/api/addons.py
  supervisor/api/supervisor.py
  supervisor/config.py
  supervisor/const.py
  supervisor/coresys.py
  supervisor/exceptions.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/utils/codenotary.py
  supervisor/utils/pwned.py
  supervisor/validate.py
  tests/api/test_supervisor.py
  tests/resolution/check/test_check_addon_pwned.py
  tests/test_updater.py
Labels: cla-signed, new-feature

#2751 Fix typo in journald location
  supervisor/const.py
  tests/docker/test_addon.py
Labels: bugfix, cla-signed

#2752 Allow optional array configs
  supervisor/addons/options.py
  tests/addons/test_options.py
Labels: bugfix, cla-signed

#2755 Fix HAOS sync output
  supervisor/core.py
  supervisor/exceptions.py
  supervisor/hassos.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, refactor

#2757 Supervisor image handler
  supervisor/config.py
  supervisor/docker/interface.py
  supervisor/docker/supervisor.py
  supervisor/supervisor.py
  supervisor/validate.py
Labels: cla-signed, refactor

#2758 Make secrets more robust again
  supervisor/homeassistant/secrets.py
  supervisor/utils/json.py
  supervisor/utils/yaml.py
Labels: cla-signed, refactor

#2764 Fix swapped volume/bind variables in Journald volume support
  supervisor/docker/addon.py
  tests/docker/test_addon.py
Labels: bugfix, cla-signed

#2767 Fix devcontainer
  .devcontainer/Dockerfile
Labels: bugfix, cla-signed

#2766 Updater check response code
  supervisor/updater.py
Labels: bugfix, cla-signed

#2765 Map both persistent and volatile journald logs
  supervisor/docker/addon.py
  tests/docker/test_addon.py
Labels: bugfix, cla-signed

#2772 Fix request status check on AppArmor profile fetch
  supervisor/exceptions.py
  supervisor/supervisor.py
  supervisor/updater.py
Labels: cla-signed, refactor

#2773 Enable content-trust on CLI docker
  supervisor/docker/cli.py
Labels: cla-signed, new-feature
