Repository home-assistant/supervisor, pull requests merged in 2021-01, with the labels that each got.

#2394 Bump awesomeversion from 20.12.4 to 20.12.5
  requirements.txt
  supervisor/utils/json.py
Labels: cla-signed, dependencies

#2409 Fix typo in reference
  supervisor/store/__init__.py
Labels: bugfix, cla-signed

#2407 Allow GET method on /auth with BasicAuth
  supervisor/api/__init__.py
Labels: cla-signed

#2186 Add GitHub Action to build wheels
  .github/workflows/builder.yml
  azure-pipelines-wheels.yml
  requirements.txt
Labels: cla-signed

#2418 Set a default for add-on boot config
  supervisor/addons/validate.py
Labels: cla-signed

#2416 Shutdown using systemd-logind if available
  supervisor/dbus/__init__.py
  supervisor/dbus/const.py
  supervisor/dbus/logind.py
  supervisor/host/control.py
Labels: cla-signed

#2417 Increases core container timeout to match core shutdown time
  supervisor/docker/homeassistant.py
Labels: cla-signed

#2419 Set a default for add-on startup config
  supervisor/addons/validate.py
Labels: cla-signed

#2420 Fix missing repository
  supervisor/store/git.py
Labels: bugfix, cla-signed

#2421 Set a default for add-on options and schema config
  supervisor/addons/validate.py
Labels: cla-signed, refactor

#2378 Update git to support updates of submodules
  supervisor/store/git.py
Labels: cla-signed, new-feature

#2425 Adjust development tasks
  .devcontainer/Dockerfile
  .vscode/tasks.json
  README.md
  scripts/build-supervisor.sh
  scripts/common.sh
  scripts/run-supervisor.sh
  scripts/test_env.sh
Labels: cla-signed

#2426 Fix submodules - check if it is needed or not
  supervisor/store/git.py
Labels: cla-signed

#2427 Auth: Improve authorisation
  supervisor/api/auth.py
Labels: cla-signed, refactor

#2428 Ignore wheels on release
  .github/workflows/builder.yml
Labels: bugfix, cla-signed

#2434 Fix submodule update
  supervisor/store/git.py
Labels: cla-signed

#2436 Add core version check
  supervisor/resolution/check.py
  supervisor/resolution/checks/core_security.py
  supervisor/resolution/const.py
  supervisor/resolution/notify.py
  tests/resolution/check/test_check_core_security.py
Labels: cla-signed, new-feature

#2438 Update wording in notification
  supervisor/resolution/notify.py
Labels: cla-signed, refactor

#2443 Fix issues with awesomeversion and representation
  requirements.txt
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/docker/supervisor.py
  supervisor/hassos.py
Labels: cla-signed

#2452 Fix: stable issue with corrupt git repository / submodule
  supervisor/store/git.py
Labels: bugfix, cla-signed

#2451 Improve fixups with Job condition checks
  supervisor/resolution/fixup.py
  supervisor/resolution/fixups/store_execute_reload.py
  supervisor/resolution/fixups/store_execute_reset.py
Labels: cla-signed, refactor

#2457 Update alert notification
  supervisor/resolution/checks/core_security.py
  supervisor/resolution/notify.py
  tests/resolution/check/test_check_core_security.py
Labels: cla-signed, refactor

#2458 Fix OSError with custom component check
  supervisor/resolution/checks/core_security.py
Labels: cla-signed

#2460 Small README tweaks
  README.md
Labels: cla-signed

#2464 Fix API info calls access
  supervisor/api/security.py
Labels: cla-signed

#2466 New version logic NM
  requirements.txt
  supervisor/dbus/network/__init__.py
Labels: cla-signed

#2469 Add action to check PR labels
  .github/workflows/check_pr_labels.yml
Labels: ci, cla-signed

#2473 Bump awesomeversion from 21.1.3 to 21.1.4
  requirements.txt
Labels: cla-signed, dependencies

#2474 Add TypeError guard for docker stats
  supervisor/docker/stats.py
Labels: bugfix, cla-signed

#2475 Limit label check
  .github/workflows/check_pr_labels.yml
Labels: ci, cla-signed

#2429 Next generation hardware handling
  rootfs/etc/cont-init.d/udev.sh
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/addons/options.py
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/api/hardware.py
  supervisor/bootstrap.py
  supervisor/const.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/homeassistant.py
  supervisor/exceptions.py
  supervisor/hardware/__init__.py
  supervisor/hardware/const.py
  supervisor/hardware/data.py
  supervisor/hardware/helper.py
  supervisor/hardware/module.py
  supervisor/hardware/monitor.py
  supervisor/hardware/policy.py
  supervisor/host/info.py
  supervisor/misc/hardware.py
  supervisor/utils/json.py
  tests/addons/test_config.py
  tests/addons/test_options.py
  tests/addons/test_options_schema.py
  tests/addons/test_ui_schema.py
  tests/api/__init__.py
  tests/api/test_hardware.py
  tests/api/test_ingress.py
  tests/hardware/__init__.py
  tests/hardware/test_data.py
  tests/hardware/test_helper.py
  tests/hardware/test_module.py
  tests/hardware/test_policy.py
  tests/misc/test_hardware.py
  tests/resolution/__init__.py
  tests/resolution/fixup/test_store_execute_reload.py
  tests/resolution/fixup/test_store_execute_reset.py
Labels: breaking-change, cla-signed, new-feature

#2476 Improve device selection and show device by id if available
  supervisor/addons/options.py
  tests/addons/test_options.py
Labels: cla-signed, refactor

#2477 Fix mknod creating of the device on runtime time
  supervisor/docker/addon.py
Labels: bugfix, cla-signed

#2478 Handle GPIO / VIDEO map with subystem
  scripts/run-supervisor.sh
  supervisor/docker/addon.py
  supervisor/hardware/const.py
  supervisor/hardware/policy.py
  tests/hardware/test_policy.py
Labels: cla-signed, refactor

#2481 Bump awesomeversion from 21.1.4 to 21.1.5
  requirements.txt
Labels: cla-signed, dependencies

#2482 plug & play devices
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/hardware/const.py
  supervisor/hardware/container.py
  supervisor/hardware/helper.py
  supervisor/hardware/module.py
  supervisor/hardware/monitor.py
  supervisor/hardware/policy.py
  tests/hardware/test_helper.py
Labels: cla-signed, new-feature

#2484 Change handling kernel udev events
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/homeassistant.py
  supervisor/hardware/const.py
  supervisor/hardware/container.py
  supervisor/hardware/module.py
  supervisor/hardware/monitor.py
  supervisor/hardware/policy.py
  tests/hardware/test_policy.py
Labels: cla-signed, refactor

#2485 Add initial GitHub Issue Form
  .github/ISSUE_TEMPLATE/BUG_REPORT.md_disabled
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, cla-signed

#2486 Re-enable old template until form is resolved
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/z_bug_report_form.yml
Labels: chore, cla-signed

#2488 Cleanup supervisor/udev device action / add GPIO
  supervisor/hardware/const.py
  supervisor/hardware/monitor.py
Labels: cla-signed, refactor

#2489 Filter out virtual vcs devices
  supervisor/hardware/helper.py
  tests/hardware/test_helper.py
Labels: cla-signed, refactor

#2490 Handle corrupt store branch / ignore local reset on corruption
  supervisor/store/data.py
  supervisor/store/git.py
Labels: bugfix, cla-signed
