Repository home-assistant/supervisor, pull requests merged in 2021-04, with the labels that each got.

#2776 Add NET_ADMIN to multicast for pimd
  supervisor/docker/audio.py
  supervisor/docker/multicast.py
Labels: new-feature

#2777 Enable content-trust for all plugins
  supervisor/docker/audio.py
  supervisor/docker/dns.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
Labels: cla-signed, new-feature

#2783 Fix issues with special compiled binary with own version schema
  supervisor/docker/__init__.py
Labels: bugfix, cla-signed

#2784 Evaluate AppArmor support
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/apparmor.py
  tests/resolution/evaluation/test_evaluate_apparmor.py
Labels: cla-signed, new-feature

#2791 Improve message handling of job condition
  supervisor/exceptions.py
  supervisor/jobs/decorator.py
Labels: cla-signed, refactor

#2796 Break loop when we have the correct file
  supervisor/store/repository.py
  tests/store/test_custom_repository.py
Labels: bugfix, cla-signed

#2795 Signal frontend when updater runs
  supervisor/homeassistant/__init__.py
  supervisor/updater.py
Labels: cla-signed, refactor

#2797 Remove not needed warning before raise on JobDecorator
  supervisor/jobs/decorator.py
Labels: chore, cla-signed

#2798 Add image source to build.json
  build.json
Labels: chore, cla-signed

#2789 System unsupported source modification
  supervisor/bootstrap.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/source_mods.py
  supervisor/resolution/fixup.py
  supervisor/resolution/module.py
  supervisor/utils/codenotary.py
  tests/resolution/evaluation/test_evaluate_source_mods.py
Labels: cla-signed, new-feature

#2804 Remove double sentry event for untrusted
  supervisor/coresys.py
Labels: chore, cla-signed

#2809 Guard against multiple client creations
  supervisor/homeassistant/websocket.py
Labels: bugfix, cla-signed

#2810 Improve local build / allow cache on dev
  supervisor/addons/build.py
  supervisor/addons/validate.py
  supervisor/const.py
Labels: cla-signed, refactor

#2813 Extend supervisor CI checks
  .github/workflows/builder.yml
Labels: ci, cla-signed

#2815 Using mimalloc
  rootfs/etc/services.d/supervisor/run
Labels: cla-signed, new-feature

#2816 Using exists container on publish
  .github/workflows/builder.yml
Labels: ci, cla-signed

#2818 Add more image-spec annotations
  build.json
Labels: chore, cla-signed

#2819 Clean env on subprocess
  supervisor/utils/__init__.py
  supervisor/utils/codenotary.py
  supervisor/utils/gdbus.py
Labels: cla-signed, refactor

#2827 Update GitHub issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, cla-signed

#2821 Fix for bug in host network info collector
  supervisor/host/network.py
Labels: bugfix, cla-signed

#2839 Clean env on remove-folder
  supervisor/utils/__init__.py
Labels: cla-signed, refactor

#2840 Ignore version on supervisor update
  supervisor/api/supervisor.py
Labels: breaking-change, cla-signed, missing-documentation

#2841 Update GitHub issue form with render field
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, cla-signed

#2845 Update black 21.4b1 on pre-commit
  .pre-commit-config.yaml
Labels: chore, cla-signed

#2846 Fix WSL2 issues + cleanup scripts
  .devcontainer/Dockerfile
  .vscode/tasks.json
  scripts/build-supervisor.sh
  scripts/supervisor.sh
Labels: chore, cla-signed

#2847 Switch back to jemalloc
  rootfs/etc/services.d/supervisor/run
Labels: cla-signed, refactor

#2849 Handle iptables better WSL2
  .devcontainer/Dockerfile
  scripts/common.sh
Labels: chore, cla-signed

#2850 Add discovery support for motionEye
  supervisor/discovery/const.py
  supervisor/discovery/services/motioneye.py
  tests/discovery/test_motioneye.py
Labels: cla-signed, new-feature
