Repository home-assistant/supervisor, pull requests merged in 2021-06, with the labels that each got.

#2929 Minor spelling fixes
  supervisor/hassos.py
Labels: cla-signed, refactor

#2931 Lmit ensure_access_token
  supervisor/homeassistant/api.py
Labels: cla-signed, enhancement

#2934 Fix setting audio profile
  supervisor/host/sound.py
Labels: bugfix, cla-signed

#2941 Introduce pre-/post-snapshot commands
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/const.py
Labels: cla-signed, enhancement

#2901 Time handling
  requirements.txt
  supervisor/api/const.py
  supervisor/api/host.py
  supervisor/api/info.py
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/const.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/dbus/__init__.py
  supervisor/dbus/const.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/timedate.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/exceptions.py
  supervisor/host/__init__.py
  supervisor/host/control.py
  supervisor/host/info.py
  supervisor/supervisor.py
  supervisor/utils/dt.py
  supervisor/utils/pwned.py
  supervisor/utils/validate.py
  supervisor/utils/whoami.py
  supervisor/validate.py
  tests/conftest.py
  tests/dbus/test_hostname.py
  tests/dbus/test_timedate.py
  tests/fixtures/org_freedesktop_hostname1-SetStaticHostname.fixture
  tests/fixtures/org_freedesktop_hostname1.json
  tests/fixtures/org_freedesktop_hostname1.xml
  tests/fixtures/org_freedesktop_login1.xml
  tests/fixtures/org_freedesktop_systemd1.xml
  tests/fixtures/org_freedesktop_timedate1-SetNTP.fixture
  tests/fixtures/org_freedesktop_timedate1-SetTime.fixture
  tests/fixtures/org_freedesktop_timedate1.json
  tests/fixtures/org_freedesktop_timedate1.xml
  tests/test_core.py
  tests/test_coresys.py
Labels: cla-signed, missing-documentation, new-feature

#2949 Bump awesomeversion to 21.6.0
  requirements.txt
Labels: cla-signed, dependencies

#2946 Rename fixtures
  tests/conftest.py
  tests/fixtures/org_freedesktop_NetworkManager_AccessPoint_~.xml
  tests/fixtures/org_freedesktop_NetworkManager_ActiveConnection_~.xml
  tests/fixtures/org_freedesktop_NetworkManager_Devices_~.xml
  tests/fixtures/org_freedesktop_NetworkManager_IP4Config_~.xml
  tests/fixtures/org_freedesktop_NetworkManager_IP6Config_~.xml
  tests/fixtures/org_freedesktop_NetworkManager_Settings_~.xml
Labels: cla-signed, refactor

#2954 Cleanup security layer - Add-on default access role
  supervisor/api/__init__.py
  supervisor/api/hardware.py
  supervisor/api/middleware/__init__.py
  supervisor/api/middleware/security.py
  tests/api/middleware/__init__.py
  tests/api/middleware/test_security.py
Labels: cla-signed, refactor

#2956 Add-on: Block update itself
  supervisor/api/store.py
Labels: breaking-change, cla-signed

#2952 Fix addon_pwned enabled setter
  supervisor/resolution/checks/addon_pwned.py
  tests/resolution/check/test_check_addon_pwned.py
Labels: bugfix, cla-signed

#2958 Fix API watchdog never trigger
  supervisor/misc/tasks.py
Labels: bugfix, cla-signed

#2959 Using ghcr.io/home-assistant + fallback
  supervisor/addons/build.py
  supervisor/homeassistant/module.py
  supervisor/plugins/base.py
  tests/addons/test_config.py
  tests/conftest.py
  tests/fixtures/basic-build-config.json
Labels: cla-signed, refactor

#2960 When validating add-ons transform core-addons url
  supervisor/store/__init__.py
Labels: bugfix, cla-signed

#2961 Run API watchdog only if core is running
  supervisor/misc/tasks.py
Labels: bugfix, cla-signed

#2969 Using images data from version file
  supervisor/updater.py
  tests/test_updater.py
Labels: cla-signed, refactor

#2970 Allow downgrade to "hassos" from "haos"
  supervisor/hassos.py
  tests/test_hassos.py
Labels: cla-signed, haos, new-feature

#2943 Support HOT/COLD snapshots for Add-ons
  supervisor/addons/addon.py
  supervisor/addons/const.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
Labels: cla-signed, missing-documentation, new-feature

#2971 Logging in local timezone
  supervisor/bootstrap.py
  supervisor/coresys.py
  tests/conftest.py
  tests/test_coresys.py
Labels: cla-signed, new-feature

#2974 Allow upgrade when using {os_name} in URL
  supervisor/hassos.py
Labels: bugfix, cla-signed, haos

#2976 Add running job condition to OS update
  supervisor/hassos.py
Labels: cla-signed, refactor

#2977 Use brotlipy instead of Brotli
  requirements.txt
Labels: bugfix, cla-signed

#2979 Stream requests to ingress
  supervisor/api/ingress.py
Labels: cla-signed, new-feature

#2980 Fix failing test
  tests/test_hassos.py
Labels: chore, cla-signed

#2981 Only use .content for POST
  supervisor/api/ingress.py
Labels: bugfix, cla-signed

#2982 Add ingress_stream add-on option
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/ingress.py
  supervisor/const.py
Labels: bugfix, cla-signed

#2811 OS-Agent support
  .devcontainer/Dockerfile
  scripts/supervisor.sh
  supervisor/bootstrap.py
  supervisor/coresys.py
  supervisor/dbus/__init__.py
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/agent/apparmor.py
  supervisor/dbus/agent/cgroup.py
  supervisor/dbus/agent/datadisk.py
  supervisor/dbus/agent/system.py
  supervisor/dbus/const.py
  supervisor/dbus/manager.py
  supervisor/host/__init__.py
  supervisor/host/const.py
  supervisor/misc/tasks.py
  supervisor/resolution/evaluations/network_manager.py
  supervisor/resolution/evaluations/systemd.py
  supervisor/utils/gdbus.py
  tests/dbus/agent/__init__.py
  tests/dbus/agent/test_agent.py
  tests/dbus/agent/test_apparmor.py
  tests/dbus/agent/test_cgroup.py
  tests/dbus/agent/test_datadisk.py
  tests/dbus/agent/test_system.py
  tests/dbus/network/__init__.py
  tests/fixtures/io_hass_os.json
  tests/fixtures/io_hass_os.xml
  tests/fixtures/io_hass_os_AppArmor-LoadProfile.fixture
  tests/fixtures/io_hass_os_AppArmor-UnloadProfile.fixture
  tests/fixtures/io_hass_os_AppArmor.json
  tests/fixtures/io_hass_os_AppArmor.xml
  tests/fixtures/io_hass_os_CGroup-AddDevicesAllowed.fixture
  tests/fixtures/io_hass_os_CGroup.xml
  tests/fixtures/io_hass_os_DataDisk-ChangeDevice.fixture
  tests/fixtures/io_hass_os_DataDisk.json
  tests/fixtures/io_hass_os_DataDisk.xml
  tests/fixtures/io_hass_os_System-ScheduleWipeDevice.fixture
  tests/fixtures/io_hass_os_System.xml
  tests/resolution/evaluation/test_evaluate_systemd.py
Labels: cla-signed, new-feature

#2984 Format log as string
  supervisor/ingress.py
Labels: bugfix, cla-signed
