Repository home-assistant/supervisor, pull requests merged in 2021-02, with the labels that each got.

#2491 Typofix exsist -> exist
  supervisor/api/network.py
  supervisor/homeassistant/core.py
  supervisor/jobs/__init__.py
  tests/api/test_network.py
Labels: chore, cla-signed

#2492 Validate build env before using it
  supervisor/addons/build.py
  supervisor/docker/addon.py
Labels: cla-signed, refactor

#2497 Fix add-on is_valid check
  supervisor/addons/build.py
Labels: bugfix, cla-signed

#2500 Rerun label check on synchronize
  .github/workflows/check_pr_labels.yml
Labels: ci, cla-signed

#2499 Fix handling with shm and shared /dev
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/docker/addon.py
  supervisor/docker/homeassistant.py
  tests/addons/test_config.py
Labels: breaking-change, bugfix, cla-signed, missing-documentation

#2501 Bump awesomeversion from 21.1.8 to 21.2.0
  requirements.txt
Labels: cla-signed, dependencies

#2502 Udev - move away form depricated callback / increase buffer
  supervisor/hardware/monitor.py
Labels: cla-signed, refactor

#2503 Lookup udev device in monitor thread
  supervisor/hardware/monitor.py
Labels: cla-signed, refactor

#2504 Make sure device is ready initialize on udev
  supervisor/hardware/monitor.py
Labels: cla-signed, refactor

#2413 Add eMMC life-time estimate support
  supervisor/api/host.py
  supervisor/const.py
  supervisor/hardware/helper.py
  supervisor/host/info.py
  tests/hardware/test_helper.py
Labels: cla-signed, new-feature

#2507 Typo: depircated -> deprecated
  supervisor/addons/validate.py
Labels: chore, cla-signed

#2508 Change verbosity for hardware.trigger API
  supervisor/api/hardware.py
Labels: cla-signed, refactor

#2509 Fix add-on state was not fast reflected
  supervisor/addons/addon.py
  supervisor/snapshots/validate.py
Labels: bugfix, cla-signed

#2510 Make add-on file schema more future approved
  supervisor/addons/validate.py
Labels: cla-signed, refactor

#2511 Apply old udev handling like core container
  rootfs/etc/cont-init.d/udev.sh
Labels: cla-signed, refactor

#2516 Show the current core state on message
  supervisor/jobs/decorator.py
Labels: cla-signed, refactor

#2518 Fix memory stats calc
  supervisor/docker/stats.py
Labels: bugfix, cla-signed

#2515 Add API endpoint for add-on for his own config
  supervisor/api/__init__.py
  supervisor/api/addons.py
  supervisor/api/security.py
Labels: cla-signed, new-feature

#2521 Fix cleanup with changed image
  supervisor/addons/__init__.py
Labels: bugfix, cla-signed

#2529 Change Supervisor update flow with AppArmor
  supervisor/supervisor.py
Labels: cla-signed, refactor

#2531 Add core state to /info API
  supervisor/api/info.py
Labels: cla-signed, new-feature

#2536 Fix UI options without filter
  supervisor/addons/options.py
  tests/addons/test_options.py
Labels: bugfix, cla-signed

#2539 Use Alpine 3.13
  .github/workflows/builder.yml
  build.json
Labels: cla-signed

#2543 Fix issue template forms
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, cla-signed

#2545 Small tweaks to issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore

#2548 Add support for hiddev on USB
  supervisor/hardware/policy.py
Labels: cla-signed, refactor

#2549 Add hidraw to USB
  supervisor/hardware/policy.py
Labels: cla-signed, refactor

#2555 Mask folder /dev/bus/usb RW
  supervisor/docker/addon.py
Labels: cla-signed, refactor

#2556 Revert "Mask folder /dev/bus/usb RW"
  supervisor/docker/addon.py
Labels: cla-signed

#2552 Fix Typos in LOGGER
  supervisor/core.py
Labels: chore, cla-signed

#2557 Add some issues and suggestion
  supervisor/core.py
  supervisor/docker/addon.py
Labels: cla-signed, refactor

#2565 Fix path for tmpfs
  supervisor/docker/addon.py
Labels: bugfix, cla-signed

#2569 Kernel modules add-on flag need no extra cap
  supervisor/addons/model.py
  supervisor/addons/utils.py
  supervisor/addons/validate.py
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/const.py
Labels: cla-signed, refactor

#2570 Drop full privileged from audio plugin
  supervisor/docker/audio.py
  supervisor/hardware/const.py
  supervisor/hardware/policy.py
Labels: cla-signed, refactor

#2573 Discovery for vlc telnet
  supervisor/discovery/services/vlc_telnet.py
  tests/discovery/test_vlc_telnet.py
Labels: cla-signed, new-feature

#2575 Fix audio cgroup issue
  supervisor/docker/audio.py
  supervisor/hardware/policy.py
Labels: bugfix, cla-signed

#2578 Fix typo in suggestion
  supervisor/docker/addon.py
Labels: bugfix, cla-signed

#2581 Fix handling with full access / blocked devices
  supervisor/addons/utils.py
  supervisor/addons/validate.py
  supervisor/docker/addon.py
  supervisor/hardware/disk.py
  supervisor/hardware/helper.py
  supervisor/hardware/module.py
  supervisor/hardware/policy.py
  supervisor/host/info.py
  tests/hardware/test_disk.py
  tests/hardware/test_helper.py
  tests/hardware/test_policy.py
Labels: bugfix, cla-signed

#2583 Add capabilities for puleaudio
  supervisor/docker/audio.py
Labels: cla-signed, refactor

#2585 Fix device check if not exists
  supervisor/docker/addon.py
Labels: bugfix, cla-signed

#2589 Allow for static port in Watchdog add-on configuration
  supervisor/addons/addon.py
  supervisor/addons/validate.py
Labels: cla-signed, new-feature

#2591 Update GitHub Issue Form template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, cla-signed

#2592 Fix some issues with the issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: chore, cla-signed

#2593 Support realtime scheduling for add-ons
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
Labels: cla-signed, new-feature

#2599 Imrove the LXC detection
  supervisor/docker/__init__.py
  supervisor/resolution/evaluations/lxc.py
  tests/resolution/evaluation/test_evaluate_lxc.py
Labels: cla-signed, refactor

#2602 Detect host support for CPU realtime + add an option for enable it
  supervisor/const.py
  supervisor/docker/__init__.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
Labels: bugfix, cla-signed

#2601 Show add-on with bad config in log
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/addons/options.py
  tests/addons/test_options.py
Labels: cla-signed, refactor

#2604 Fix small typo in log message
  supervisor/docker/addon.py
Labels: bugfix, cla-signed

#2605 Use the cpu_rt support check also for rtprio
  supervisor/docker/addon.py
  supervisor/docker/audio.py
Labels: bugfix, cla-signed

#2603 Signal frontend to refresh on SU startup
  supervisor/core.py
Labels: cla-signed, new-feature

#2606 Remove not needed call_soon
  supervisor/homeassistant/websocket.py
Labels: cla-signed, refactor

#2607 Add kernel docs about the device classes
  supervisor/hardware/policy.py
Labels: chore, cla-signed

#2608 Send event when add-on changes state
  supervisor/addons/addon.py
  supervisor/const.py
  supervisor/core.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/websocket.py
  tests/homeassistant/test_websocket.py
Labels: cla-signed, new-feature

#2612 Add execution limit for jobs
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, new-feature

#2610 Fix issue with concurrent reads
  supervisor/addons/addon.py
  supervisor/homeassistant/websocket.py
Labels: bugfix, cla-signed

#2615 Fix landingpage on check_api_state
  supervisor/homeassistant/api.py
Labels: cla-signed, refactor

#2614 Add check for pwned secrets to resolution center
  supervisor/addons/addon.py
  supervisor/addons/options.py
  supervisor/core.py
  supervisor/exceptions.py
  supervisor/resolution/check.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/resolution/checks/base.py
  supervisor/resolution/checks/core_security.py
  supervisor/resolution/checks/free_space.py
  supervisor/resolution/const.py
  supervisor/resolution/notify.py
  supervisor/utils/dt.py
  supervisor/utils/pwned.py
  tests/addons/test_options.py
  tests/resolution/check/test_check_addon_pwned.py
Labels: cla-signed, new-feature

#2621 Add home-assistant version to API response
  supervisor/api/addons.py
Labels: bugfix, cla-signed

#2622 Optimize resolution checks / add endpoint to trigger it manual
  supervisor/api/__init__.py
  supervisor/api/resolution.py
  supervisor/core.py
  supervisor/resolution/module.py
Labels: cla-signed, refactor

#2625 Small cleanups with pwned handling
  supervisor/addons/options.py
  supervisor/utils/pwned.py
  tests/addons/test_options.py
Labels: bugfix, cla-signed

#2626 Add /store API
  supervisor/api/__init__.py
  supervisor/api/store.py
  supervisor/api/utils.py
  supervisor/coresys.py
  tests/api/test_store.py
  tests/conftest.py
  tests/fixtures/add-on.json
Labels: cla-signed, new-feature

#2627 Fix k-anonymity handling
  supervisor/utils/pwned.py
Labels: bugfix, cla-signed

#2630 Real-time fixes
  supervisor/docker/__init__.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
Labels: cla-signed, refactor

#2629 Log issues/suggestion with info
  supervisor/resolution/module.py
Labels: cla-signed, refactor

#2631 Add throttle to job execution
  supervisor/homeassistant/secrets.py
  supervisor/host/sound.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/updater.py
  supervisor/utils/__init__.py
  tests/jobs/test_job_decorator.py
  tests/resolution/check/test_check_addon_pwned.py
Labels: cla-signed, refactor

#2632 Fix add-on updates
  supervisor/api/addons.py
  supervisor/api/security.py
  supervisor/api/store.py
Labels: bugfix, cla-signed

#2635 Make homeassistant optional in partial snapshot
  supervisor/api/snapshots.py
  supervisor/snapshots/__init__.py
Labels: cla-signed, missing-documentation, new-feature

#2636 Allways store docker and repository config
  supervisor/snapshots/__init__.py
Labels: bugfix, cla-signed

#2645 Allow use YAML for addon and repository config
  supervisor/const.py
  supervisor/exceptions.py
  supervisor/homeassistant/secrets.py
  supervisor/store/data.py
  supervisor/store/repository.py
  supervisor/utils/__init__.py
  supervisor/utils/yaml.py
  tests/utils/test_yaml.py
Labels: cla-signed, missing-documentation, new-feature
