Repository home-assistant/supervisor, pull requests merged in 2021-09, with the labels that each got.

#3094 Ignore all files and directories that starts with .
  supervisor/store/data.py
  tests/store/test_reading_addons.py
Labels: cla-signed, bugfix

#3097 Ignore rootfs
  supervisor/store/data.py
  tests/store/test_reading_addons.py
Labels: cla-signed, bugfix

#3100 Support USB discovery
  supervisor/homeassistant/module.py
Labels: cla-signed, new-feature

#3110 Print supervisor container logs on failure
  .github/workflows/builder.yml
Labels: cla-signed, ci

#3120 Support OS-Agent Data disk
  pylintrc
  supervisor/api/__init__.py
  supervisor/api/const.py
  supervisor/api/info.py
  supervisor/api/os.py
  supervisor/bootstrap.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/host/manager.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/misc/filter.py
  supervisor/os/__init__.py
  supervisor/os/data_disk.py
  supervisor/os/manager.py
  supervisor/resolution/evaluations/operating_system.py
  supervisor/updater.py
  supervisor/utils/json.py
  tests/api/test_os.py
  tests/jobs/test_job_decorator.py
  tests/os/__init__.py
  tests/os/test_manager.py
  tests/resolution/evaluation/test_evaluate_operating_system.py
Labels: cla-signed, new-feature

#3124 Detect if frontend is not loaded
  supervisor/homeassistant/api.py
  supervisor/homeassistant/core.py
Labels: cla-signed, refactor

#3129 DataDisk reload devices
  supervisor/api/const.py
  supervisor/api/host.py
  supervisor/dbus/agent/datadisk.py
  supervisor/exceptions.py
  supervisor/os/data_disk.py
  supervisor/os/manager.py
  supervisor/utils/gdbus.py
  tests/api/test_os.py
  tests/dbus/agent/test_datadisk.py
  tests/fixtures/io_hass_os_DataDisk-ReloadDevice.fixture
  tests/fixtures/io_hass_os_DataDisk.xml
Labels: cla-signed, refactor

#3132 Using git token + pull image from ghcr.io for tests
  .github/workflows/builder.yml
Labels: cla-signed, ci

#3133 Return list of possible data disk targets
  supervisor/api/__init__.py
  supervisor/api/os.py
  supervisor/bootstrap.py
  supervisor/coresys.py
  supervisor/hardware/data.py
  supervisor/hardware/disk.py
  supervisor/hardware/manager.py
  supervisor/hardware/monitor.py
  supervisor/hardware/policy.py
  supervisor/os/data_disk.py
  tests/addons/test_options.py
  tests/api/test_hardware.py
  tests/api/test_os.py
  tests/hardware/test_data.py
  tests/hardware/test_disk.py
  tests/hardware/test_helper.py
  tests/hardware/test_module.py
  tests/hardware/test_policy.py
  tests/os/test_data_disk.py
Labels: cla-signed, new-feature

#3136 Add startup time and boot_timestamp
  supervisor/api/const.py
  supervisor/api/host.py
  supervisor/dbus/const.py
  supervisor/dbus/systemd.py
  supervisor/host/info.py
  tests/dbus/test_systemd.py
  tests/fixtures/org_freedesktop_systemd1_properties.json
Labels: cla-signed, new-feature

#3145 Revert "Bump voluptuous from 0.12.1 to 0.12.2"
  requirements.txt
Labels: cla-signed, dependencies

#3147 Bump voluptuous from 0.12.1 to 0.12.2
  requirements.txt
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/api/audio.py
  supervisor/api/auth.py
  supervisor/api/backups.py
  supervisor/api/docker.py
  supervisor/api/homeassistant.py
  supervisor/api/host.py
  supervisor/backups/validate.py
  supervisor/discovery/services/adguard.py
  supervisor/discovery/services/almond.py
  supervisor/discovery/services/deconz.py
  supervisor/discovery/services/homematic.py
  supervisor/discovery/services/motioneye.py
  supervisor/discovery/services/mqtt.py
  supervisor/discovery/services/unifi.py
  supervisor/discovery/validate.py
  supervisor/homeassistant/validate.py
  supervisor/services/modules/mqtt.py
  supervisor/services/modules/mysql.py
  supervisor/store/validate.py
  supervisor/validate.py
Labels: cla-signed, dependencies

#3153 Fix UnboundLocalError
  supervisor/homeassistant/core.py
Labels: cla-signed, bugfix

#3154 Fix typo in vcn_version
  .github/workflows/ci.yaml
Labels: cla-signed, ci

#3155 Fix pyupgrade precommit
  .pre-commit-config.yaml
  supervisor/utils/json.py
Labels: cla-signed, dependencies

#3162 Use deepmerge for options
  requirements.txt
  supervisor/addons/addon.py
  supervisor/store/__init__.py
  tests/addons/test_addon.py
  tests/api/test_store.py
  tests/conftest.py
  tests/const.py
  tests/fixtures/addons/core/samba/build.yaml
  tests/fixtures/addons/core/samba/config.yaml
  tests/fixtures/addons/git/.empty
  tests/fixtures/addons/local/ssh/build.yaml
  tests/fixtures/addons/local/ssh/config.yaml
  tests/store/test_builtin_stores.py
Labels: cla-signed, bugfix

#3167 Use `=` instead of deprecated `:` as security option separator
  .github/workflows/builder.yml
  scripts/supervisor.sh
  supervisor/docker/addon.py
Labels: enhancement, cla-signed

#3166 Add all_plugins to cleanup code
  supervisor/misc/filter.py
  supervisor/plugins/manager.py
  supervisor/resolution/checks/plugin_trust.py
Labels: cla-signed, refactor

#3168 Return early in validate
  supervisor/utils/codenotary.py
Labels: cla-signed, refactor

#3173 Fix observer security filter
  supervisor/api/middleware/security.py
Labels: cla-signed, bugfix
