Repository home-assistant/supervisor, pull requests merged in 2022-03, with the labels that each got.

#3474 Use enum in arch to platform map
  supervisor/docker/interface.py
Labels: cla-signed, chore

#3473 Error response handling & tests
  supervisor/utils/codenotary.py
  tests/utils/test_codenotary.py
Labels: cla-signed, bugfix

#3476 Fix partial backup with Core
  supervisor/api/backups.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
Labels: cla-signed, bugfix

#3483 Remove Debian buster from supported OS
  supervisor/resolution/evaluations/operating_system.py
Labels: cla-signed, breaking-change

#3487 Add unsupported message if no systemd-resolved
  supervisor/dbus/const.py
  supervisor/dbus/manager.py
  supervisor/dbus/resolved.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/resolved.py
  tests/dbus/test_resolved.py
  tests/fixtures/org_freedesktop_resolve1.xml
  tests/fixtures/org_freedesktop_resolve1_Manager.json
  tests/resolution/evaluation/test_evaluate_resolved.py
Labels: cla-signed, new-feature

#3488 Update whoami URL
  supervisor/utils/whoami.py
Labels: cla-signed, chore

#3490 Use full version in actions to prevent auto-updates
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
  .github/workflows/release-drafter.yml
  .github/workflows/stale.yml
Labels: cla-signed, ci

#3493 Add collapse-after for dependencies
  .github/release-drafter.yml
Labels: cla-signed, ci

#3500 Reduce floot on startup
  supervisor/resolution/checks/core_trust.py
  supervisor/resolution/checks/plugin_trust.py
  supervisor/utils/codenotary.py
Labels: cla-signed, refactor

#3504 Disable CAS until it work
  .github/workflows/builder.yml
  supervisor/utils/codenotary.py
  tests/test_security.py
  tests/utils/test_codenotary.py
Labels: cla-signed, breaking-change

#3507 Get arch from config and not data when generating image
  supervisor/addons/model.py
Labels: cla-signed, bugfix

#3508 Remove name argument to _restore
  supervisor/backups/backup.py
Labels: cla-signed, bugfix

#3509 Add backup and restore to CI
  .github/workflows/builder.yml
Labels: cla-signed, ci

#3521 Fix issues with old protection flag
  supervisor/backups/validate.py
  tests/backups/test_validate.py
Labels: cla-signed, bugfix

#3528 Apply network settings on start to fix defaults
  supervisor/host/manager.py
  supervisor/host/network.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  tests/conftest.py
  tests/fixtures/org_freedesktop_NetworkManager-ActivateConnection.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings_1-GetSettings.json
  tests/fixtures/org_freedesktop_systemd1-ListUnits.json
  tests/fixtures/org_freedesktop_systemd1_Manager.json
  tests/host/test_manager.py
  tests/host/test_network.py
Labels: enhancement, cla-signed

#3506 Enable CAS for Add-ons
  .github/workflows/builder.yml
  supervisor/resolution/checks/core_trust.py
  supervisor/resolution/checks/plugin_trust.py
  supervisor/security.py
  supervisor/utils/codenotary.py
  tests/test_security.py
  tests/utils/test_codenotary.py
Labels: cla-signed, refactor
