Repository home-assistant/supervisor, pull requests merged in 2022-01, with the labels that each got.

#3389 Fix copy-paste error in pydoc for test_almond.py
  tests/discovery/test_almond.py
Labels: cla-signed, chore

#3393 Fix copy/paste issues in tests
  tests/discovery/test_adguard.py
  tests/discovery/test_almond.py
  tests/discovery/test_deconz.py
  tests/discovery/test_homematic.py
  tests/discovery/test_motioneye.py
  tests/discovery/test_mqtt.py
  tests/discovery/test_ozw.py
  tests/discovery/test_unifi.py
  tests/discovery/test_zwave_js.py
Labels: cla-signed, refactor

#3392 Add Add-on discovery schema for RTSPtoWebRTC
  supervisor/discovery/services/rtsp_to_webrtc.py
  tests/discovery/test_rtsp_to_webrtc.py
Labels: cla-signed, cla-error

#3305 Notify HA Core when backup is being executed
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/module.py
  supervisor/homeassistant/websocket.py
  tests/backups/conftest.py
  tests/backups/test_manager.py
Labels: cla-signed, new-feature

#3401 Release all pending WebSocket calls on connection close
  supervisor/homeassistant/websocket.py
Labels: enhancement, cla-signed

#3400 Avoid sending backup start notification to HA Core 2021.12
  supervisor/homeassistant/websocket.py
Labels: cla-signed, bugfix

#3403 Fix local Add-on restore on blank instance
  supervisor/docker/addon.py
Labels: bug, cla-signed

#3409 Add backup size to list API
  supervisor/api/backups.py
Labels: enhancement, cla-signed

#3413 Add Core Update API
  supervisor/api/__init__.py
  supervisor/api/info.py
  supervisor/api/root.py
  supervisor/api/supervisor.py
  tests/api/test_root.py
  tests/api/test_supervisor.py
Labels: cla-signed, new-feature

#3421 Support dynamic device access cgroup
  supervisor/bus.py
  supervisor/docker/addon.py
  tests/test_bus.py
Labels: cla-signed, new-feature

#3422 Fixing IO on the loop with docker HW events
  supervisor/docker/addon.py
Labels: cla-signed, bugfix
