Repository home-assistant/supervisor, pull requests merged in 2022-08, with the labels that each got.

#3765 Fix keyerror on unnamed containers
  supervisor/docker/monitor.py
Labels: cla-signed, bugfix

#3766 Watchdog shouldn't rebuild addons
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#3762 addons/info returns info on all addons
  supervisor/addons/addon.py
  supervisor/api/__init__.py
  supervisor/api/addons.py
  supervisor/exceptions.py
  tests/api/test_addons.py
Labels: cla-signed, bugfix

#3768 Add fields back for legacy addons info routing
  supervisor/api/__init__.py
  supervisor/api/store.py
  tests/api/test_addons.py
Labels: cla-signed, bugfix

#3771 Attach is in executor, use `call_soon_threadsafe`
  supervisor/docker/interface.py
Labels: cla-signed, bugfix

#3773 Healthy/Unhealthy state means addon started
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#3778 Mark CGroup V2 supported on Home Assistant OS
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/cgroup.py
  supervisor/resolution/evaluations/docker_configuration.py
  tests/resolution/evaluation/test_evaluate_cgroup.py
  tests/resolution/evaluation/test_evaluate_docker_configuration.py
Labels: cla-signed, new-feature

#3779 Set limits on watchdog retries
  supervisor/addons/addon.py
  supervisor/addons/const.py
  supervisor/exceptions.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/core.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/const.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, new-feature

#3787 Absolute imports to relative imports
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/__init__.py
  supervisor/bootstrap.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/connection.py
  supervisor/discovery/services/adguard.py
  supervisor/discovery/services/almond.py
  supervisor/discovery/services/deconz.py
  supervisor/discovery/services/homematic.py
  supervisor/discovery/services/mqtt.py
  supervisor/discovery/services/ozw.py
  supervisor/discovery/services/rtsp_to_webrtc.py
  supervisor/discovery/services/unifi.py
  supervisor/discovery/services/vlc_telnet.py
  supervisor/discovery/services/zwave_js.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  supervisor/docker/monitor.py
  supervisor/hardware/disk.py
  supervisor/hardware/manager.py
  supervisor/homeassistant/core.py
  supervisor/host/info.py
  supervisor/host/network.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/validate.py
  supervisor/resolution/checks/dns_server_failure.py
  supervisor/resolution/checks/dns_server_ipv6_error.py
  supervisor/services/modules/mqtt.py
  supervisor/services/modules/mysql.py
  supervisor/store/__init__.py
  supervisor/store/const.py
  supervisor/store/validate.py
Labels: cla-signed, refactor

#3769 Add auto update option
  supervisor/addons/__init__.py
  supervisor/addons/const.py
  supervisor/api/supervisor.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
  supervisor/const.py
  supervisor/core.py
  supervisor/homeassistant/core.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/misc/tasks.py
  supervisor/os/manager.py
  supervisor/plugins/audio.py
  supervisor/plugins/cli.py
  supervisor/plugins/const.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/supervisor_version.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/validate.py
  tests/addons/test_addon.py
  tests/api/test_supervisor.py
  tests/backups/conftest.py
  tests/backups/test_manager.py
  tests/homeassistant/test_core.py
  tests/jobs/test_job_decorator.py
  tests/os/test_manager.py
  tests/plugins/test_plugin_base.py
  tests/resolution/evaluation/test_evaluate_supervisor_version.py
Labels: enhancement, cla-signed

#3724 Support for Docker manifests base images add-on build
  supervisor/addons/build.py
  supervisor/addons/validate.py
  tests/addons/test_build.py
  tests/addons/test_config.py
  tests/fixtures/build-config-manifest.json
Labels: cla-signed, new-feature

#3783 Handle timedrift better if not synchronized
  supervisor/core.py
Labels: cla-signed, refactor

#3795 Supervisor updated before addon repositories
  supervisor/misc/tasks.py
  supervisor/store/__init__.py
  tests/store/test_custom_repository.py
  tests/store/test_store_manager.py
Labels: cla-signed, new-feature

#3796 Attempt plugin update before failing job condition
  supervisor/jobs/decorator.py
  tests/addons/test_addon.py
  tests/homeassistant/test_core.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, new-feature

#3802 Fix memory calculation for cgroupv2
  supervisor/docker/stats.py
  tests/docker/test_stats.py
  tests/fixtures/container_stats.json
  tests/fixtures/container_stats_cgroupv1.json
  tests/fixtures/container_stats_cgroupv2.json
Labels: cla-signed, bugfix

#3807 Set autoreconnect to true for interfaces
  supervisor/dbus/network/setting/generate.py
  tests/dbus/network/setting/test_init.py
Labels: cla-signed, bugfix

#3801 Update architecture compatibility JSON file
  supervisor/data/arch.json
Labels: cla-signed, new-feature

#3804 Create asyncio loop explicitly
  supervisor/__main__.py
Labels: cla-signed, chore

#3815 Watchdog restarts addons on successful but unexpected exits
  supervisor/addons/addon.py
  supervisor/hardware/helper.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#3811 Rename dns checks to fit pattern
  supervisor/resolution/checks/dns_server.py
  supervisor/resolution/checks/dns_server_ipv6.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_dns_server_failure.py
  tests/resolution/check/test_check_dns_server_ipv6_error.py
Labels: cla-signed, refactor

#3810 Remove static-only fields when method is auto
  supervisor/dbus/network/setting/__init__.py
  tests/dbus/network/setting/test_init.py
Labels: cla-signed, bugfix

#3806 Identify and handle dhcp issues
  supervisor/dbus/const.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/connection.py
  supervisor/host/network.py
  supervisor/resolution/checks/network_interface.py
  supervisor/resolution/const.py
  tests/fixtures/org_freedesktop_NetworkManager_Connection_Active_1.json
  tests/host/test_network.py
  tests/resolution/check/test_check_network_interface.py
Labels: cla-signed, bugfix

#3781 Improve system behavior on low memory situation
  supervisor/docker/addon.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/observer.py
Labels: cla-signed, new-feature

#3818 Fire events on issue changes
  supervisor/api/__init__.py
  supervisor/api/resolution.py
  supervisor/const.py
  supervisor/resolution/fixup.py
  supervisor/resolution/fixups/base.py
  supervisor/resolution/module.py
  tests/api/test_resolution.py
  tests/resolution/test_resolution_manager.py
Labels: cla-signed, new-feature

#3820 Simplify watchdog container rules
  supervisor/addons/addon.py
Labels: cla-signed, bugfix

#3822 Fix suggestion test to be order agnostic
  tests/api/test_resolution.py
Labels: cla-signed, refactor

#3821 Bump ruamel.yaml to 0.17.21
  requirements.txt
Labels: cla-signed, dependencies

#3823 Store load ignores supervisor updated condition
  supervisor/store/__init__.py
  tests/store/test_custom_repository.py
Labels: cla-signed, bugfix

#3826 No bool conversion in resolution test
  tests/api/test_resolution.py
Labels: cla-signed, refactor

#3829 Use link-local instead disabled for ipv6
  supervisor/dbus/const.py
  supervisor/dbus/network/setting/generate.py
  supervisor/host/network.py
  tests/dbus/network/setting/test_init.py
Labels: cla-signed, refactor

#3830 Network connection check only about ipv4
  supervisor/host/network.py
  supervisor/resolution/checks/network_interface_ipv4.py
  supervisor/resolution/const.py
  tests/resolution/check/test_check_network_interface_ipv4.py
Labels: cla-signed, bugfix
