Repository home-assistant/supervisor, pull requests merged in 2022-09, with the labels that each got.

#3839 supervisor/backup: Ensure compressed flag is respected by homeassistant
  supervisor/backups/backup.py
Labels: cla-signed, bugfix

#3837 Fire issue events on HA's bus
  supervisor/const.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/websocket.py
  supervisor/resolution/module.py
  tests/resolution/test_resolution_manager.py
Labels: cla-signed, bugfix

#3836 Reduce connectivity checks
  supervisor/api/network.py
  supervisor/dbus/const.py
  supervisor/dbus/network/__init__.py
  supervisor/host/network.py
  supervisor/jobs/decorator.py
  supervisor/misc/tasks.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/base.py
  supervisor/resolution/evaluations/connectivity_check.py
  supervisor/resolution/evaluations/supervisor_version.py
  supervisor/supervisor.py
  supervisor/utils/dbus.py
  tests/api/test_network.py
  tests/conftest.py
  tests/dbus/network/test_network_manager.py
  tests/host/test_connectivity.py
  tests/host/test_network.py
  tests/jobs/test_job_decorator.py
  tests/misc/test_connectivity_task.py
  tests/resolution/evaluation/test_connectivity_check.py
  tests/test_supervisor.py
Labels: cla-signed, new-feature

#3814 Create issue+suggestion when no recent backup
  supervisor/api/__init__.py
  supervisor/api/backups.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
  supervisor/const.py
  supervisor/resolution/checks/backups.py
  supervisor/resolution/checks/free_space.py
  supervisor/resolution/const.py
  supervisor/resolution/fixups/system_clear_full_backup.py
  tests/api/test_backups.py
  tests/conftest.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_free_space.py
  tests/resolution/fixup/test_system_clear_full_backup.py
  tests/resolution/fixup/test_system_create_full_backup.py
Labels: cla-signed, new-feature

#3844 Add missing await in backup check
  supervisor/resolution/checks/backups.py
Labels: cla-signed, bugfix

#3845 Add tests for backups check
  tests/conftest.py
  tests/resolution/check/test_check_backups.py
Labels: cla-signed, ci

#3847 Replace loop test fixture with event_loop
  tests/conftest.py
Labels: cla-signed, bugfix

#3853 Bump supported docker version
  supervisor/docker/manager.py
Labels: cla-signed, chore

#3854 Dbus refactor and tests
  supervisor/api/host.py
  supervisor/dbus/hostname.py
  supervisor/dbus/logind.py
  supervisor/dbus/network/accesspoint.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/network/wireless.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/host/network.py
  supervisor/host/services.py
  supervisor/os/manager.py
  supervisor/utils/dbus.py
  tests/conftest.py
  tests/dbus/agent/test_apparmor.py
  tests/dbus/agent/test_cgroup.py
  tests/dbus/agent/test_datadisk.py
  tests/dbus/agent/test_system.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_accesspoint.py
  tests/dbus/network/test_dns.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_settings.py
  tests/dbus/network/test_wireless.py
  tests/dbus/test_hostname.py
  tests/dbus/test_login.py
  tests/dbus/test_rauc.py
  tests/dbus/test_systemd.py
  tests/dbus/test_timedate.py
  tests/fixtures/de_pengutronix_rauc.xml
  tests/fixtures/de_pengutronix_rauc_Installer.json
  tests/fixtures/de_pengutronix_rauc_Installer_GetSlotStatus.json
  tests/fixtures/de_pengutronix_rauc_Installer_Mark.json
  tests/fixtures/org_freedesktop_NetworkManager_Devices_3-RequestScan.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings-AddConnection.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings-ReloadConnections.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings_1-Delete.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings_1-Update.json
  tests/fixtures/org_freedesktop_hostname1-SetStaticHostname.json
  tests/fixtures/org_freedesktop_systemd1-ListUnits.json
  tests/fixtures/org_freedesktop_systemd1-ReloadOrRestartUnit.json
  tests/fixtures/org_freedesktop_systemd1-RestartUnit.json
  tests/fixtures/org_freedesktop_systemd1-StartUnit.json
  tests/fixtures/org_freedesktop_systemd1-StopUnit.json
  tests/fixtures/org_freedesktop_timedate1-SetNTP.json
  tests/fixtures/org_freedesktop_timedate1-SetTime.json
  tests/host/test_network.py
Labels: cla-signed, refactor

#3860 Share MessageBus across dbus objects
  supervisor/core.py
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/agent/apparmor.py
  supervisor/dbus/agent/cgroup.py
  supervisor/dbus/agent/datadisk.py
  supervisor/dbus/agent/system.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/accesspoint.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/network/wireless.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/utils/dbus.py
  tests/api/test_dns.py
  tests/api/test_host.py
  tests/api/test_os.py
  tests/conftest.py
  tests/dbus/agent/test_agent.py
  tests/dbus/agent/test_apparmor.py
  tests/dbus/agent/test_cgroup.py
  tests/dbus/agent/test_datadisk.py
  tests/dbus/agent/test_system.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_accesspoint.py
  tests/dbus/test_hostname.py
  tests/dbus/test_login.py
  tests/dbus/test_rauc.py
  tests/dbus/test_resolved.py
  tests/dbus/test_systemd.py
  tests/dbus/test_timedate.py
  tests/os/test_data_disk.py
  tests/test_coresys.py
  tests/utils/test_dbus.py
Labels: cla-signed, refactor

#3864 Use the same python version for all steps
  .github/workflows/ci.yaml
Labels: cla-signed, ci

#3857 Cleanup evaluations
  supervisor/resolution/evaluations/apparmor.py
  supervisor/resolution/evaluations/cgroup.py
  supervisor/resolution/evaluations/container.py
  supervisor/resolution/evaluations/content_trust.py
  supervisor/resolution/evaluations/dbus.py
  supervisor/resolution/evaluations/dns_server.py
  supervisor/resolution/evaluations/docker_configuration.py
  supervisor/resolution/evaluations/docker_version.py
  supervisor/resolution/evaluations/job_conditions.py
  supervisor/resolution/evaluations/lxc.py
  supervisor/resolution/evaluations/network_manager.py
  supervisor/resolution/evaluations/operating_system.py
  supervisor/resolution/evaluations/os_agent.py
  supervisor/resolution/evaluations/privileged.py
  supervisor/resolution/evaluations/resolved.py
  supervisor/resolution/evaluations/source_mods.py
  supervisor/resolution/evaluations/systemd.py
  tests/resolution/evaluation/test_evaluate_cgroup.py
Labels: cla-signed, refactor

#3862 Refactor to dbus-next proxy interfaces
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/agent/apparmor.py
  supervisor/dbus/agent/cgroup.py
  supervisor/dbus/agent/datadisk.py
  supervisor/dbus/agent/system.py
  supervisor/dbus/hostname.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/network/wireless.py
  supervisor/dbus/rauc.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/exceptions.py
  supervisor/utils/dbus.py
  tests/api/test_network.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/fixtures/de_pengutronix_rauc_Installer_GetSlotStatus.json
  tests/fixtures/io_hass_os_AppArmor-LoadProfile.json
  tests/fixtures/io_hass_os_AppArmor-UnloadProfile.json
  tests/fixtures/io_hass_os_CGroup-AddDevicesAllowed.json
  tests/fixtures/io_hass_os_DataDisk-ChangeDevice.json
  tests/fixtures/io_hass_os_DataDisk-ReloadDevice.json
  tests/fixtures/io_hass_os_System-ScheduleWipeDevice.json
  tests/fixtures/org_freedesktop_NetworkManager-ActivateConnection.json
  tests/fixtures/org_freedesktop_NetworkManager-CheckConnectivity.json
  tests/fixtures/org_freedesktop_NetworkManager_Devices_3-GetAllAccessPoints.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings-AddConnection.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings-ReloadConnections.json
  tests/fixtures/org_freedesktop_NetworkManager_Settings_1-GetSettings.json
  tests/fixtures/org_freedesktop_systemd1-ListUnits.json
  tests/fixtures/org_freedesktop_systemd1-ReloadOrRestartUnit.json
  tests/fixtures/org_freedesktop_systemd1-RestartUnit.json
  tests/fixtures/org_freedesktop_systemd1-StartUnit.json
  tests/fixtures/org_freedesktop_systemd1-StopUnit.json
  tests/host/test_connectivity.py
  tests/host/test_network.py
  tests/jobs/test_job_decorator.py
  tests/utils/test_dbus.py
Labels: cla-signed, refactor

#3866 Reduce patching call dbus in tests
  tests/api/test_network.py
  tests/host/test_network.py
Labels: cla-signed, refactor

#3865 Fix network vlan api
  supervisor/api/network.py
  supervisor/host/network.py
  tests/api/test_network.py
Labels: cla-signed, bugfix

#3868 Only update HW condition at once
  supervisor/docker/addon.py
Labels: cla-signed, bugfix

#3872 Listen for dbus property changes
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/agent/apparmor.py
  supervisor/dbus/agent/cgroup.py
  supervisor/dbus/agent/datadisk.py
  supervisor/dbus/agent/system.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/accesspoint.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/ip_configuration.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/network/wireless.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/host/control.py
  supervisor/host/manager.py
  supervisor/host/network.py
  supervisor/os/manager.py
  supervisor/utils/dbus.py
  tests/api/test_dns.py
  tests/api/test_host.py
  tests/common.py
  tests/conftest.py
  tests/dbus/agent/test_agent.py
  tests/dbus/agent/test_apparmor.py
  tests/dbus/agent/test_datadisk.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_dns.py
  tests/dbus/network/test_interface.py
  tests/dbus/network/test_ip_configuration.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_setting.py
  tests/dbus/network/test_wireless.py
  tests/dbus/test_hostname.py
  tests/dbus/test_interface.py
  tests/dbus/test_rauc.py
  tests/dbus/test_resolved.py
  tests/dbus/test_timedate.py
  tests/fixtures/apparmor/.empty/.empty
  tests/host/test_control.py
  tests/host/test_manager.py
  tests/host/test_network.py
  tests/host/test_supported_features.py
  tests/resolution/evaluation/test_evaluate_network_manager.py
  tests/resolution/evaluation/test_evaluate_resolved.py
Labels: cla-signed, new-feature

#3873 Empty string in gateway returns none
  supervisor/dbus/network/ip_configuration.py
  tests/dbus/network/test_ip_configuration.py
Labels: cla-signed, bugfix

#3877 Switch from dbus-next to dbus-fast
  requirements.txt
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/utils/dbus.py
  tests/common.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_accesspoint.py
  tests/dbus/test_interface.py
  tests/host/test_network.py
  tests/utils/test_dbus.py
Labels: cla-signed, dependencies

#3878 Revert "Switch from dbus-next to dbus-fast"
  requirements.txt
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/utils/dbus.py
  tests/common.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_accesspoint.py
  tests/dbus/test_interface.py
  tests/host/test_network.py
  tests/utils/test_dbus.py
Labels: cla-signed, dependencies

#3882 Switch from dbus-next to dbus-fast
  requirements.txt
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/utils/dbus.py
  tests/common.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_accesspoint.py
  tests/dbus/test_interface.py
  tests/host/test_network.py
  tests/utils/test_dbus.py
Labels: cla-signed, dependencies

#3885 Use dbus-fast unpack_variants option
  requirements.txt
  supervisor/dbus/network/setting/__init__.py
  supervisor/host/network.py
  supervisor/utils/dbus.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/test_interface.py
  tests/host/test_network.py
  tests/utils/test_dbus.py
Labels: cla-signed, dependencies, refactor

#3886 Add restart policy evaluation
  supervisor/docker/const.py
  supervisor/docker/interface.py
  supervisor/docker/observer.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/restart_policy.py
  tests/fixtures/container_attrs.json
  tests/resolution/evaluation/test_restart_policy.py
Labels: cla-signed, new-feature

#3891 Check if issue in list, not end of list in test
  tests/resolution/check/test_check.py
Labels: bugfix

#3889 Add portainer as container orchestra
  supervisor/resolution/evaluations/container.py
Labels: cla-signed, breaking-change

#3892 Replace __del__ with explicit disconnect
  supervisor/dbus/interface.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/wireless.py
  tests/dbus/network/test_connection.py
  tests/dbus/network/test_interface.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_wireless.py
Labels: cla-signed, bugfix

#3893 Attach event monitor after addon restore
  .github/workflows/builder.yml
  supervisor/addons/__init__.py
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#3898 Bad introspection causes DBus error not KeyError
  supervisor/dbus/interface.py
  supervisor/utils/dbus.py
  tests/fixtures/test_no_properties_interface.xml
  tests/utils/test_dbus.py
Labels: cla-signed, bugfix

#3899 Bump dbus-fast from 1.14.0 to 1.15.1
  requirements.txt
Labels: cla-signed, dependencies

#3901 Don't disconnect in executor
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/interface.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/wireless.py
  supervisor/dbus/utils.py
  supervisor/utils/dbus.py
  tests/dbus/test_interface.py
Labels: cla-signed, bugfix

#3902 Manual stop true after a reboot
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#3904 Bump HA timeout to match S6_SERVICES_GRACETIME
  supervisor/docker/homeassistant.py
Labels: cla-signed, chore

#3911 No unpack variants for property sets
  supervisor/utils/dbus.py
  tests/api/test_supervisor.py
Labels: cla-signed, bugfix
