Repository home-assistant/supervisor, pull requests merged in 2022-02, with the labels that each got.

#3378 backups: Add support for creating fully uncompressed backups
  supervisor/api/backups.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
  supervisor/const.py
  tests/backups/test_manager.py
Labels: cla-signed, new-feature

#3430 ESPHome default repo for new installations
  supervisor/validate.py
Labels: cla-signed, new-feature

#3436 Fix bashio-typo in watchdog service
  rootfs/etc/services.d/watchdog/run
Labels: cla-signed, bugfix

#3382 Using CAS for content-trust
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  Dockerfile
  build.yaml
  requirements.txt
  rootfs/root/.cas-trusted-signing-pub-key
  supervisor/docker/interface.py
  supervisor/resolution/evaluations/source_mods.py
  supervisor/security.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/utils/codenotary.py
  tests/resolution/evaluation/test_evaluate_source_mods.py
Labels: enhancement, cla-signed

#3438 Add suffix hash on CAS CI
  .github/workflows/builder.yml
Labels: ci

#3440 Fix source-mod detection calculation
  .github/workflows/builder.yml
Labels: cla-signed, ci

#3442 Hash correct folder in source_mods tests
  tests/resolution/evaluation/test_evaluate_source_mods.py
Labels: cla-signed, test

#3452 Ignore corrupted databases in backup
  supervisor/homeassistant/module.py
Labels: cla-signed, chore

#3450 Add add-on support for CAS
  supervisor/addons/const.py
  supervisor/addons/model.py
  supervisor/addons/utils.py
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/api/const.py
  supervisor/docker/addon.py
  supervisor/security.py
  tests/test_security.py
Labels: cla-signed, new-feature

#3459 Add dbus support to plugin-dns
  supervisor/docker/addon.py
  supervisor/docker/const.py
  supervisor/docker/dns.py
Labels: cla-signed, refactor

#3451 New Backup format for core
  requirements.txt
  supervisor/addons/addon.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/backups/utils.py
  supervisor/backups/validate.py
  supervisor/exceptions.py
  supervisor/homeassistant/module.py
  supervisor/utils/tar.py
  tests/backups/conftest.py
  tests/backups/test_manager.py
  tests/resolution/fixup/test_clear_full_backup.py
  tests/utils/test_tarfile.py
Labels: cla-signed, breaking-change

#3462 Add CAS configs to image
  rootfs/root/.cas/config.json
Labels: cla-signed, chore

#3464 Create a backup on add-on auto update
  supervisor/misc/tasks.py
Labels: cla-signed, new-feature

#3463 Partial backup v1 bugfix
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
  tests/backups/test_validate.py
Labels: cla-signed, bugfix

#3441 Disable diagnostic on dev/unsupported
  supervisor/core.py
Labels: cla-signed, refactor

#3469 Test CI codenotary timeout of 15sec for DNS plugin issues
  supervisor/utils/codenotary.py
Labels: cla-signed, chore

#3470 Fix CI warning "[: =~: binary operator expected"
  .github/workflows/builder.yml
Labels: cla-signed, ci
