Repository home-assistant/supervisor, pull requests merged in 2022-07, with the labels that each got.

#3709 Bump black in pre-commit
  .pre-commit-config.yaml
Labels: cla-signed, dependencies

#3720 Docker info more robust
  supervisor/docker/__init__.py
Labels: cla-signed, bugfix

#3721 Branch names can contain periods
  supervisor/validate.py
Labels: cla-signed, bugfix

#3722 Output backup log on error
  supervisor/addons/addon.py
Labels: cla-signed, refactor

#3726 Bump atomicwrites
  requirements.txt
Labels: cla-signed, dependencies

#3739 Fix add-on memory calculation
  supervisor/docker/stats.py
Labels: cla-signed, bugfix

#3725 Docker events based watchdog and docker healthchecks
  supervisor/addons/addon.py
  supervisor/addons/const.py
  supervisor/bootstrap.py
  supervisor/const.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/docker/__init__.py
  supervisor/docker/const.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  supervisor/docker/monitor.py
  supervisor/docker/supervisor.py
  supervisor/exceptions.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/core.py
  supervisor/misc/tasks.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/const.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  tests/addons/test_addon.py
  tests/conftest.py
  tests/docker/test_interface.py
  tests/docker/test_monitor.py
  tests/homeassistant/test_home_assistant_watchdog.py
  tests/plugins/test_dns.py
  tests/plugins/test_plugin_base.py
  tests/resolution/evaluation/test_evaluate_container.py
Labels: cla-signed, new-feature

#3746 Fix addons always unknown after install
  supervisor/addons/__init__.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#3747 Increase max line size for ingress addons
  supervisor/api/__init__.py
Labels: cla-signed, bugfix

#3752 Pass supervisor debug value to audio
  supervisor/plugins/audio.py
  tests/plugins/test_audio.py
Labels: cla-signed, new-feature

#3756 Update supervisor before auto-updating others
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/misc/tasks.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, new-feature
