Repository home-assistant/supervisor, pull requests merged in 2022-05, with the labels that each got.

#3613 Using job limit ONCE for integrity
  supervisor/security/module.py
Labels: cla-signed, refactor

#3614 Rework fixups & Add integrity
  requirements_tests.txt
  supervisor/resolution/const.py
  supervisor/resolution/fixup.py
  supervisor/resolution/fixups/base.py
  supervisor/resolution/fixups/store_execute_reload.py
  supervisor/resolution/fixups/store_execute_remove.py
  supervisor/resolution/fixups/store_execute_reset.py
  supervisor/resolution/fixups/system_clear_full_backup.py
  supervisor/resolution/fixups/system_create_full_backup.py
  supervisor/resolution/fixups/system_execute_integrity.py
  supervisor/security/module.py
  tests/resolution/fixup/test_fixup.py
  tests/resolution/fixup/test_system_clear_full_backup.py
  tests/resolution/fixup/test_system_create_full_backup.py
  tests/resolution/fixup/test_system_execute_integrity.py
Labels: cla-signed, new-feature

#3628 Don't include addresses in network update
  supervisor/dbus/network/setting/__init__.py
  tests/dbus/network/setting/test_init.py
Labels: cla-signed, bugfix

#3631 Revert "OS latest version set from upgrade path"
  supervisor/updater.py
  tests/test_updater.py
Labels: cla-signed, bugfix

#3634 Bump awesomeversion to 22.5.1
  requirements.txt
Labels: cla-signed, dependencies

#3635 Fix update issues
  requirements.txt
Labels: cla-signed

#3337 Use volume as Docker storage location
  .devcontainer/devcontainer.json
Labels: cla-signed, chore, performance

#3632 OS latest version set from upgrade path
  supervisor/updater.py
  tests/test_updater.py
Labels: cla-signed, new-feature

#3630 Support new s6 overlay
  rootfs/etc/cont-init.d/udev.sh
  rootfs/etc/services.d/supervisor/finish
  rootfs/etc/services.d/supervisor/run
  rootfs/etc/services.d/watchdog/finish
  rootfs/etc/services.d/watchdog/run
Labels: cla-signed, chore

#3646 Respect capitialization of network interfaces
  supervisor/api/network.py
Labels: cla-signed, bugfix

#3651 Catch assertion error on git pull
  supervisor/store/git.py
Labels: cla-signed, bugfix
