Repository home-assistant/supervisor, pull requests merged in 2022-10, with the labels that each got.

#3915 Adjust stale bot
  .github/workflows/stale.yml
Labels: cla-signed, chore

#3925 Don't sync unmanaged interfaces
  supervisor/dbus/network/interface.py
  tests/dbus/network/test_interface.py
  tests/fixtures/org_freedesktop_NetworkManager_Device_35.json
Labels: cla-signed, Hacktoberfest, refactor

#3926 Fix property change debug log
  supervisor/utils/dbus.py
Labels: cla-signed, Hacktoberfest, bugfix

#3932 Ask for system information in bug reports
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: cla-signed, Hacktoberfest, ci

#3945 Fix host reload test
  tests/host/test_manager.py
Labels: cla-signed, Hacktoberfest, ci

#3948 Add unhealthy reasons to block message
  supervisor/jobs/decorator.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, Hacktoberfest

#3949 Job conditions take a list
  supervisor/host/network.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, Hacktoberfest

#3291 Add enhanced logging REST endpoints using systemd-journal-gatewayd
  supervisor/api/__init__.py
  supervisor/api/host.py
  supervisor/api/utils.py
  supervisor/data/syslog-identifiers.json
  supervisor/docker/addon.py
  supervisor/exceptions.py
  supervisor/host/const.py
  supervisor/host/logs.py
  supervisor/host/manager.py
  tests/api/middleware/test_security.py
  tests/api/test_addons.py
  tests/api/test_audio.py
  tests/api/test_dns.py
  tests/api/test_homeassistant.py
  tests/api/test_host.py
  tests/api/test_multicast.py
  tests/api/test_supervisor.py
  tests/common.py
  tests/conftest.py
  tests/fixtures/logs_boot_ids.txt
  tests/fixtures/logs_docker_container.txt
  tests/fixtures/logs_host.txt
  tests/fixtures/logs_identifiers.txt
  tests/host/test_logs.py
  tests/host/test_manager.py
Labels: cla-signed, new-feature

#3955 Ignore veth changes
  supervisor/dbus/interface.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/utils/dbus.py
  tests/conftest.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/test_interface.py
  tests/utils/test_dbus.py
Labels: cla-signed, Hacktoberfest, bugfix

#3951 Events when unhealthy/unsupported changes
  supervisor/homeassistant/const.py
  supervisor/resolution/data.py
  supervisor/resolution/module.py
  tests/host/test_network.py
  tests/resolution/test_resolution_manager.py
Labels: cla-signed, Hacktoberfest, new-feature

#3950 Unsupported check for journal gateway
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/systemd_journal.py
  tests/resolution/evaluation/test_evaluate_systemd_journal.py
Labels: cla-signed, Hacktoberfest, new-feature

#3956 Add action concurrency
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
Labels: cla-signed, Hacktoberfest, ci

#3974 Make host log endpoints cli friendly
  supervisor/api/const.py
  supervisor/api/host.py
  supervisor/host/logs.py
  tests/api/test_host.py
  tests/fixtures/logs_identifiers.txt
  tests/host/test_logs.py
Labels: cla-signed, Hacktoberfest, bugfix
