Repository home-assistant/supervisor, pull requests merged in 2022-06, with the labels that each got.

#3665 Move repository urls to store settings file
  supervisor/api/store.py
  supervisor/api/supervisor.py
  supervisor/backups/backup.py
  supervisor/backups/validate.py
  supervisor/config.py
  supervisor/misc/filter.py
  supervisor/resolution/fixups/store_execute_remove.py
  supervisor/store/__init__.py
  supervisor/store/const.py
  supervisor/store/git.py
  supervisor/store/repository.py
  supervisor/store/validate.py
  supervisor/validate.py
  tests/api/test_store.py
  tests/api/test_supervisor.py
  tests/conftest.py
  tests/fixtures/addons/git/5c53de3b/repository.yaml
  tests/fixtures/addons/git/a0d7b954/repository.yaml
  tests/resolution/fixup/test_store_execute_remove.py
  tests/store/test_custom_repository.py
  tests/store/test_store_manager.py
  tests/store/test_validate.py
Labels: cla-signed, new-feature

#3670 Use source instead of URL for repos
  supervisor/store/__init__.py
  tests/api/test_store.py
  tests/api/test_supervisor.py
  tests/store/test_custom_repository.py
Labels: cla-signed, bugfix

#3671 Don't add dupe repos to data on startup
  supervisor/store/__init__.py
Labels: cla-signed, bugfix

#3672 Move addon repo migration to bootstrap
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/store/__init__.py
  tests/conftest.py
  tests/store/test_store_manager.py
Labels: cla-signed, refactor

#3678 Extended store addon info
  supervisor/api/store.py
  tests/conftest.py
Labels: cla-signed, new-feature

#3676 Never disable interfaces at startup
  supervisor/host/network.py
  tests/host/test_network.py
Labels: cla-signed, bugfix

#3688 Verify the cgroup supported level
  supervisor/docker/__init__.py
  supervisor/resolution/evaluations/docker_configuration.py
  tests/resolution/evaluation/test_evaluate_docker_configuration.py
Labels: cla-signed, refactor

#3690 Add chidlren to the HW output
  supervisor/api/const.py
  supervisor/api/hardware.py
  supervisor/hardware/const.py
Labels: cla-signed, refactor

#3694 Add back missing state to addons list API
  supervisor/api/addons.py
Labels: cla-signed, bugfix

#3695 Remove installed key from store list API
  supervisor/api/addons.py
Labels: cla-signed, refactor

#3700 Use checkonline instead of version for online check
  supervisor/supervisor.py
Labels: cla-signed, refactor

#3701 AddonStore is_installed needs to check installed
  supervisor/store/addon.py
Labels: cla-signed, bugfix

#3710 Fix wheels build by pinning wheels action
  .github/workflows/builder.yml
Labels: cla-signed, ci
