Repository home-assistant/supervisor, pull requests merged in 2022-04, with the labels that each got.

#3551 Drop unnecessary command from CLI plug-in
  supervisor/docker/cli.py
Labels: cla-signed, performance

#3468 Handle TarError/OSError in backup routine
  supervisor/backups/backup.py
  supervisor/exceptions.py
  supervisor/homeassistant/module.py
Labels: bug, cla-signed

#3545 Add MDNS and LLMNR status to API
  supervisor/api/const.py
  supervisor/api/dns.py
  supervisor/api/host.py
  supervisor/host/const.py
  supervisor/host/info.py
  supervisor/host/manager.py
  supervisor/plugins/dns.py
  tests/api/test_dns.py
  tests/api/test_host.py
Labels: cla-signed, missing-documentation, new-feature

#3560 Update resolved information with host info
  supervisor/host/info.py
  tests/conftest.py
  tests/host/test_manager.py
Labels: bug, cla-signed

#3570 Merge updates with existing network settings
  supervisor/dbus/network/setting/__init__.py
  supervisor/utils/dbus.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/fixtures/org_freedesktop_NetworkManager_Settings_1-GetSettings.json
Labels: cla-signed, bugfix

#3578 Create issue for detected DNS server problem
  requirements.txt
  supervisor/resolution/checks/base.py
  supervisor/resolution/checks/dns_server_failure.py
  supervisor/resolution/checks/dns_server_ipv6_error.py
  supervisor/resolution/const.py
  tests/plugins/test_dns.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_dns_server_failure.py
  tests/resolution/check/test_check_dns_server_ipv6_error.py
Labels: cla-signed, new-feature

#3586 Add API option to disable fallback DNS
  supervisor/api/const.py
  supervisor/api/dns.py
  supervisor/misc/filter.py
  supervisor/plugins/const.py
  supervisor/plugins/dns.py
  supervisor/plugins/validate.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/dns_server.py
  tests/api/test_dns.py
  tests/plugins/test_dns.py
  tests/resolution/evaluation/test_evaluate_dns_server.py
Labels: cla-signed, new-feature

#3595 Enable CAS
  supervisor/resolution/checks/core_trust.py
  supervisor/resolution/checks/plugin_trust.py
  supervisor/security.py
  tests/test_security.py
Labels: cla-signed, refactor

#3600 Tuning Jemalloc
  rootfs/etc/services.d/supervisor/run
Labels: cla-signed, refactor

#3608 Add integrity check
  setup.py
  supervisor/addons/addon.py
  supervisor/api/__init__.py
  supervisor/api/security.py
  supervisor/bootstrap.py
  supervisor/coresys.py
  supervisor/exceptions.py
  supervisor/resolution/checks/core_trust.py
  supervisor/resolution/checks/plugin_trust.py
  supervisor/security.py
  supervisor/security/__init__.py
  supervisor/security/const.py
  supervisor/security/module.py
  supervisor/updater.py
  tests/api/test_security.py
  tests/resolution/check/test_check_core_trust.py
  tests/resolution/check/test_check_plugin_trust.py
  tests/security/__init__.py
  tests/security/test_module.py
  tests/test_security.py
Labels: cla-signed, refactor
