Repository home-assistant/supervisor, pull requests merged in 2023-07, with the labels that each got.

#4425 Separate startup event from update check event
  supervisor/const.py
  supervisor/core.py
  supervisor/homeassistant/module.py
  supervisor/homeassistant/websocket.py
  tests/homeassistant/test_module.py
  tests/homeassistant/test_websocket.py
Labels: cla-signed, bugfix

#4416 Identify network interfaces by mac over name
  supervisor/api/network.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/exceptions.py
  supervisor/host/configuration.py
  supervisor/host/network.py
  supervisor/resolution/checks/network_interface_ipv4.py
  tests/api/test_network.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_connection.py
  tests/dbus/network/test_interface.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_wireless.py
  tests/host/test_network.py
Labels: cla-signed, new-feature

#4438 Reduce executor code for docker
  supervisor/addons/__init__.py
  supervisor/backups/backup.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  supervisor/docker/multicast.py
  supervisor/docker/network.py
  supervisor/docker/observer.py
  supervisor/docker/supervisor.py
  supervisor/homeassistant/core.py
  supervisor/host/sound.py
  supervisor/plugins/dns.py
  supervisor/resolution/evaluations/container.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/api/test_addons.py
  tests/api/test_homeassistant.py
  tests/api/test_store.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/dbus/network/test_network_manager.py
  tests/docker/test_interface.py
  tests/homeassistant/test_core.py
  tests/homeassistant/test_home_assistant_watchdog.py
  tests/plugins/test_dns.py
  tests/plugins/test_plugin_base.py
  tests/resolution/check/test_check_docker_config.py
  tests/resolution/evaluation/test_evaluate_container.py
Labels: cla-signed, refactor

#4443 Increase core websocket proxy maximum message size to 64MiB
  supervisor/api/proxy.py
Labels: cla-signed, bugfix

#4446 Avoid check_api_state in websocket _can_send if we are already connected
  supervisor/homeassistant/websocket.py
Labels: cla-signed, performance

#4445 Switch to using the get core state api call to check if the API is up
  supervisor/homeassistant/api.py
Labels: cla-signed, performance

#4449 Allow discovery messages for unknown services with a warning
  supervisor/addons/validate.py
  supervisor/api/discovery.py
  supervisor/discovery/validate.py
  supervisor/utils/sentry.py
  tests/addons/test_config.py
  tests/api/test_discovery.py
  tests/conftest.py
Labels: cla-signed, refactor

#4452 Temporary operations for backups take place in destination folder
  supervisor/backups/backup.py
  tests/backups/test_backup.py
Labels: cla-signed, new-feature

#4451 List discovery only includes healthy addons
  supervisor/api/discovery.py
  tests/api/test_discovery.py
  tests/fixtures/discovery.json
Labels: cla-signed, bugfix

#4463 Missing an await on dns.write_hosts call
  supervisor/addons/__init__.py
Labels: cla-signed, bugfix
