Repository home-assistant/supervisor, pull requests merged in 2023-06, with the labels that each got.

#4333 Fix asyncio.wait in supervisor.reload
  supervisor/api/supervisor.py
  tests/api/test_supervisor.py
  tests/homeassistant/test_module.py
Labels: cla-signed, bugfix

#4338 Exit reload early if no mounts
  supervisor/mounts/manager.py
Labels: cla-signed, bugfix

#4342 Set CRYPTOGRAPHY_OPENSSL_NO_LEGACY for OpenSSL3
  Dockerfile
Labels: cla-signed, bugfix

#4377 Support Debian Bookworm
  supervisor/resolution/evaluations/operating_system.py
Labels: cla-signed, new-feature

#4374 Fix propagation mode of mounts to allow Ha-Core to start
  supervisor/docker/addon.py
  supervisor/docker/homeassistant.py
  supervisor/resolution/checks/docker_config.py
  tests/docker/test_addon.py
Labels: cla-signed, bugfix

#4376 Addon startup waits for healthy
  supervisor/addons/__init__.py
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/api/addons.py
  supervisor/api/store.py
  supervisor/api/supervisor.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/const.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  supervisor/misc/tasks.py
  supervisor/resolution/fixups/addon_execute_rebuild.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/api/test_addons.py
  tests/api/test_store.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/docker/test_addon.py
  tests/fixtures/backup_local_ssh_running.tar.gz
  tests/fixtures/backup_local_ssh_stopped.tar.gz
  tests/resolution/fixup/test_addon_execute_rebuild.py
Labels: cla-signed, new-feature

#4395 Allow specifying CIFS version
  supervisor/mounts/const.py
  supervisor/mounts/mount.py
  supervisor/mounts/validate.py
  tests/api/test_mounts.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
Labels: cla-signed, new-feature

#4398 Use noserverino option in cifs mounts
  supervisor/mounts/mount.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
Labels: cla-signed, bugfix

#4399 Allow all characters in mount credentials
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/mounts/mount.py
  supervisor/mounts/validate.py
  tests/conftest.py
  tests/mounts/test_mount.py
Labels: cla-signed, refactor

#4406 Fix Tag
  .github/workflows/builder.yml
Labels: cla-signed, ci

#4408 Add support for apparmor channels
  supervisor/const.py
  supervisor/supervisor.py
  tests/test_supervisor.py
Labels: cla-signed, new-feature

#4409 Ensure addon.start always returns coroutine
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix
