Repository home-assistant/supervisor, pull requests merged in 2023-05, with the labels that each got.

#4269 Add support for network mounts
  .vscode/launch.json
  supervisor/api/__init__.py
  supervisor/api/const.py
  supervisor/api/mounts.py
  supervisor/backups/backup.py
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/data/syslog-identifiers.json
  supervisor/dbus/const.py
  supervisor/dbus/systemd.py
  supervisor/dbus/udisks2/partition.py
  supervisor/exceptions.py
  supervisor/mounts/__init__.py
  supervisor/mounts/const.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/mounts/validate.py
  supervisor/resolution/const.py
  supervisor/resolution/fixups/base.py
  supervisor/resolution/fixups/mount_execute_reload.py
  supervisor/resolution/fixups/mount_execute_remove.py
  supervisor/resolution/module.py
  supervisor/utils/dbus.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/dbus/test_systemd.py
  tests/dbus_service_mocks/systemd.py
  tests/dbus_service_mocks/systemd_unit.py
  tests/mounts/__init__.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
  tests/mounts/test_validate.py
  tests/resolution/fixup/test_mount_execute_reload.py
  tests/resolution/fixup/test_mount_execute_remove.py
  tests/resolution/test_resolution_manager.py
Labels: cla-signed, new-feature

#4274 Fix bind mounting and remove on create failure
  supervisor/exceptions.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
Labels: cla-signed, bugfix

#4289 Use backup mounts
  supervisor/api/__init__.py
  supervisor/api/backups.py
  supervisor/api/mounts.py
  supervisor/backups/manager.py
  supervisor/misc/tasks.py
  supervisor/mounts/const.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/resolution/module.py
  supervisor/utils/sentinel.py
  tests/api/test_backups.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
Labels: cla-signed, new-feature

#4302 Fix devcontainer workspace and use env
  .devcontainer/devcontainer.json
Labels: cla-signed, bugfix

#4259 Add support for CAP_BPF and CAP_PERFMON privileges
  supervisor/addons/utils.py
  supervisor/docker/const.py
Labels: cla-signed, new-feature

#4296 Update to python 3.11
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  build.yaml
  requirements.txt
  supervisor/addons/__init__.py
  supervisor/api/ingress.py
  supervisor/backups/manager.py
  supervisor/core.py
  supervisor/homeassistant/module.py
  supervisor/mounts/manager.py
  supervisor/plugins/manager.py
  supervisor/store/__init__.py
  supervisor/updater.py
  supervisor/utils/codenotary.py
  tests/addons/test_manager.py
  tests/homeassistant/test_module.py
  tests/plugins/test_plugin_manager.py
  tests/store/test_store_manager.py
Labels: cla-signed, dependencies

#4312 Add missing default_backup_mount to mount config
  supervisor/mounts/validate.py
Labels: cla-signed, bugfix

#4318 Support share mounts
  supervisor/mounts/const.py
  supervisor/mounts/manager.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/mounts/test_manager.py
Labels: cla-signed, new-feature

#4321 Adjust regex to allow woff2 files to be served
  supervisor/api/middleware/security.py
Labels: enhancement, cla-signed

#4317 Make issue for problem with config for containers
  supervisor/docker/interface.py
  supervisor/docker/supervisor.py
  supervisor/host/manager.py
  supervisor/resolution/checks/docker_config.py
  supervisor/resolution/const.py
  supervisor/resolution/fixups/addon_execute_rebuild.py
  supervisor/resolution/fixups/core_execute_rebuild.py
  supervisor/resolution/fixups/plugin_execute_rebuild.py
  supervisor/resolution/fixups/system_execute_rebuild.py
  tests/api/test_backups.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/mounts/test_manager.py
  tests/resolution/check/test_check_docker_config.py
  tests/resolution/fixup/test_addon_execute_rebuild.py
  tests/resolution/fixup/test_core_execute_rebuild.py
  tests/resolution/fixup/test_mount_execute_reload.py
  tests/resolution/fixup/test_mount_execute_remove.py
  tests/resolution/fixup/test_plugin_execute_rebuild.py
  tests/resolution/fixup/test_system_execute_rebuild.py
Labels: cla-signed, new-feature

#4322 Add share to docker config issue
  supervisor/docker/addon.py
  supervisor/docker/homeassistant.py
  supervisor/resolution/checks/docker_config.py
  tests/docker/test_addon.py
  tests/fixtures/basic-addon-config.json
  tests/resolution/check/test_check_docker_config.py
Labels: cla-signed, bugfix

#4323 Improve handling of NFS mounts and backup manager errors
  supervisor/backups/manager.py
  supervisor/mounts/mount.py
  tests/backups/test_manager.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
Labels: cla-signed, bugfix

#4326 Null check for meta in meta_mounts
  supervisor/docker/interface.py
Labels: cla-signed, bugfix

#4327 Protect backup manager from setup failures for mount down
  supervisor/backups/manager.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix
