Repository home-assistant/supervisor, pull requests merged in 2023-02, with the labels that each got.

#3596 Add host UTS namespace support for Add-Ons
  supervisor/addons/model.py
  supervisor/addons/utils.py
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/manager.py
  tests/addons/test_config.py
Labels: stale, cla-signed, new-feature

#4145 Fix udisks2 standard options constant
  supervisor/dbus/udisks2/const.py
Labels: cla-signed, bugfix

#4144 Fix CI Supervisor version for tests
  supervisor/const.py
  tests/api/test_root.py
  tests/backups/conftest.py
  tests/test_coresys.py
Labels: cla-signed, ci

#4127 Handle OSError / Filesystem corruptions
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/source_mods.py
  supervisor/utils/codenotary.py
  tests/resolution/test_evaluation.py
Labels: cla-signed, refactor
