Repository home-assistant/supervisor, pull requests merged in 2023-08, with the labels that each got.

#4466 Revert "Bump aiohttp from 3.8.4 to 3.8.5 (#4448)"
  requirements.txt
Labels: cla-signed, bugfix

#4475 Cancel startup wait task on addon uninstallation
  supervisor/addons/addon.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/api/test_addons.py
  tests/api/test_store.py
Labels: cla-signed, bugfix

#4476 Use udev path instead of mac or name for nm match
  supervisor/api/network.py
  supervisor/dbus/const.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/host/configuration.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
  tests/dbus_service_mocks/network_connection_settings.py
  tests/host/test_network.py
Labels: cla-signed, bugfix

#4479 Fallback on interface name if path is missing
  supervisor/dbus/network/setting/generate.py
  tests/dbus/network/setting/test_generate.py
Labels: cla-signed, bugfix

#4457 Add job group execution limit option
  supervisor/addons/addon.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/docker/supervisor.py
  supervisor/exceptions.py
  supervisor/homeassistant/core.py
  supervisor/jobs/__init__.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/jobs/job_group.py
  tests/addons/test_manager.py
  tests/api/test_store.py
  tests/conftest.py
  tests/docker/test_addon.py
  tests/homeassistant/test_core.py
  tests/jobs/test_job_decorator.py
  tests/jobs/test_job_manager.py
  tests/plugins/test_audio.py
  tests/plugins/test_dns.py
Labels: cla-signed, new-feature

#4486 Add Home Assistant Green
  supervisor/addons/validate.py
  supervisor/data/arch.json
  tests/test_arch.py
Labels: cla-signed, new-feature

#4480 Extend container image name validator
  supervisor/validate.py
  tests/addons/test_config.py
  tests/test_validate.py
Labels: cla-signed, bugfix

#4481 Address addon storage race condition
  supervisor/store/data.py
  tests/addons/test_manager.py
  tests/store/test_reading_addons.py
  tests/store/test_translation_load.py
Labels: cla-signed, bugfix

#4487 Missing an await in addon data
  supervisor/store/data.py
Labels: cla-signed, bugfix

#4492 Always stop the addon before restoring it
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#4495 Add job names and references everywhere
  supervisor/addons/__init__.py
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/backups/manager.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/docker/supervisor.py
  supervisor/homeassistant/api.py
  supervisor/homeassistant/core.py
  supervisor/homeassistant/module.py
  supervisor/homeassistant/secrets.py
  supervisor/host/network.py
  supervisor/host/sound.py
  supervisor/jobs/__init__.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/jobs/job_group.py
  supervisor/misc/tasks.py
  supervisor/mounts/manager.py
  supervisor/os/data_disk.py
  supervisor/os/manager.py
  supervisor/plugins/audio.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  supervisor/resolution/checks/addon_pwned.py
  supervisor/resolution/checks/dns_server.py
  supervisor/resolution/checks/dns_server_ipv6.py
  supervisor/resolution/fixup.py
  supervisor/resolution/fixups/store_execute_reload.py
  supervisor/resolution/fixups/store_execute_reset.py
  supervisor/resolution/fixups/system_execute_integrity.py
  supervisor/security/module.py
  supervisor/store/__init__.py
  supervisor/store/git.py
  supervisor/supervisor.py
  supervisor/updater.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, new-feature

#4152 Allows the supervisor to send a session's user to addon with header X-Remote-User
  supervisor/api/ingress.py
  supervisor/const.py
  supervisor/homeassistant/module.py
  supervisor/ingress.py
  supervisor/validate.py
  tests/api/test_ingress.py
  tests/test_ingress.py
Labels: cla-signed, new-feature

#4502 Use dataclasses asdict for dataclasses
  supervisor/api/audio.py
Labels: cla-signed, bugfix

#4504 Remove old add-on state refresh
  supervisor/misc/tasks.py
Labels: cla-signed, refactor

#4506 Don't notify listeners on CoreState.CLOSE
  supervisor/core.py
Labels: cla-signed, bugfix

#4514 List current job tree in api
  supervisor/api/const.py
  supervisor/api/jobs.py
  tests/api/test_jobs.py
Labels: cla-signed, new-feature
