Repository home-assistant/supervisor, pull requests merged in 2023-01, with the labels that each got.

#4084 Add support for ESPHome dashboard discovery
  supervisor/discovery/services/esphome.py
  tests/discovery/test_esphome.py
Labels: cla-signed, new-feature

#4098 Clarify message when addon unavailable
  supervisor/addons/__init__.py
  supervisor/addons/model.py
  tests/common.py
  tests/store/test_store_manager.py
Labels: cla-signed, refactor

#4095 sys_capture_exception to capture_exception
  supervisor/addons/addon.py
Labels: cla-signed, bugfix

#4107 Allow all job conditions to be ignored
  supervisor/jobs/decorator.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, bugfix

#4078 Fix AppArmor name-related exceptions
  supervisor/utils/apparmor.py
Labels: cla-signed, bugfix

#4109 AppArmor tests and fix profile name in flag
  supervisor/utils/apparmor.py
  tests/common.py
  tests/fixtures/apparmor_multiple_profiles.txt
  tests/fixtures/apparmor_no_profile.txt
  tests/fixtures/apparmor_valid.txt
  tests/fixtures/apparmor_valid_mediate.txt
  tests/utils/test_apparmor.py
Labels: cla-signed, test

#4110 Handle UnicodeDecodeError
  supervisor/store/git.py
  supervisor/utils/codenotary.py
  tests/store/test_repository_git.py
  tests/utils/test_codenotary.py
Labels: cla-signed, bugfix

#4115 Don't log error for addon unavailable
  supervisor/addons/model.py
  tests/api/test_store.py
Labels: bugfix
