Repository home-assistant/supervisor, pull requests merged in 2023-10, with the labels that each got.

#4574 Remove all PyPi classifiers as this package is not published to PyPi
  setup.py
Labels: cla-signed, dependencies

#4602 JobGroups check active job to determine if in progress
  supervisor/docker/interface.py
  supervisor/homeassistant/core.py
Labels: cla-signed, Hacktoberfest, bugfix

#4595 Core API check during startup can timeout
  supervisor/exceptions.py
  supervisor/homeassistant/core.py
  tests/homeassistant/test_core.py
Labels: cla-signed, Hacktoberfest, bugfix

#4604 Unstarted jobs should always be cleaned up
  supervisor/jobs/__init__.py
  supervisor/jobs/decorator.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, Hacktoberfest, bugfix

#4591 Allow home assistant backups to exclude database
  supervisor/api/backups.py
  supervisor/api/homeassistant.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
  supervisor/const.py
  supervisor/homeassistant/module.py
  supervisor/homeassistant/validate.py
  supervisor/utils/__init__.py
  tests/api/test_backups.py
  tests/api/test_homeassistant.py
  tests/backups/test_manager.py
Labels: cla-signed, new-feature

#4620 Call save data after removing mount in fixup
  supervisor/resolution/fixups/mount_execute_remove.py
  tests/resolution/fixup/test_mount_execute_remove.py
Labels: cla-signed, Hacktoberfest, bugfix

#4619 Eliminate possible addon data race condition during update
  supervisor/addons/__init__.py
  supervisor/docker/interface.py
  supervisor/store/addon.py
  tests/addons/test_manager.py
Labels: cla-signed, Hacktoberfest, bugfix

#4605 Support proxy of binary messages from addons to HA
  supervisor/api/proxy.py
  tests/api/test_proxy.py
  tests/fixtures/addons/local/ssh/config.yaml
Labels: cla-signed, Hacktoberfest, new-feature

#4626 Fixing multiple typos
  supervisor/addons/addon.py
  supervisor/core.py
  supervisor/jobs/decorator.py
Labels: cla-signed, Hacktoberfest

#4628 Handle get users API returning None
  supervisor/homeassistant/module.py
  tests/homeassistant/test_module.py
Labels: cla-signed, Hacktoberfest, bugfix

#4621 Capture exception if image is missing on run
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/cli.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/resolution/fixups/addon_execute_repair.py
  tests/docker/test_addon.py
  tests/docker/test_interface.py
  tests/resolution/fixup/test_addon_execute_repair.py
Labels: cla-signed, Hacktoberfest, refactor

#4633 Use UUID for setting parent interface in vlans
  supervisor/dbus/network/setting/generate.py
  supervisor/host/network.py
  tests/api/test_network.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
Labels: cla-signed, Hacktoberfest

#4639 Update base images to 3.11-alpine3.18
  .hadolint.yaml
  Dockerfile
  build.yaml
Labels: cla-signed, Hacktoberfest

#4632 Don't warn for removing unstarted jobs
  supervisor/jobs/__init__.py
  tests/jobs/test_job_manager.py
Labels: cla-signed, Hacktoberfest, bugfix

#4635 Remove race with watchdog during backup, restore and update
  supervisor/addons/__init__.py
  supervisor/addons/addon.py
  supervisor/docker/addon.py
  supervisor/plugins/base.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/plugins/test_plugin_base.py
Labels: cla-signed, Hacktoberfest, bugfix

#4646 Revert "Update base images to 3.11-alpine3.18 (#4639)"
  .hadolint.yaml
  Dockerfile
  build.yaml
Labels: cla-signed, Hacktoberfest

#4638 Reload Pulseaudio modules on hardware change
  supervisor/host/manager.py
  supervisor/host/sound.py
Labels: cla-signed, Hacktoberfest, bugfix

#4651 Catch unicode decode errors
  supervisor/utils/yaml.py
Labels: cla-signed, Hacktoberfest

#4653 Remove folder only deletes from current filesystem
  Dockerfile
  supervisor/utils/__init__.py
Labels: cla-signed, Hacktoberfest

#4650 Add a public config folder per addon
  supervisor/addons/__init__.py
  supervisor/addons/addon.py
  supervisor/addons/validate.py
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/const.py
  supervisor/docker/addon.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/docker/test_addon.py
  tests/fixtures/addon-config-map-addon_config.json
  tests/fixtures/addons/local/example/config.yaml
Labels: cla-signed, missing-documentation, new-feature

#4654 Don't remove folder itself on restore
  supervisor/homeassistant/module.py
Labels: cla-signed, Hacktoberfest, bugfix
