Repository home-assistant/supervisor, pull requests merged in 2023-09, with the labels that each got.

#4515 Skip plugin update on startup if supervisor out of date
  supervisor/core.py
  supervisor/plugins/manager.py
  tests/plugins/test_plugin_manager.py
Labels: cla-signed, refactor

#4519 Update store data in one task to prevent races
  supervisor/store/data.py
Labels: cla-signed, bugfix

#4518 Skip unnecessary mounts and privileges for landingpage
  supervisor/docker/homeassistant.py
  tests/docker/test_homeassistant.py
Labels: cla-signed, refactor

#4520 Add jobs to docker supervisor and use group wait
  supervisor/docker/interface.py
  supervisor/docker/supervisor.py
Labels: cla-signed, refactor

#4521 Use newer StrEnum and IntEnum over Enum
  supervisor/addons/addon.py
  supervisor/addons/const.py
  supervisor/addons/validate.py
  supervisor/api/middleware/security.py
  supervisor/config.py
  supervisor/const.py
  supervisor/core.py
  supervisor/dbus/const.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/setting/generate.py
  supervisor/dbus/rauc.py
  supervisor/dbus/systemd.py
  supervisor/dbus/udisks2/block.py
  supervisor/dbus/udisks2/const.py
  supervisor/dbus/udisks2/data.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/const.py
  supervisor/docker/dns.py
  supervisor/docker/homeassistant.py
  supervisor/docker/multicast.py
  supervisor/docker/observer.py
  supervisor/docker/supervisor.py
  supervisor/hardware/const.py
  supervisor/hardware/manager.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/core.py
  supervisor/host/const.py
  supervisor/host/logs.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/mounts/const.py
  supervisor/mounts/mount.py
  supervisor/mounts/validate.py
  supervisor/plugins/base.py
  supervisor/resolution/checks/core_security.py
  supervisor/resolution/checks/docker_config.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/base.py
  supervisor/security/const.py
  supervisor/store/const.py
  supervisor/store/validate.py
  supervisor/supervisor.py
  supervisor/updater.py
  tests/addons/test_config.py
  tests/test_core.py
  tests/test_supervisor.py
Labels: cla-signed, refactor

#4545 Mount names cannot include non-alphanumerics
  supervisor/mounts/validate.py
  tests/api/test_mounts.py
Labels: cla-signed, bugfix

#4538 Add freeze/thaw apis for external snapshots
  supervisor/addons/addon.py
  supervisor/api/__init__.py
  supervisor/api/backups.py
  supervisor/backups/const.py
  supervisor/backups/manager.py
  supervisor/coresys.py
  supervisor/exceptions.py
  supervisor/homeassistant/module.py
  supervisor/jobs/__init__.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  tests/api/test_backups.py
  tests/backups/test_manager.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, API, new-feature

#4551 Ingress does not break when username missing
  supervisor/api/ingress.py
  supervisor/const.py
  supervisor/homeassistant/module.py
Labels: cla-signed, bugfix

#4557 Unmount mounts before backup restore
  supervisor/backups/backup.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix

#4552 Only tell HA to refresh ingress on restore on change
  supervisor/addons/__init__.py
  tests/addons/test_addon.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix

#4555 Switch from ruamel.yaml to pyyaml
  .github/workflows/builder.yml
  Dockerfile
  requirements.txt
  supervisor/utils/yaml.py
Labels: cla-signed, refactor

#4556 Add support for green LEDs to API
  supervisor/api/__init__.py
  supervisor/api/const.py
  supervisor/api/os.py
  supervisor/const.py
  supervisor/dbus/agent/boards/__init__.py
  supervisor/dbus/agent/boards/const.py
  supervisor/dbus/agent/boards/green.py
  supervisor/dbus/agent/boards/interface.py
  supervisor/dbus/agent/boards/validate.py
  supervisor/dbus/agent/boards/yellow.py
  supervisor/dbus/const.py
  tests/api/test_os.py
  tests/dbus/agent/boards/test_board.py
  tests/dbus/agent/boards/test_green.py
  tests/dbus/agent/boards/test_yellow.py
  tests/dbus_service_mocks/agent_boards_green.py
Labels: cla-signed, new-feature

#4563 Network backups skip free space check
  supervisor/backups/manager.py
  supervisor/jobs/decorator.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix

#4546 Fix typos in docstrings
  supervisor/backups/backup.py
  supervisor/coresys.py
Labels: cla-signed, chore

#4586 Change User LED to System Health LED
  supervisor/api/const.py
  supervisor/api/os.py
  tests/api/test_os.py
Labels: cla-signed, refactor

#4588 Skip watchdog API test on landingpage
  supervisor/misc/tasks.py
Labels: cla-signed, bugfix

#4589 Correct /store/addons api output
  supervisor/api/store.py
  tests/api/test_store.py
Labels: cla-signed, breaking-change, bugfix
