Repository home-assistant/supervisor, pull requests merged in 2023-03, with the labels that each got.

#4165 Backport core api filter
  requirements_tests.txt
  supervisor/api/__init__.py
  supervisor/api/middleware/security.py
  tests/api/middleware/test_security.py
Labels: cla-signed, refactor

#4174 Test discovery message deleted on uninstall
  tests/addons/test_manager.py
  tests/conftest.py
Labels: cla-signed, ci

#4160 Mock services on session dbus in tests
  .github/workflows/ci.yaml
  setup.cfg
  supervisor/resolution/validate.py
  tests/common.py
  tests/conftest.py
  tests/dbus/test_hostname.py
  tests/dbus/test_login.py
  tests/dbus/test_rauc.py
  tests/dbus/test_resolved.py
  tests/dbus/test_systemd.py
  tests/dbus/test_timedate.py
  tests/dbus_service_mocks/__init__.py
  tests/dbus_service_mocks/base.py
  tests/dbus_service_mocks/hostname.py
  tests/dbus_service_mocks/logind.py
  tests/dbus_service_mocks/rauc.py
  tests/dbus_service_mocks/resolved.py
  tests/dbus_service_mocks/systemd.py
  tests/dbus_service_mocks/timedate.py
Labels: cla-signed, ci

#4177 Add ODROID-M1
  supervisor/addons/validate.py
  supervisor/data/arch.json
  tests/test_arch.py
Labels: cla-signed, new-feature

#4180 Use session dbus for os agent tests
  tests/dbus/agent/boards/test_board.py
  tests/dbus/agent/boards/test_yellow.py
  tests/dbus/agent/conftest.py
  tests/dbus/agent/test_agent.py
  tests/dbus/agent/test_apparmor.py
  tests/dbus/agent/test_cgroup.py
  tests/dbus/agent/test_datadisk.py
  tests/dbus/agent/test_system.py
  tests/dbus_service_mocks/apparmor.py
  tests/dbus_service_mocks/boards.py
  tests/dbus_service_mocks/boards_supervised.py
  tests/dbus_service_mocks/boards_yellow.py
  tests/dbus_service_mocks/cgroup.py
  tests/dbus_service_mocks/datadisk.py
  tests/dbus_service_mocks/os_agent.py
  tests/dbus_service_mocks/system.py
Labels: cla-signed, ci

#4188 Improve addon slug validation
  supervisor/addons/const.py
  supervisor/addons/validate.py
  supervisor/api/middleware/security.py
  tests/addons/test_config.py
Labels: cla-signed, bugfix

#4191 Use session dbus for network tests
  supervisor/dbus/const.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/wireless.py
  tests/conftest.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_accesspoint.py
  tests/dbus/network/test_connection.py
  tests/dbus/network/test_dns.py
  tests/dbus/network/test_interface.py
  tests/dbus/network/test_ip_configuration.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_setting.py
  tests/dbus/network/test_settings.py
  tests/dbus/network/test_wireless.py
  tests/dbus_service_mocks/hostname.py
  tests/dbus_service_mocks/network_access_point.py
  tests/dbus_service_mocks/network_active_connection.py
  tests/dbus_service_mocks/network_connection_settings.py
  tests/dbus_service_mocks/network_device.py
  tests/dbus_service_mocks/network_device_wireless.py
  tests/dbus_service_mocks/network_dns_manager.py
  tests/dbus_service_mocks/network_ip4config.py
  tests/dbus_service_mocks/network_ip6config.py
  tests/dbus_service_mocks/network_manager.py
  tests/dbus_service_mocks/network_settings.py
  tests/dbus_service_mocks/resolved.py
Labels: cla-signed, ci

#4194 Use session dbus for udisks2 tests
  tests/common.py
  tests/conftest.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_connection.py
  tests/dbus/network/test_interface.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_wireless.py
  tests/dbus/udisks2/test_block.py
  tests/dbus/udisks2/test_drive.py
  tests/dbus/udisks2/test_filesystem.py
  tests/dbus/udisks2/test_manager.py
  tests/dbus/udisks2/test_partition_table.py
  tests/dbus_service_mocks/udisks2_block.py
  tests/dbus_service_mocks/udisks2_drive.py
  tests/dbus_service_mocks/udisks2_filesystem.py
  tests/dbus_service_mocks/udisks2_loop.py
  tests/dbus_service_mocks/udisks2_manager.py
  tests/dbus_service_mocks/udisks2_partition.py
  tests/dbus_service_mocks/udisks2_partition_table.py
Labels: cla-signed, ci

#4212 Format data disk in Supervisor instead of OS Agent
  supervisor/dbus/agent/datadisk.py
  supervisor/dbus/interface.py
  supervisor/dbus/udisks2/__init__.py
  supervisor/dbus/udisks2/block.py
  supervisor/dbus/udisks2/data.py
  supervisor/dbus/udisks2/partition_table.py
  supervisor/os/data_disk.py
  supervisor/utils/dbus.py
  tests/conftest.py
  tests/dbus/agent/test_datadisk.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/test_interface.py
  tests/dbus/udisks2/test_block.py
  tests/dbus/udisks2/test_manager.py
  tests/dbus/udisks2/test_partition_table.py
  tests/dbus_service_mocks/agent_datadisk.py
  tests/dbus_service_mocks/udisks2_partition_table.py
  tests/os/test_data_disk.py
  tests/utils/test_dbus.py
Labels: cla-signed, new-feature

#4217 Disable codenotary until rework of cosign
  supervisor/utils/codenotary.py
  tests/utils/test_codenotary.py
Labels: cla-signed, refactor

#4221 Don't fail if data disk can't be detected
  supervisor/api/os.py
  supervisor/os/data_disk.py
Labels: cla-signed, bugfix

#4215 Strip null character off udisks2 paths
  supervisor/dbus/udisks2/block.py
  supervisor/dbus/udisks2/data.py
  supervisor/dbus/udisks2/filesystem.py
  tests/dbus_service_mocks/udisks2_block.py
  tests/dbus_service_mocks/udisks2_filesystem.py
Labels: cla-signed, bugfix

#4218 Create issue for multiple data disks detected
  supervisor/dbus/udisks2/__init__.py
  supervisor/dbus/udisks2/filesystem.py
  supervisor/os/const.py
  supervisor/os/data_disk.py
  supervisor/resolution/checks/multiple_data_disks.py
  supervisor/resolution/const.py
  supervisor/resolution/fixups/system_rename_data_disk.py
  tests/dbus/udisks2/test_block.py
  tests/dbus/udisks2/test_filesystem.py
  tests/dbus/udisks2/test_manager.py
  tests/dbus_service_mocks/udisks2_block.py
  tests/dbus_service_mocks/udisks2_manager.py
  tests/resolution/check/test_check_multiple_data_disks.py
  tests/resolution/fixup/test_system_rename_data_disk.py
Labels: cla-signed, new-feature
