Repository home-assistant/supervisor, pull requests merged in 2023-04, with the labels that each got.

#4222 Prevent multiple data disks with name hassos-data-external
  supervisor/dbus/const.py
  supervisor/dbus/udisks2/block.py
  supervisor/dbus/udisks2/data.py
  supervisor/dbus/udisks2/partition.py
  supervisor/dbus/udisks2/partition_table.py
  supervisor/os/const.py
  supervisor/os/data_disk.py
  tests/conftest.py
  tests/dbus/udisks2/test_block.py
  tests/dbus/udisks2/test_partition.py
  tests/os/test_data_disk.py
Labels: cla-signed, bugfix

#4225 Issue changed messages include suggestions
  supervisor/resolution/module.py
  tests/resolution/test_resolution_manager.py
Labels: cla-signed, new-feature

#4223 Support checkout directory which are not named supervisor
  .devcontainer/devcontainer.json
Labels: cla-signed, build

#4238 Remove codecov package
  requirements_tests.txt
Labels: cla-signed, bugfix

#4237 Add start transient unit dbus method
  supervisor/dbus/const.py
  supervisor/dbus/systemd.py
  supervisor/host/services.py
  tests/dbus/test_systemd.py
  tests/dbus_service_mocks/systemd.py
Labels: cla-signed, new-feature

#4242 Add support for NET_RAW privileges
  supervisor/addons/utils.py
  supervisor/docker/const.py
Labels: cla-signed, new-feature
