Repository home-assistant/supervisor, pull requests merged in 2023-12, with the labels that each got.

#4677 Make check_port an async function
  supervisor/addons/addon.py
  supervisor/homeassistant/api.py
  supervisor/ingress.py
  supervisor/utils/__init__.py
  tests/test_ingress.py
  tests/utils/test_check_port.py
Labels: cla-signed, refactor

#4744 Check/get ingress port on add-on load
  supervisor/addons/addon.py
  tests/addons/test_addon.py
  tests/fixtures/addons/local/example/config.yaml
Labels: cla-signed, bugfix

#4745 Address GitHub action deprecation warnings
  .github/workflows/builder.yml
  .github/workflows/release-drafter.yml
Labels: cla-signed, github_actions

#4746 Fix pre-commit GitHub Action cache
  .github/workflows/ci.yaml
Labels: cla-signed, github_actions

#4757 Add Raspberry Pi 5
  supervisor/addons/validate.py
  supervisor/data/arch.json
  tests/addons/test_config.py
  tests/test_arch.py
Labels: cla-signed, new-feature

#4760 Refactor addons init to addons manager
  supervisor/addons/__init__.py
  supervisor/addons/manager.py
  supervisor/api/addons.py
  supervisor/api/store.py
  supervisor/backups/backup.py
  supervisor/bootstrap.py
  supervisor/coresys.py
  tests/docker/test_interface.py
Labels: cla-signed, refactor

#4751 Fix fallback to non-SSL whoami call
  supervisor/core.py
  tests/test_core.py
Labels: cla-signed, bugfix

#4781 Fix WiFi WEP configuration
  supervisor/dbus/network/setting/generate.py
Labels: cla-signed, bugfix

#4783 Adjust "retry in ..." log messages to avoid confusion
  supervisor/homeassistant/core.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  tests/homeassistant/test_core.py
Labels: cla-signed, chore

#4784 Set max reanimation attempts on HA watchdog
  supervisor/misc/tasks.py
  tests/misc/test_tasks.py
Labels: cla-signed, new-feature

#4750 OSError Bad message error marks system as unhealthy
  supervisor/addons/addon.py
  supervisor/api/backups.py
  supervisor/backups/manager.py
  supervisor/homeassistant/module.py
  supervisor/host/apparmor.py
  supervisor/os/manager.py
  supervisor/plugins/audio.py
  supervisor/plugins/dns.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/source_mods.py
  supervisor/store/data.py
  supervisor/supervisor.py
  tests/addons/test_addon.py
  tests/backups/test_manager.py
  tests/hardware/test_helper.py
  tests/homeassistant/test_module.py
  tests/host/test_apparmor_control.py
  tests/plugins/test_audio.py
  tests/plugins/test_dns.py
  tests/resolution/evaluation/test_evaluate_apparmor.py
  tests/resolution/evaluation/test_evaluate_source_mods.py
  tests/store/test_reading_addons.py
  tests/test_core.py
  tests/test_supervisor.py
Labels: cla-signed, new-feature

#4786 Always pass explicit architecture of installed add-ons
  supervisor/addons/addon.py
  supervisor/docker/addon.py
  tests/addons/test_manager.py
Labels: cla-signed, bugfix

#4694 Add support for setting target path in map config
  supervisor/addons/addon.py
  supervisor/addons/configuration.py
  supervisor/addons/const.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/const.py
  supervisor/docker/addon.py
  tests/docker/test_addon.py
Labels: cla-signed, new-feature

#4791 Improve error handling in backup restore
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/exceptions.py
  supervisor/homeassistant/module.py
  tests/backups/conftest.py
  tests/backups/test_manager.py
Labels: cla-signed, refactor

#4770 Migrate to pyproject.toml where possible
  pylintrc
  pyproject.toml
  pytest.ini
  setup.cfg
  setup.py
  tests/resolution/evaluation/test_evaluate_operating_system.py
  tests/resolution/evaluation/test_evaluate_os_agent.py
  tests/resolution/evaluation/test_evaluate_systemd.py
Labels: cla-signed, refactor
