Repository home-assistant/supervisor, pull requests merged in 2023-11, with the labels that each got.

#4658 Use longer timeouts for API checks before trigger a rollback
  supervisor/homeassistant/api.py
  supervisor/homeassistant/core.py
  tests/conftest.py
  tests/homeassistant/test_core.py
Labels: cla-signed, Hacktoberfest, bugfix

#4659 Addon methods interfacing with docker are job groups
  supervisor/addons/__init__.py
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/api/addons.py
  supervisor/api/store.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/misc/tasks.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
Labels: cla-signed, refactor

#4657 Revert "Revert "Update base images to 3.11-alpine3.18 (#4639)" (#4646)"
  .hadolint.yaml
  Dockerfile
  build.yaml
Labels: cla-signed, Hacktoberfest

#4663 Fix Home Assistant Core API check
  supervisor/homeassistant/api.py
  tests/conftest.py
Labels: cla-signed, bugfix

#4665 Update devcontainer.json to use the new format
  .devcontainer/devcontainer.json
Labels: cla-signed, build

#4666 Bump tooling to target Python version 3.11
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  supervisor/addons/addon.py
  supervisor/api/proxy.py
  supervisor/backups/manager.py
  supervisor/core.py
  supervisor/dbus/udisks2/data.py
  supervisor/homeassistant/api.py
  supervisor/misc/scheduler.py
  supervisor/mounts/validate.py
  supervisor/os/manager.py
  supervisor/plugins/observer.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/utils/codenotary.py
  supervisor/utils/dbus.py
  supervisor/utils/pwned.py
  supervisor/utils/whoami.py
  tox.ini
Labels: cla-signed, build

#4672 Fix saving ingress data on supervisor shutdown
  supervisor/const.py
  supervisor/ingress.py
  supervisor/validate.py
  tests/test_ingress.py
Labels: cla-signed, bugfix

#4673 Cache common version checks
  supervisor/addons/model.py
  supervisor/api/middleware/security.py
  supervisor/homeassistant/api.py
  supervisor/utils/__init__.py
Labels: cla-signed, refactor

#4676 Add log entries of level INFO to Sentry breadcrumbs
  supervisor/utils/sentry.py
Labels: cla-signed, new-feature

#4685 Use content-type fast path for common case
  supervisor/api/ingress.py
Labels: cla-signed, performance

#4691 Warn users only when old config is actually used
  supervisor/addons/validate.py
Labels: cla-signed, bugfix

#4690 Create add-on config folder on add-on start
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#4674 Small speed up to arch is_supported
  supervisor/arch.py
  tests/addons/test_addon.py
  tests/conftest.py
  tests/test_arch.py
Labels: cla-signed, refactor

#4696 Don't remove add-on conifg on add-on removal
  supervisor/addons/addon.py
  tests/backups/test_manager.py
Labels: cla-signed, breaking-change

#4697 Revert Home Assistant configuration to `/config`
  supervisor/docker/addon.py
  tests/docker/test_addon.py
Labels: cla-signed, breaking-change

#4702 Revert "Revert Home Assistant configuration to `/config`"
  supervisor/docker/addon.py
  tests/docker/test_addon.py
Labels: cla-signed, breaking-change

#4698 Avoid empty newlines in Supervisor logs
  rootfs/etc/services.d/watchdog/run
Labels: cla-signed, bugfix

#4695 Address pytest warnings
  pytest.ini
  tests/api/middleware/test_security.py
  tests/api/test_addons.py
  tests/api/test_audio.py
  tests/api/test_dns.py
  tests/api/test_homeassistant.py
  tests/api/test_multicast.py
  tests/api/test_supervisor.py
  tests/dbus/test_interface.py
  tests/jobs/test_job_decorator.py
  tests/utils/test_dbus.py
Labels: cla-signed, refactor

#4710 Ensure empty body responses never generate an invalid chunked response
  supervisor/api/ingress.py
Labels: cla-signed, bugfix

#4705 Use aiohttp-fast-url-dispatcher to avoid linear searching to route urls
  requirements.txt
  supervisor/api/__init__.py
Labels: cla-signed, performance

#4714 Bump aiohttp to 3.9.0
  requirements.txt
  supervisor/api/__init__.py
Labels: cla-signed, dependencies

#4716 Move logging I/O to another thread to avoid blocking the event loop
  supervisor/__main__.py
  supervisor/utils/logging.py
  tests/utils/test_logging.py
Labels: cla-signed, bugfix

#4719 Fix ingress session cleanup
  supervisor/ingress.py
  tests/test_ingress.py
Labels: cla-signed, bugfix

#4722 Revert "Bump aiohttp to 3.9.0"
  requirements.txt
  supervisor/api/__init__.py
Labels: cla-signed, dependencies

#4729 Bump aiohttp to 3.9.1
  requirements.txt
  supervisor/api/__init__.py
Labels: cla-signed, dependencies

#4732 Use find to delete files recursively
  Dockerfile
  supervisor/utils/__init__.py
Labels: cla-signed, bugfix

#4720 Improve D-Bus error handling for NetworkManager
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/hostname.py
  supervisor/dbus/logind.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/dns.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/rauc.py
  supervisor/dbus/resolved.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/dbus/udisks2/__init__.py
  supervisor/exceptions.py
  supervisor/utils/dbus.py
  tests/dbus/agent/test_agent.py
  tests/dbus/network/test_dns.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_settings.py
  tests/dbus/test_hostname.py
  tests/dbus/test_login.py
  tests/dbus/test_rauc.py
  tests/dbus/test_resolved.py
  tests/dbus/test_timedate.py
  tests/utils/test_dbus.py
Labels: cla-signed, refactor

#4736 Bump core shutdown timeout for new pre-stopping core state
  supervisor/docker/homeassistant.py
  tests/homeassistant/test_core.py
Labels: cla-signed, refactor

#4733 Wait until mount unit is deactivated on unmount
  supervisor/mounts/mount.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/dbus_service_mocks/systemd.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
  tests/resolution/fixup/test_mount_execute_remove.py
Labels: cla-signed, bugfix
