Repository home-assistant/supervisor, pull requests merged in 2024-11, with the labels that each got.

#5391 Add fallback for boot IDs query
  supervisor/host/logs.py
  tests/api/test_host.py
  tests/conftest.py
  tests/host/test_logs.py
Labels: cla-signed, bugfix

#5397 Create addon boot failed issue for repair
  supervisor/addons/addon.py
  supervisor/addons/manager.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/resolution/const.py
  supervisor/resolution/fixups/addon_disable_boot.py
  supervisor/resolution/fixups/addon_execute_start.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/resolution/fixup/test_addon_disable_boot.py
  tests/resolution/fixup/test_addon_execute_repair.py
  tests/resolution/fixup/test_addon_execute_start.py
Labels: cla-signed, new-feature

#5414 Bump aiohttp to 3.10.11
  requirements.txt
Labels: cla-signed, dependencies

#5438 Add support for cloud backups in Core
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/backups.py
  supervisor/api/const.py
  supervisor/api/mounts.py
  supervisor/backups/backup.py
  supervisor/backups/const.py
  supervisor/backups/manager.py
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/const.py
  supervisor/docker/homeassistant.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/websocket.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/store/data.py
  tests/api/test_backups.py
  tests/api/test_mounts.py
  tests/backups/test_backup.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/docker/test_homeassistant.py
  tests/fixtures/backup_example.tar
  tests/resolution/fixup/test_mount_execute_remove.py
Labels: cla-signed, missing-documentation, new-feature, need-cli, need-client-library

#5446 Add null check on user path in mounts
  supervisor/api/mounts.py
Labels: bugfix

#5453 Fix flaky backup test
  tests/backups/test_manager.py
Labels: ci

#5452 Disable backup complete ws message
  supervisor/homeassistant/websocket.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix
