Repository home-assistant/supervisor, pull requests merged in 2024-05, with the labels that each got.

#5049 Skip udisks listener on failure to connect
  supervisor/dbus/udisks2/__init__.py
Labels: cla-signed, bugfix

#5064 Fix no changelog API response
  supervisor/api/__init__.py
  supervisor/api/store.py
  tests/api/test_store.py
Labels: cla-signed, bugfix

#5068 Revert "Bump orjson from 3.9.15 to 3.10.3 (#5057)"
  requirements.txt
Labels: cla-signed, dependencies

#5079 Don't process hardware events when landing page is running
  supervisor/homeassistant/module.py
Labels: cla-signed, bugfix

#5082 Fix doc and changelog API response for orphaned addons
  supervisor/api/store.py
  tests/api/test_store.py
Labels: cla-signed, bugfix

#5097 Pin Python requets package
  requirements.txt
Labels: cla-signed, bugfix

#5051 Max retries for auto applying addon image fixup
  supervisor/resolution/fixups/addon_execute_repair.py
  tests/resolution/fixup/test_addon_execute_repair.py
Labels: cla-signed, refactor

#5084 Create issue for detached addons
  supervisor/resolution/checks/detached_addon_missing.py
  supervisor/resolution/checks/detached_addon_removed.py
  supervisor/resolution/const.py
  tests/resolution/check/test_check_detached_addon_missing.py
  tests/resolution/check/test_check_detached_addon_removed.py
Labels: cla-signed, new-feature

#5088 Add Exception handling when processing udev devices
  supervisor/hardware/manager.py
Labels: cla-signed, bugfix
