Repository home-assistant/supervisor, pull requests merged in 2024-08, with the labels that each got.

#5224 Fix resp may be undefined end_backup issue
  supervisor/homeassistant/module.py
  tests/homeassistant/test_module.py
Labels: cla-signed, bugfix

#5227 Suppress SyntaxWarning from CPE until fixed
  supervisor/os/manager.py
Labels: cla-signed, bugfix

#5236 Bump aiohttp to 3.10.2, drop aiohttp-fast-url-dispatcher
  requirements.txt
  supervisor/api/__init__.py
Labels: cla-signed, dependencies

#5145 Allow core to mark addons as system managed
  supervisor/addons/addon.py
  supervisor/addons/validate.py
  supervisor/api/__init__.py
  supervisor/api/addons.py
  supervisor/api/middleware/security.py
  supervisor/const.py
  tests/api/middleware/test_security.py
  tests/api/test_addons.py
Labels: cla-signed, new-feature

#5259 Keep shared images on addon uninstall
  supervisor/addons/addon.py
  supervisor/addons/manager.py
  supervisor/docker/interface.py
  tests/addons/test_manager.py
Labels: cla-signed, bugfix

#5263 Bump cosign to v2.4.0
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  build.yaml
Labels: cla-signed, dependencies

#5262 Use separate data structure for IP configuration
  supervisor/api/network.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/host/configuration.py
  supervisor/host/network.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
  tests/host/test_network.py
Labels: cla-signed, refactor

#5265 Minimize D-Bus requirements for tests
  .github/workflows/ci.yaml
  tests/conftest.py
Labels: cla-signed, ci, chore

#5267 Use single quotes in f-strings
  supervisor/homeassistant/module.py
  supervisor/utils/systemd_journal.py
Labels: cla-signed, chore

#5272 Add `manual_only` option to addon boot config
  .github/PULL_REQUEST_TEMPLATE.md
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/api/addons.py
  supervisor/api/const.py
  supervisor/const.py
  tests/addons/test_addon.py
  tests/api/test_addons.py
  tests/fixtures/addons/local/example/config.yaml
Labels: cla-signed, new-feature

#5276 Persist currently selected slot on successful boot
  supervisor/os/manager.py
Labels: cla-signed, bugfix

#5268 Keep shared images on update
  supervisor/docker/addon.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  tests/addons/test_manager.py
  tests/fixtures/addons/local/example_image/Dockerfile.aarch64
  tests/fixtures/addons/local/example_image/build.yaml
  tests/fixtures/addons/local/example_image/config.yaml
  tests/store/test_store_manager.py
Labels: cla-signed, bugfix

#5278 Improve connection settings tests
  tests/api/test_network.py
  tests/const.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
  tests/dbus/network/test_connection.py
  tests/dbus/network/test_interface.py
  tests/dbus/network/test_network_manager.py
  tests/dbus/network/test_settings.py
  tests/dbus/network/test_wireless.py
  tests/dbus_service_mocks/network_active_connection.py
  tests/dbus_service_mocks/network_connection_settings.py
  tests/dbus_service_mocks/network_device.py
  tests/host/test_network.py
Labels: cla-signed, test

#5282 Make IPv4 and IPv6 parse errors raise an API error
  supervisor/api/network.py
  tests/api/test_network.py
Labels: cla-signed, bugfix
