Repository home-assistant/supervisor, pull requests merged in 2024-09, with the labels that each got.

#5287 Add "lines" and "verbose" query parameters for advanced logs
  supervisor/api/host.py
  tests/api/test_host.py
Labels: cla-signed, missing-documentation, new-feature

#5293 Improve WiFi settings error handling
  supervisor/dbus/network/setting/generate.py
  supervisor/host/network.py
  tests/api/test_network.py
  tests/dbus_service_mocks/network_manager.py
Labels: cla-signed, bugfix

#5308 Bump aiohttp to 3.10.6
  requirements.txt
Labels: cla-signed, dependencies

#5314 Bump aiohttp to 3.10.8
  requirements.txt
Labels: cla-signed, dependencies

#5313 Exclude Text-to-Speech cache from backups
  supervisor/homeassistant/module.py
Labels: cla-signed, bugfix

#5316 Add OHF logo to README
  README.md
Labels: cla-signed, chore
