Repository home-assistant/supervisor, pull requests merged in 2024-07, with the labels that each got.

#5152 Use uv instead of pip in Supervisor
  .devcontainer/devcontainer.json
  Dockerfile
Labels: cla-signed, refactor

#5170 Migrate supervisor devcontainer from pip to uv
  .devcontainer/devcontainer.json
Labels: cla-signed, ci

#5189 Ignore false positive no-member error
  supervisor/coresys.py
Labels: cla-signed, ci

#5191 Small cleanup to pyproject.toml
  pyproject.toml
Labels: cla-signed, refactor

#5184 Ignore failure to query wireless strength.
  supervisor/host/configuration.py
Labels: cla-signed, bugfix

#5202 Add support for offline DB migration
  supervisor/homeassistant/api.py
  supervisor/homeassistant/core.py
  tests/conftest.py
  tests/homeassistant/test_core.py
Labels: cla-signed, new-feature

#5204 Add hard-coded image fallback for plugins for offline start
  supervisor/plugins/audio.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  tests/plugins/test_plugin_base.py
Labels: cla-signed, bugfix

#5205 Restrict stopping core during migrations with force option
  supervisor/api/const.py
  supervisor/api/homeassistant.py
  supervisor/api/host.py
  supervisor/exceptions.py
  tests/api/test_homeassistant.py
  tests/api/test_host.py
Labels: cla-signed, missing-documentation, new-feature
