Repository home-assistant/supervisor, pull requests merged in 2024-04, with the labels that each got.

#4995 Update base images to 3.12-alpine3.19
  build.yaml
Labels: cla-signed, dependencies

#4986 Format NetworkManager connection name correctly for VLANs
  supervisor/dbus/network/setting/generate.py
Labels: cla-signed, bugfix

#4997 Fix submounts of /dev being read-only with Docker 25+
  supervisor/docker/const.py
  tests/docker/__init__.py
  tests/docker/test_addon.py
  tests/docker/test_audio.py
  tests/docker/test_homeassistant.py
Labels: cla-signed, bugfix

#4972 Use Systemd Journal API for all logs endpoints in API
  supervisor/api/__init__.py
  supervisor/api/addons.py
  supervisor/api/audio.py
  supervisor/api/dns.py
  supervisor/api/homeassistant.py
  supervisor/api/host.py
  supervisor/api/multicast.py
  supervisor/api/supervisor.py
  supervisor/api/utils.py
  tests/api/__init__.py
  tests/api/test_addons.py
  tests/api/test_audio.py
  tests/api/test_dns.py
  tests/api/test_homeassistant.py
  tests/api/test_host.py
  tests/api/test_multicast.py
  tests/api/test_supervisor.py
Labels: cla-signed, API, new-feature

#5000 Increase DNS timeout for CoreDNS users
  supervisor/docker/manager.py
Labels: cla-signed, bugfix

#5011 Addon load should not fail due to docker error
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#5010 Adopt a disabled data disk
  supervisor/os/const.py
  supervisor/resolution/checks/disabled_data_disk.py
  supervisor/resolution/const.py
  supervisor/resolution/fixups/system_adopt_data_disk.py
  supervisor/resolution/fixups/system_rename_data_disk.py
  tests/dbus/udisks2/test_filesystem.py
  tests/dbus_service_mocks/base.py
  tests/dbus_service_mocks/udisks2_filesystem.py
  tests/dbus_service_mocks/udisks2_manager.py
  tests/resolution/check/test_check_disabled_data_disk.py
  tests/resolution/fixup/test_system_adopt_data_disk.py
  tests/resolution/fixup/test_system_rename_data_disk.py
Labels: cla-signed, new-feature

#4899 Bump aiohttp to 3.9.4
  requirements.txt
Labels: cla-signed, dependencies

#5014 Mount manager reload mounts all failed mounts
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  tests/mounts/test_manager.py
Labels: cla-signed, new-feature

#5017 Allow restarting core in safe mode
  supervisor/api/const.py
  supervisor/api/homeassistant.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/core.py
  tests/api/test_homeassistant.py
Labels: cla-signed, new-feature

#5022 Fix Supervisor logs fallback
  supervisor/api/__init__.py
  supervisor/api/host.py
  tests/api/test_supervisor.py
Labels: cla-signed, bugfix

#5024 Add issues field to create full backup suggestion
  supervisor/resolution/fixups/system_create_full_backup.py
Labels: cla-signed, bugfix

#5041 Revert orjson to 3.9.15 due to segmentation faults
  requirements.txt
Labels: cla-signed, dependencies

#5048 Bump pytest-asyncio to 0.23.6
  requirements_tests.txt
Labels: cla-signed, dependencies
