Repository home-assistant/supervisor, pull requests merged in 2024-02, with the labels that each got.

#4872 Improve error handling when mounts fail
  supervisor/backups/manager.py
  supervisor/exceptions.py
  supervisor/mounts/const.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/mounts/validate.py
  tests/api/test_backups.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
Labels: cla-signed, new-feature

#4882 Mount status checks look at connection
  supervisor/dbus/const.py
  supervisor/dbus/systemd.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  tests/api/test_backups.py
  tests/api/test_mounts.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/mounts/test_manager.py
  tests/mounts/test_mount.py
  tests/resolution/fixup/test_mount_execute_reload.py
  tests/resolution/fixup/test_mount_execute_remove.py
Labels: cla-signed, bugfix

#4888 Bump securetar to 2024.2.0
  requirements.txt
Labels: cla-signed, dependencies

#4884 Create backups files without having to copy inner tarballs
  supervisor/backups/backup.py
  tests/backups/test_backup.py
Labels: cla-signed, performance

#4898 Fix new complaint by ruff 0.2.1
  supervisor/mounts/mount.py
Labels: cla-signed, bugfix

#4897 Fix autoupdate time compare
  supervisor/addons/addon.py
  supervisor/addons/model.py
Labels: cla-signed, bugfix

#4925 Bump securetar to 2024.2.1
  requirements.txt
Labels: cla-signed, dependencies

#4912 Allow listing of HA users via admin CLI
  supervisor/api/__init__.py
  supervisor/api/auth.py
  supervisor/api/const.py
  supervisor/auth.py
  supervisor/exceptions.py
  tests/api/middleware/test_security.py
  tests/api/test_auth.py
Labels: cla-signed, new-feature

#4913 Allow removing addon config on uninstall
  supervisor/addons/addon.py
  supervisor/addons/manager.py
  supervisor/api/addons.py
  supervisor/api/const.py
  tests/api/test_addons.py
Labels: cla-signed, new-feature

#4934 Add an admin only device wipe API
  supervisor/api/__init__.py
  supervisor/api/middleware/security.py
  supervisor/api/os.py
  supervisor/dbus/agent/system.py
  supervisor/os/data_disk.py
  tests/api/middleware/test_security.py
  tests/api/test_os.py
  tests/dbus/agent/test_system.py
  tests/dbus_service_mocks/agent_system.py
  tests/dbus_service_mocks/logind.py
  tests/os/test_data_disk.py
Labels: cla-signed, new-feature, WTH

#4933 Fix check used for addon auto update
  supervisor/misc/tasks.py
Labels: cla-signed, bugfix
