Repository home-assistant/supervisor, pull requests merged in 2024-03, with the labels that each got.

#4942 Proxy WebSocket close messages as well
  supervisor/api/proxy.py
Labels: cla-signed, bugfix

#4943 APIForbidden should result in 403 status
  supervisor/api/utils.py
  supervisor/exceptions.py
  tests/api/test_discovery.py
Labels: cla-signed, bugfix

#4937 Remove discovery config validation from supervisor
  supervisor/addons/validate.py
  supervisor/api/discovery.py
  supervisor/discovery/__init__.py
  supervisor/discovery/services/__init__.py
  supervisor/discovery/services/adguard.py
  supervisor/discovery/services/almond.py
  supervisor/discovery/services/deconz.py
  supervisor/discovery/services/esphome.py
  supervisor/discovery/services/homematic.py
  supervisor/discovery/services/matter.py
  supervisor/discovery/services/motioneye.py
  supervisor/discovery/services/mqtt.py
  supervisor/discovery/services/otbr.py
  supervisor/discovery/services/ozw.py
  supervisor/discovery/services/rtsp_to_webrtc.py
  supervisor/discovery/services/unifi.py
  supervisor/discovery/services/vlc_telnet.py
  supervisor/discovery/services/wyoming.py
  supervisor/discovery/services/zwave_js.py
  supervisor/discovery/validate.py
  tests/addons/test_config.py
  tests/api/test_discovery.py
  tests/discovery/__init__.py
  tests/discovery/test_adguard.py
  tests/discovery/test_almond.py
  tests/discovery/test_deconz.py
  tests/discovery/test_esphome.py
  tests/discovery/test_homematic.py
  tests/discovery/test_matter.py
  tests/discovery/test_motioneye.py
  tests/discovery/test_mqtt.py
  tests/discovery/test_otbr.py
  tests/discovery/test_ozw.py
  tests/discovery/test_rtsp_to_webrtc.py
  tests/discovery/test_unifi.py
  tests/discovery/test_validate.py
  tests/discovery/test_vlc_telnet.py
  tests/discovery/test_wyoming.py
  tests/discovery/test_zwave_js.py
Labels: cla-signed, refactor

#4955 Avoid Watchdog starting Core before Supervisor is in startup
  supervisor/homeassistant/core.py
  tests/homeassistant/test_home_assistant_watchdog.py
Labels: bugfix

#4945 Allow client to change boot slot via API
  supervisor/api/__init__.py
  supervisor/api/const.py
  supervisor/api/os.py
  supervisor/dbus/rauc.py
  supervisor/exceptions.py
  supervisor/host/manager.py
  supervisor/os/manager.py
  tests/api/test_os.py
  tests/dbus/test_rauc.py
  tests/dbus_service_mocks/rauc.py
  tests/host/test_manager.py
Labels: cla-signed, new-feature

#4944 Cache existence of addon paths
  supervisor/addons/addon.py
  supervisor/addons/manager.py
  supervisor/addons/model.py
  supervisor/resolution/fixups/store_execute_reload.py
  supervisor/store/__init__.py
  supervisor/store/git.py
  supervisor/store/repository.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/store/test_store_manager.py
Labels: cla-signed, refactor

#4965 Restore lost continue statement
  supervisor/misc/tasks.py
Labels: cla-signed, bugfix

#4964 Fix some expected boot slot fields are optional
  supervisor/dbus/rauc.py
  supervisor/os/manager.py
  tests/dbus_service_mocks/rauc.py
  tests/os/test_manager.py
Labels: cla-signed, bugfix

#4963 Use Journal Export Format for host (advanced) logs
  supervisor/api/const.py
  supervisor/api/host.py
  supervisor/exceptions.py
  supervisor/host/const.py
  supervisor/host/logs.py
  supervisor/utils/systemd_journal.py
  tests/api/test_host.py
  tests/conftest.py
  tests/fixtures/logs_export_host.txt
  tests/fixtures/logs_export_supervisor.txt
  tests/host/test_logs.py
  tests/utils/test_systemd_journal.py
Labels: cla-signed, new-feature

#4971 Bump cosign to `v2.2.3` and builder to `2024.03.5`
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  build.yaml
Labels: cla-signed, dependencies

#4974 Fix IncompleteReadError happening sometimes when reading Systemd logs
  supervisor/utils/systemd_journal.py
Labels: cla-signed, bugfix

#4968 Unsupported if wrong image used on virtualization
  supervisor/api/const.py
  supervisor/api/host.py
  supervisor/dbus/const.py
  supervisor/dbus/systemd.py
  supervisor/host/info.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/virtualization_image.py
  tests/api/test_host.py
  tests/dbus_service_mocks/systemd.py
  tests/resolution/evaluation/test_virtualization_image.py
Labels: cla-signed, new-feature
