Repository home-assistant/supervisor, pull requests merged in 2024-12, with the labels that each got.

#5464 Fix and extend cloud backup support
  supervisor/api/backups.py
  supervisor/api/const.py
  supervisor/backups/backup.py
  supervisor/backups/const.py
  supervisor/backups/manager.py
  supervisor/backups/validate.py
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/homeassistant.py
  supervisor/exceptions.py
  supervisor/homeassistant/const.py
  supervisor/homeassistant/websocket.py
  supervisor/misc/tasks.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  tests/api/test_backups.py
  tests/api/test_mounts.py
  tests/backups/conftest.py
  tests/backups/test_manager.py
  tests/docker/test_homeassistant.py
  tests/misc/test_tasks.py
  tests/resolution/fixup/test_mount_execute_remove.py
Labels: cla-signed, new-feature

#5466 Bump aiohttp to 3.11.10
  requirements.txt
Labels: cla-signed, dependencies

#5473 Add size in bytes to backups
  supervisor/api/backups.py
  supervisor/api/const.py
  supervisor/backups/backup.py
  tests/api/test_backups.py
  tests/conftest.py
Labels: cla-signed, new-feature

#5472 Fix backup consolidate and upload duplicate
  supervisor/backups/manager.py
  tests/api/test_backups.py
Labels: cla-signed, bugfix

#5419 Support CGroup v2 on Supervised with manual addon restarts
  supervisor/addons/addon.py
  supervisor/docker/addon.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/cgroup.py
  supervisor/resolution/fixups/addon_execute_restart.py
  tests/docker/test_addon.py
  tests/resolution/evaluation/test_evaluate_cgroup.py
  tests/resolution/fixup/test_addon_execute_restart.py
Labels: cla-signed, new-feature

#5479 Backup not found returns 404 instead of 400
  supervisor/api/backups.py
  supervisor/exceptions.py
  tests/api/test_backups.py
Labels: cla-signed, bugfix

#5482 Add location to backup download and remove APIs
  supervisor/api/backups.py
  tests/api/test_backups.py
  tests/backups/test_manager.py
Labels: cla-signed, new-feature

#5490 Add all addons flag to partial backups
  supervisor/api/backups.py
  tests/api/test_backups.py
Labels: cla-signed, new-feature

#5491 Restore backup from specific location
  supervisor/api/backups.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
  tests/backups/test_backup.py
Labels: cla-signed, new-feature

#5480 Use status 404 in more places when appropriate
  supervisor/api/addons.py
  supervisor/api/discovery.py
  supervisor/api/docker.py
  supervisor/api/jobs.py
  supervisor/api/mounts.py
  supervisor/api/network.py
  supervisor/api/resolution.py
  supervisor/api/services.py
  supervisor/api/store.py
  tests/api/test_addons.py
  tests/api/test_discovery.py
  tests/api/test_docker.py
  tests/api/test_jobs.py
  tests/api/test_mounts.py
  tests/api/test_network.py
  tests/api/test_resolution.py
  tests/api/test_services.py
  tests/api/test_store.py
Labels: cla-signed, breaking-change

#5498 Bump aiohttp to 3.11.11
  requirements.txt
Labels: cla-signed, dependencies

#5506 Add astroid to pytest requirements
  requirements_tests.txt
Labels: cla-signed, dependencies

#5515 Fix backup remove for alternate locations
  supervisor/backups/manager.py
Labels: cla-signed, bugfix

#5517 Drop dead folder restore code
  supervisor/backups/backup.py
Labels: cla-signed, chore

#5518 Avoid lingering tasks when using background backup tasks
  supervisor/api/backups.py
Labels: cla-signed, bugfix

#5519 Check password early on backup restore
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
  tests/backups/test_manager.py
Labels: cla-signed, new-feature
