Repository home-assistant/supervisor, pull requests merged in 2024-10, with the labels that each got.

#5321 Allow Supervisor token authentication from landing page
  supervisor/api/middleware/security.py
Labels: cla-signed, Hacktoberfest, new-feature

#5335 Drop support for Debian 11 Bullseye
  supervisor/resolution/evaluations/operating_system.py
Labels: cla-signed, Hacktoberfest

#5331 Update DNS plug-in on network change
  supervisor/host/network.py
  tests/host/test_connectivity.py
Labels: cla-signed, Hacktoberfest, bugfix

#5334 Fix number of lines returned with host logs' query argument
  supervisor/api/host.py
  tests/api/__init__.py
  tests/api/test_host.py
Labels: cla-signed, Hacktoberfest, bugfix

#5342 Throttle connectivity check on connectivity issue
  supervisor/supervisor.py
  tests/common.py
  tests/jobs/test_job_decorator.py
  tests/test_supervisor.py
Labels: cla-signed, Hacktoberfest, performance

#5354 Fix Supervisor log fallback for the /follow endpoint
  supervisor/api/__init__.py
  tests/api/test_supervisor.py
Labels: cla-signed, Hacktoberfest, bugfix

#5358 Suppress ClientConnectionResetError when returning logs
  supervisor/api/host.py
Labels: cla-signed, Hacktoberfest, bugfix

#5375 Update supervisor immediately on new version
  supervisor/misc/tasks.py
  tests/fixtures/version_stable.json
  tests/misc/test_tasks.py
Labels: cla-signed, Hacktoberfest, new-feature
