Repository home-assistant/supervisor, pull requests merged in 2024-01, with the labels that each got.

#4815 Update python to 3.12
  .devcontainer/devcontainer.json
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  build.yaml
  pyproject.toml
  requirements_tests.txt
  supervisor/addons/addon.py
  supervisor/backups/backup.py
  supervisor/config.py
  supervisor/hardware/helper.py
  supervisor/homeassistant/module.py
  supervisor/utils/dt.py
  tests/api/middleware/test_security.py
  tests/conftest.py
  tests/jobs/test_job_decorator.py
  tox.ini
Labels: cla-signed, dependencies, python

#4816 Improve json performance by porting core orjson utils
  requirements.txt
  supervisor/api/auth.py
  supervisor/api/utils.py
  supervisor/utils/json.py
  tests/utils/test_json.py
Labels: cla-signed, performance

#4817 Fix dirhash failing to import pkg_resources
  .github/workflows/builder.yml
  requirements.txt
Labels: cla-signed, build, bugfix

#4819 Fix add-on rebuild with ingress
  supervisor/addons/addon.py
Labels: cla-signed, bugfix

#4802 Add background option to backup APIs
  supervisor/api/__init__.py
  supervisor/api/backups.py
  supervisor/api/const.py
  supervisor/api/jobs.py
  supervisor/api/utils.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/const.py
  supervisor/coresys.py
  supervisor/exceptions.py
  supervisor/jobs/__init__.py
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/misc/scheduler.py
  supervisor/store/__init__.py
  tests/api/test_backups.py
  tests/api/test_jobs.py
  tests/backups/conftest.py
  tests/backups/test_backup.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/docker/test_interface.py
  tests/jobs/test_job_decorator.py
  tests/jobs/test_job_manager.py
Labels: cla-signed, new-feature

#4833 Fix bootstrap log typo
  supervisor/bootstrap.py
Labels: cla-signed, bugfix

#4832 Addon devs can block auto update for breaking versions
  supervisor/addons/addon.py
  supervisor/addons/const.py
  supervisor/addons/model.py
  supervisor/addons/validate.py
  supervisor/misc/tasks.py
  tests/addons/test_addon.py
  tests/fixtures/addons/local/example/config.yaml
Labels: cla-signed, new-feature

#4853 Fix serialization issue adding error to job
  supervisor/jobs/__init__.py
  tests/jobs/test_job_manager.py
Labels: cla-signed, bugfix

#4838 Auto updates to new version delay for 24 hours
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/const.py
  supervisor/misc/tasks.py
  supervisor/store/data.py
  tests/store/test_store_manager.py
Labels: cla-signed, new-feature

#4854 Use json_dumps helper for websocket messages
  supervisor/api/proxy.py
  supervisor/homeassistant/websocket.py
Labels: cla-signed, performance

#4861 Explicitly log when API requests timeout
  supervisor/homeassistant/api.py
Labels: cla-signed, refactor

#4862 Reset failed API call counter on successful API call
  supervisor/misc/tasks.py
  tests/misc/test_tasks.py
Labels: cla-signed, bugfix
