Repository home-assistant/supervisor, pull requests merged in 2024-06, with the labels that each got.

#5105 Add uninstall addon suggestion to detached_addon_removed
  supervisor/resolution/checks/detached_addon_removed.py
  supervisor/resolution/fixups/addon_execute_remove.py
  tests/resolution/check/test_check_detached_addon_missing.py
  tests/resolution/check/test_check_detached_addon_removed.py
  tests/resolution/fixup/test_addon_execute_remove.py
Labels: cla-signed, new-feature

#5111 Fix addon in wrong state after restore
  supervisor/addons/addon.py
  supervisor/core.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix

#5120 Add safe mode option to core rebuild
  supervisor/api/homeassistant.py
  supervisor/homeassistant/core.py
  tests/api/test_homeassistant.py
Labels: cla-signed, new-feature

#5124 Home Assistant watchdog attempts safe mode after max fails
  supervisor/misc/tasks.py
  tests/misc/test_tasks.py
Labels: cla-signed, new-feature

#5141 Await uninstall of addon in fixup
  supervisor/resolution/fixups/addon_execute_remove.py
Labels: cla-signed, bugfix

#5142 Fix uninstall of add-on on fixup
  supervisor/resolution/fixups/addon_execute_remove.py
Labels: cla-signed, bugfix

#5128 Add music assistant to the builtin repositories
  supervisor/store/validate.py
  tests/fixtures/addons/git/d5369777/repository.json
  tests/store/test_custom_repository.py
  tests/store/test_store_manager.py
  tests/store/test_validate.py
Labels: cla-signed, new-feature

#5147 Ignore dns-data field in network settings update
  supervisor/dbus/network/setting/__init__.py
  tests/dbus/network/setting/test_init.py
  tests/dbus_service_mocks/network_connection_settings.py
Labels: cla-signed, bugfix

#5151 Bump Supervisor to Alpine 3.20
  build.yaml
Labels: cla-signed, dependencies
