Repository home-assistant/supervisor, pull requests merged in 2025-02, with the labels that each got.

#5596 Update cache if a backup file is missing
  supervisor/api/backups.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
  tests/backups/test_manager.py
  tests/misc/test_tasks.py
Labels: cla-signed, new-feature

#5597 Use full match in homeassistant backup excludes
  supervisor/homeassistant/module.py
  tests/homeassistant/test_module.py
Labels: cla-signed, bugfix

#5599 Handle non-existing file in Backup password check too
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
  tests/backups/conftest.py
  tests/backups/test_backup.py
  tests/backups/test_manager.py
  tests/fixtures/backup_example_enc.tar
Labels: cla-signed, bugfix

#5600 Fix restoring unencrypted backup in corner case
  supervisor/backups/manager.py
  tests/api/test_backups.py
Labels: cla-signed, bugfix

#5602 Prevent race condition with location reload and backups list
  supervisor/backups/manager.py
  tests/api/test_backups.py
Labels: cla-signed, bugfix

#5605 Drop Docker config from Supervisor backup
  supervisor/backups/backup.py
  supervisor/backups/const.py
  supervisor/backups/manager.py
  tests/backups/test_manager.py
Labels: cla-signed, breaking-change

#5609 Print the exact reason if the WebSocket event to Core fails
  supervisor/homeassistant/module.py
  tests/homeassistant/test_module.py
Labels: cla-signed, chore

#5630 Avoid exception when handling closed WebSocket connection
  supervisor/homeassistant/websocket.py
Labels: cla-signed, bugfix

#5632 Always validate Backup before restoring
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
  tests/backups/conftest.py
  tests/backups/test_backup.py
  tests/backups/test_manager.py
Labels: cla-signed, refactor

#5640 Generate Python bytecode for site-packages during build
  Dockerfile
Labels: cla-signed, bugfix

#5641 Bump uv to 0.6.1
  Dockerfile
Labels: cla-signed, dependencies

#5642 Use uv to install supervisor
  Dockerfile
Labels: cla-signed, python

#5634 Remove I/O in event loop for backup create and restore operations
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/homeassistant/module.py
  supervisor/resolution/fixups/store_execute_reset.py
  supervisor/store/git.py
  supervisor/utils/__init__.py
  tests/utils/test_remove_folder.py
Labels: cla-signed, bugfix, refactor

#5644 Capture errors correctly while copying backups
  supervisor/backups/manager.py
Labels: cla-signed, bugfix

#5646 Disable uv cache when creating container image
  Dockerfile
Labels: cla-signed, python

#5648 Remove I/O in event loop for Home Assistant Core backup
  supervisor/homeassistant/module.py
Labels: cla-signed, refactor

#5649 Remove I/O in event loop for add-on backup and restore
  supervisor/addons/addon.py
  supervisor/docker/addon.py
  supervisor/host/apparmor.py
  tests/host/test_apparmor_control.py
Labels: cla-signed, refactor

#5660 Handle non-zero subprocess exits
  supervisor/utils/__init__.py
Labels: cla-signed, bugfix

#5667 Build Python wheels for Python 3.13
  .github/workflows/builder.yml
Labels: cla-signed, python, refactor

#5670 Define CPU architecture to fix armhf builds
  Dockerfile
Labels: cla-signed, ci, bugfix

#5664 Improve D-Bus timeout error handling
  supervisor/dbus/udisks2/__init__.py
  supervisor/exceptions.py
  supervisor/os/data_disk.py
  supervisor/utils/dbus.py
Labels: cla-signed, bugfix

#5669 Fix add-on store reset
  supervisor/resolution/fixups/store_execute_reset.py
  supervisor/utils/__init__.py
  tests/resolution/fixup/test_store_execute_reset.py
Labels: cla-signed, bugfix

#5672 Improve Supervisor restart detection message
  supervisor/core.py
Labels: cla-signed, chore

#5652 FileConfiguration uses executor for I/O
  supervisor/__main__.py
  supervisor/addons/addon.py
  supervisor/addons/build.py
  supervisor/addons/data.py
  supervisor/addons/manager.py
  supervisor/api/addons.py
  supervisor/api/auth.py
  supervisor/api/discovery.py
  supervisor/api/jobs.py
  supervisor/auth.py
  supervisor/bootstrap.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/dbus/agent/boards/__init__.py
  supervisor/discovery/__init__.py
  supervisor/docker/addon.py
  supervisor/docker/manager.py
  supervisor/homeassistant/core.py
  supervisor/ingress.py
  supervisor/mounts/manager.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/manager.py
  supervisor/plugins/observer.py
  supervisor/resolution/check.py
  supervisor/resolution/evaluate.py
  supervisor/resolution/fixup.py
  supervisor/resolution/module.py
  supervisor/services/__init__.py
  supervisor/supervisor.py
  supervisor/updater.py
  supervisor/utils/common.py
  tests/addons/test_addon.py
  tests/addons/test_build.py
  tests/addons/test_manager.py
  tests/api/test_discovery.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/dbus/agent/boards/test_green.py
  tests/dbus/agent/boards/test_yellow.py
  tests/docker/test_credentials.py
  tests/mounts/test_manager.py
  tests/resolution/check/test_check.py
  tests/store/test_custom_repository.py
  tests/store/test_store_manager.py
  tests/test_auth.py
  tests/test_ingress.py
Labels: cla-signed, refactor

#5683 Use await for all FileConfiguration calls
  supervisor/addons/addon.py
  supervisor/api/backups.py
  supervisor/api/dns.py
  supervisor/api/docker.py
  supervisor/api/homeassistant.py
  supervisor/api/jobs.py
  supervisor/api/mounts.py
  supervisor/api/os.py
  supervisor/api/resolution.py
  supervisor/api/security.py
  supervisor/api/services.py
  supervisor/api/supervisor.py
  supervisor/resolution/fixups/mount_execute_remove.py
  supervisor/services/interface.py
  supervisor/services/modules/mqtt.py
  supervisor/services/modules/mysql.py
  supervisor/store/__init__.py
Labels: cla-signed, bugfix

#5682 Add more context to Sentry reports early during startup
  supervisor/bootstrap.py
  supervisor/coresys.py
  supervisor/misc/filter.py
  tests/misc/test_filter_data.py
Labels: cla-signed, new-feature

#5681 Correctly handle aiohttp requests in Sentry reporting
  supervisor/misc/filter.py
  tests/misc/test_filter_data.py
  tests/misc/test_sanitise_url.py
Labels: cla-signed, bugfix

#5673 Temporary directory to executor
  supervisor/addons/addon.py
  supervisor/api/backups.py
  supervisor/supervisor.py
  supervisor/utils/__init__.py
Labels: cla-signed, refactor

#5678 Open to executor
  supervisor/api/store.py
  supervisor/host/apparmor.py
  supervisor/mounts/mount.py
  supervisor/os/manager.py
  supervisor/store/data.py
  supervisor/store/repository.py
  supervisor/utils/apparmor.py
  supervisor/utils/common.py
  supervisor/utils/yaml.py
  tests/mounts/test_manager.py
Labels: cla-signed, refactor

#5685 Enable Sentry asyncio integration
  supervisor/utils/sentry.py
Labels: cla-signed, new-feature

#5691 Add body with update information to frontend update PRs
  .github/workflows/update_frontend.yml
Labels: cla-signed, ci

#5692 Make advanced logs error test work in all test environments
  tests/api/test_host.py
Labels: cla-signed, test

#5694 Avoid space in update link of frontend update PR
  .github/workflows/update_frontend.yml
Labels: cla-signed, ci

#5696 Load resolution evaluation, check and fixups early
  supervisor/bootstrap.py
  supervisor/resolution/check.py
  supervisor/resolution/evaluate.py
  supervisor/resolution/fixup.py
  supervisor/resolution/module.py
  tests/conftest.py
  tests/resolution/check/test_check.py
Labels: cla-signed, bugfix

#5686 Initialize Supervisor Core state in constructor
  supervisor/core.py
  tests/api/middleware/test_security.py
  tests/conftest.py
  tests/homeassistant/test_websocket.py
  tests/jobs/test_job_decorator.py
  tests/jobs/test_job_manager.py
  tests/test_core.py
  tests/test_coresys.py
Labels: cla-signed, bugfix

#5697 Capture warnings and report to sentry
  supervisor/bootstrap.py
Labels: cla-signed, new-feature
