Repository home-assistant/supervisor, pull requests merged in 2025-04, with the labels that each got.

#5798 Switch iter_chunked to iter_chunks
  supervisor/api/ingress.py
Labels: cla-signed, refactor

#5815 Fix root path requests
  supervisor/api/ingress.py
  supervisor/api/proxy.py
  tests/api/test_proxy.py
Labels: cla-signed, bugfix

#5805 Fix mypy issues in docker, hardware and homeassistant modules
  supervisor/api/homeassistant.py
  supervisor/auth.py
  supervisor/bootstrap.py
  supervisor/const.py
  supervisor/docker/addon.py
  supervisor/docker/homeassistant.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  supervisor/docker/monitor.py
  supervisor/docker/network.py
  supervisor/docker/supervisor.py
  supervisor/hardware/disk.py
  supervisor/hardware/manager.py
  supervisor/homeassistant/api.py
  supervisor/homeassistant/core.py
  supervisor/homeassistant/module.py
  supervisor/homeassistant/websocket.py
  supervisor/host/info.py
  tests/docker/conftest.py
  tests/docker/test_credentials.py
  tests/docker/test_interface.py
  tests/homeassistant/test_core.py
Labels: cla-signed, refactor

#5821 Drop typing-extensions from requirements
  requirements.txt
  requirements_tests.txt
Labels: cla-signed, chore

#5825 Avoid using host system socket for logs tests
  tests/api/test_host.py
Labels: cla-signed, test

#5826 Add country to Supervisor info
  supervisor/api/supervisor.py
  supervisor/config.py
  supervisor/const.py
  supervisor/validate.py
  tests/api/test_supervisor.py
Labels: cla-signed, new-feature, need-client-library

#5831 Unify Supervisor event message functions
  supervisor/addons/addon.py
  supervisor/exceptions.py
  supervisor/homeassistant/websocket.py
  tests/homeassistant/test_websocket.py
Labels: cla-signed, refactor

#5833 Add dedicated version update refresh for main components
  supervisor/api/__init__.py
  supervisor/api/root.py
  tests/api/test_root.py
Labels: cla-signed, new-feature

#5851 Revert "Recreate aiohttp session on connectivity check (#5332)"
  supervisor/coresys.py
  supervisor/supervisor.py
Labels: cla-signed, bugfix

#5847 Remove deprecated ruff rule S320
  pyproject.toml
Labels: cla-signed, chore

#5846 Avoid reading add-ons twice unnecessarily
  supervisor/store/__init__.py
Labels: cla-signed, bugfix, refactor

#5854 Bump uv to 0.6.17
  Dockerfile
Labels: cla-signed, dependencies

#5845 Check local store repository for changes
  supervisor/store/repository.py
  supervisor/utils/__init__.py
  tests/addons/test_addon.py
  tests/store/test_store_manager.py
  tests/utils/test_utils_init.py
Labels: cla-signed, new-feature

#5858 Avoid using host system socket for systemd journald tests
  tests/resolution/evaluation/test_evaluate_systemd_journal.py
Labels: cla-signed, test
