Repository home-assistant/supervisor, pull requests merged in 2025-03, with the labels that each got.

#5700 Update Supervisor bug form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: cla-signed, ci

#5702 Fix tests in devcontainer by removing resolution center
  tests/conftest.py
Labels: cla-signed, bugfix, test

#5688 Move `read_text` to executor
  supervisor/__main__.py
  supervisor/addons/addon.py
  supervisor/addons/manager.py
  supervisor/addons/model.py
  supervisor/api/__init__.py
  supervisor/api/addons.py
  supervisor/api/host.py
  supervisor/api/store.py
  supervisor/backups/manager.py
  supervisor/bootstrap.py
  supervisor/core.py
  supervisor/dbus/network/__init__.py
  supervisor/docker/addon.py
  supervisor/docker/interface.py
  supervisor/hardware/disk.py
  supervisor/homeassistant/core.py
  supervisor/host/info.py
  supervisor/jobs/__init__.py
  supervisor/jobs/decorator.py
  supervisor/misc/filter.py
  supervisor/misc/tasks.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/os/data_disk.py
  supervisor/os/manager.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/manager.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  supervisor/resolution/check.py
  supervisor/resolution/checks/dns_server.py
  supervisor/resolution/checks/dns_server_ipv6.py
  supervisor/resolution/checks/free_space.py
  supervisor/resolution/evaluate.py
  supervisor/resolution/fixup.py
  supervisor/resolution/notify.py
  supervisor/supervisor.py
  supervisor/utils/dbus.py
  supervisor/utils/log_format.py
  supervisor/utils/sentry.py
  tests/api/test_supervisor.py
  tests/homeassistant/test_home_assistant_watchdog.py
  tests/host/test_info.py
  tests/utils/test_log_format.py
Labels: cla-signed, refactor

#5701 Fix cloning of add-on store repository
  supervisor/store/git.py
  tests/store/test_repository_git.py
Labels: cla-signed, bugfix

#5703 No executor task in sentry call when not initialized
  supervisor/utils/sentry.py
Labels: cla-signed, refactor

#5716 Avoid loading add-on store repositories too early
  supervisor/store/__init__.py
  supervisor/store/git.py
Labels: cla-signed, refactor

#5712 Replace non-unicode characters for add-on static files
  supervisor/api/store.py
  tests/api/test_store.py
  tests/conftest.py
Labels: cla-signed, refactor

#5718 Exclude non-Supervisor Server Error codes from Sentry reporting
  supervisor/utils/sentry.py
Labels: cla-signed, refactor

#5719 Fix add-on repair log message
  supervisor/resolution/fixups/addon_execute_repair.py
Labels: cla-signed, bugfix

#5722 Stop streaming logs when client closes connection
  supervisor/api/host.py
Labels: cla-signed, bugfix

#5698 Finish migrating read_text to executor
  supervisor/addons/addon.py
  supervisor/arch.py
  supervisor/core.py
  supervisor/hardware/helper.py
  supervisor/homeassistant/core.py
  supervisor/homeassistant/module.py
  supervisor/host/logs.py
  supervisor/plugins/audio.py
  supervisor/plugins/dns.py
  supervisor/resolution/evaluations/apparmor.py
  supervisor/resolution/evaluations/lxc.py
  supervisor/utils/json.py
  tests/addons/test_addon.py
  tests/hardware/test_helper.py
  tests/homeassistant/test_module.py
Labels: cla-signed, refactor

#5723 Make sure to close file stream after backup upload
  supervisor/api/backups.py
Labels: cla-signed, bugfix

#5717 Fix add-on store repository getting removed without internet
  supervisor/store/git.py
Labels: cla-signed, bugfix

#5725 Call core post init
  supervisor/bootstrap.py
Labels: cla-signed, bugfix

#5729 Revert "Enable Sentry asyncio integration (#5685)"
  supervisor/utils/sentry.py
Labels: cla-signed, refactor

#5731 Add blockbuster library and find I/O from unit tests
  requirements.txt
  supervisor/addons/addon.py
  supervisor/addons/build.py
  supervisor/addons/utils.py
  supervisor/api/__init__.py
  supervisor/api/backups.py
  supervisor/api/supervisor.py
  supervisor/api/utils.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/dbus/timedate.py
  supervisor/docker/addon.py
  supervisor/docker/audio.py
  supervisor/docker/homeassistant.py
  supervisor/hardware/manager.py
  supervisor/hardware/monitor.py
  supervisor/homeassistant/secrets.py
  supervisor/host/info.py
  supervisor/host/logs.py
  supervisor/host/manager.py
  supervisor/store/__init__.py
  supervisor/store/git.py
  supervisor/utils/dt.py
  supervisor/utils/validate.py
  tests/addons/test_build.py
  tests/addons/test_manager.py
  tests/api/test_addons.py
  tests/api/test_host.py
  tests/api/test_panel.py
  tests/api/test_supervisor.py
  tests/common.py
  tests/conftest.py
  tests/host/test_logs.py
  tests/resolution/check/test_check.py
  tests/resolution/evaluation/test_evaluate_operating_system.py
  tests/resolution/evaluation/test_evaluate_os_agent.py
  tests/resolution/evaluation/test_evaluate_systemd.py
  tests/resolution/evaluation/test_evaluate_systemd_journal.py
  tests/resolution/fixup/test_fixup.py
  tests/store/test_store_manager.py
  tests/test_coresys.py
Labels: cla-signed, refactor

#5734 Use Sentry helper function to report warnings
  supervisor/bootstrap.py
  tests/utils/test_sentry.py
Labels: cla-signed, bugfix

#5735 Finish out effort of adding and enabling blockbuster in tests
  supervisor/backups/backup.py
  supervisor/bootstrap.py
  supervisor/docker/manager.py
  supervisor/host/apparmor.py
  supervisor/mounts/manager.py
  supervisor/resolution/checks/core_security.py
  tests/backups/test_manager.py
  tests/conftest.py
  tests/dbus/test_interface.py
  tests/resolution/check/test_check.py
  tests/store/test_custom_repository.py
  tests/store/test_store_manager.py
  tests/test_ingress.py
  tests/utils/test_apparmor.py
  tests/utils/test_dbus.py
  tests/utils/test_sentry.py
Labels: cla-signed, refactor

#5743 Remove release assets tarball on frontend update
  .github/workflows/update_frontend.yml
Labels: cla-signed, bugfix

#5747 Fix logging error for invalid password for backup
  supervisor/backups/backup.py
  tests/backups/test_backup.py
Labels: cla-signed, bugfix

#5744 Remove WipeDevice method from OS Agent DBus mock
  tests/dbus_service_mocks/agent_system.py
Labels: cla-signed, test

#5746 Add blockbuster option to API
  supervisor/__main__.py
  supervisor/api/const.py
  supervisor/api/supervisor.py
  supervisor/config.py
  supervisor/const.py
  supervisor/utils/blockbuster.py
  supervisor/validate.py
  tests/api/test_supervisor.py
  tests/conftest.py
Labels: cla-signed, missing-documentation, new-feature, need-cli, need-client-library

#5787 Rate limit D-Bus errors
  requirements.txt
  supervisor/utils/dbus.py
Labels: cla-signed, new-feature

#5788 Handle unexpected WebSocket messages during auth
  supervisor/api/proxy.py
  tests/api/test_proxy.py
Labels: cla-signed, breaking-change, refactor

#5789 Skip corrupt registry files in backups
  supervisor/homeassistant/module.py
  tests/homeassistant/test_module.py
Labels: cla-signed, bugfix

#5791 Fix /supervisor/reload after refactoring
  supervisor/api/supervisor.py
  tests/api/test_supervisor.py
Labels: cla-signed, bugfix

#5784 Report stage with error in jobs
  supervisor/backups/manager.py
  supervisor/jobs/__init__.py
  tests/api/test_backups.py
  tests/api/test_jobs.py
  tests/backups/test_manager.py
  tests/jobs/test_job_manager.py
Labels: cla-signed, missing-documentation, new-feature, need-client-library

#5790 Improve Home Assistant Core WebSocket proxy implementation
  supervisor/api/proxy.py
  supervisor/utils/logging.py
  tests/api/test_proxy.py
Labels: cla-signed, refactor

#5792 Fix mypy issues in backups and dbus
  supervisor/api/backups.py
  supervisor/api/os.py
  supervisor/api/proxy.py
  supervisor/backups/backup.py
  supervisor/backups/const.py
  supervisor/backups/manager.py
  supervisor/dbus/agent/__init__.py
  supervisor/dbus/agent/apparmor.py
  supervisor/dbus/agent/boards/__init__.py
  supervisor/dbus/agent/boards/green.py
  supervisor/dbus/agent/boards/interface.py
  supervisor/dbus/agent/boards/yellow.py
  supervisor/dbus/agent/cgroup.py
  supervisor/dbus/agent/datadisk.py
  supervisor/dbus/agent/swap.py
  supervisor/dbus/agent/system.py
  supervisor/dbus/hostname.py
  supervisor/dbus/interface.py
  supervisor/dbus/logind.py
  supervisor/dbus/manager.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/accesspoint.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/interface.py
  supervisor/dbus/network/ip_configuration.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/dbus/network/settings.py
  supervisor/dbus/network/wireless.py
  supervisor/dbus/rauc.py
  supervisor/dbus/systemd.py
  supervisor/dbus/timedate.py
  supervisor/dbus/udisks2/__init__.py
  supervisor/dbus/udisks2/block.py
  supervisor/dbus/udisks2/data.py
  supervisor/dbus/udisks2/drive.py
  supervisor/dbus/udisks2/filesystem.py
  supervisor/dbus/udisks2/partition.py
  supervisor/dbus/udisks2/partition_table.py
  supervisor/mounts/mount.py
  supervisor/utils/dbus.py
  tests/api/test_backups.py
  tests/backups/conftest.py
  tests/backups/test_backup.py
  tests/backups/test_manager.py
  tests/dbus/agent/boards/test_green.py
  tests/dbus/agent/boards/test_yellow.py
  tests/dbus/test_interface.py
Labels: cla-signed, refactor
