Repository home-assistant/supervisor, pull requests merged in 2025-07, with the labels that each got.

#5987 Refactor addon git repo
  supervisor/resolution/fixups/store_execute_reset.py
  supervisor/store/__init__.py
  supervisor/store/git.py
  supervisor/store/repository.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/api/test_store.py
  tests/api/test_supervisor.py
  tests/conftest.py
  tests/resolution/fixup/test_store_execute_reset.py
  tests/store/test_custom_repository.py
  tests/store/test_repository_git.py
  tests/store/test_store_manager.py
Labels: cla-signed, refactor

#5988 Don't backup uninstalled addons
  supervisor/backups/backup.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix

#6000 Force reload of /etc/resolv.conf on WebSession init
  supervisor/coresys.py
Labels: cla-signed, bugfix

#5996 Allow multiple set-cookie headers with addons ingress
  supervisor/api/ingress.py
Labels: cla-signed, bugfix

#6009 Adjust feature request links in issue reporting
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: cla-signed, chore

#6007 Add Task issue form
  .github/ISSUE_TEMPLATE/task.yml
  .github/workflows/restrict-task-creation.yml
Labels: cla-signed, chore

#5844 Return 401 Unauthorized when using json/url encoded auth fails
  supervisor/api/auth.py
  tests/api/test_auth.py
Labels: cla-signed, breaking-change, chore, no-stale

#6011 Small improvement to Copilot instructions
  .github/copilot-instructions.md
Labels: cla-signed, ci

#6012 Drop ensure_builtin_repositories()
  supervisor/backups/backup.py
  supervisor/store/__init__.py
  supervisor/store/const.py
  supervisor/store/validate.py
  tests/store/test_custom_repository.py
Labels: cla-signed, refactor

#6025 Check for duplicate data disks only when the OS is available
  supervisor/resolution/checks/multiple_data_disks.py
  tests/resolution/check/test_check_multiple_data_disks.py
Labels: cla-signed, chore

#6024 Mark system as unhealthy if multiple OS installations are found
  supervisor/dbus/udisks2/data.py
  supervisor/resolution/checks/duplicate_os_installation.py
  supervisor/resolution/const.py
  tests/resolution/check/test_check_duplicate_os_installation.py
Labels: cla-signed, new-feature

#6053 Block OS updates when the system is unhealthy
  supervisor/os/manager.py
  tests/os/test_manager.py
Labels: cla-signed, new-feature
