Repository home-assistant/supervisor, pull requests merged in 2025-01, with the labels that each got.

#5544 Add X-Accel-Buffering to disable buffers in proxies
  supervisor/api/host.py
  supervisor/api/ingress.py
  supervisor/api/proxy.py
Labels: cla-signed, bugfix

#5426 Add support for CAP_CHECKPOINT_RESTORE privileges
  supervisor/addons/utils.py
  supervisor/docker/const.py
Labels: cla-signed, new-feature, need-cli

#5547 Add tun to static device list in hardware manager
  supervisor/hardware/manager.py
Labels: cla-signed, bugfix

#5555 Revert "Bump dbus-fast from 2.28.0 to 2.29.0"
  requirements.txt
Labels: cla-signed, dependencies

#5548 Add env on core restart due to restore
  supervisor/backups/backup.py
  supervisor/backups/const.py
  supervisor/backups/manager.py
  supervisor/core.py
  supervisor/docker/homeassistant.py
  supervisor/homeassistant/core.py
  supervisor/jobs/__init__.py
  tests/api/test_backups.py
  tests/backups/test_manager.py
Labels: cla-signed, new-feature

#5447 Trigger HA USB rescan on device removal
  supervisor/homeassistant/module.py
Labels: cla-signed, new-feature

#5564 Update Python to 3.13
  .devcontainer/devcontainer.json
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  .pre-commit-config.yaml
  build.yaml
  pyproject.toml
  requirements_tests.txt
  supervisor/api/host.py
  supervisor/utils/systemd_journal.py
  tests/api/test_proxy.py
  tests/conftest.py
  tests/dbus_service_mocks/base.py
  tests/utils/test_systemd_journal.py
Labels: cla-signed, dependencies, python

#5567 Extend backup API with file name field
  supervisor/api/backups.py
  supervisor/backups/manager.py
  tests/backups/test_manager.py
Labels: cla-signed, missing-documentation, new-feature, need-cli, need-client-library

#5569 Backup protected status can vary per location
  supervisor/api/backups.py
  supervisor/api/const.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
  tests/backups/test_backup.py
  tests/backups/test_manager.py
  tests/fixtures/test_consolidate.tar
  tests/fixtures/test_consolidate_unc.tar
Labels: cla-signed, missing-documentation, new-feature, need-client-library

#5572 Use version which is treated CalVer by AwesomeVersion
  setup.py
  supervisor/const.py
  tests/api/test_root.py
  tests/backups/conftest.py
  tests/test_coresys.py
Labels: cla-signed, refactor

#5568 Extend backup upload API with file name parameter
  supervisor/api/backups.py
  supervisor/backups/manager.py
  tests/api/test_backups.py
Labels: cla-signed, missing-documentation, new-feature

#5576 Support systemd-journal-gatewayd using a TCP socket
  supervisor/host/logs.py
Labels: cla-signed, new-feature

#5581 Add sizes per location and support `.local`
  supervisor/api/backups.py
  supervisor/api/const.py
  supervisor/backups/backup.py
  tests/api/test_backups.py
Labels: cla-signed, missing-documentation, new-feature, need-client-library

#5594 Avoid test failure by not checking exact size of backup
  tests/api/test_backups.py
Labels: cla-signed, bugfix

#5591 Make sure the oldest boot ID is included in the boot list
  supervisor/host/logs.py
Labels: cla-signed, bugfix

#5590 Handle non-existing backup file
  supervisor/api/backups.py
  supervisor/api/utils.py
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  supervisor/exceptions.py
  supervisor/misc/tasks.py
  supervisor/resolution/fixups/system_clear_full_backup.py
  tests/api/test_backups.py
  tests/backups/test_manager.py
Labels: cla-signed, bugfix

#5595 Avoid reordering add-on repositories on Backup load
  supervisor/backups/backup.py
  supervisor/store/validate.py
  tests/backups/test_backup.py
  tests/store/test_validate.py
Labels: cla-signed, bugfix
