Repository home-assistant/supervisor, pull requests merged in 2025-06, with the labels that each got.

#5940 Fix dynamic port pytest
  tests/test_ingress.py
Labels: cla-signed, test

#5939 Fix mypy issues in `host` and `jobs`
  supervisor/coresys.py
  supervisor/dbus/const.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/dbus/timedate.py
  supervisor/host/configuration.py
  supervisor/host/logs.py
  supervisor/host/network.py
  supervisor/jobs/__init__.py
  supervisor/jobs/decorator.py
  supervisor/jobs/job_group.py
Labels: cla-signed, refactor

#5879 Add opt-in IPv6 for containers
  supervisor/api/__init__.py
  supervisor/api/docker.py
  supervisor/api/network.py
  supervisor/const.py
  supervisor/dbus/network/connection.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/docker/manager.py
  supervisor/docker/network.py
  supervisor/docker/observer.py
  supervisor/misc/filter.py
  supervisor/validate.py
  tests/api/test_docker.py
  tests/api/test_network.py
  tests/dbus/network/test_connection.py
  tests/dbus/network/test_ip_configuration.py
  tests/docker/test_network.py
  tests/test_validate.py
Labels: cla-signed, new-feature

#5941 Avoid aiodns resolver memory leak
  supervisor/resolution/checks/dns_server.py
  supervisor/resolution/checks/dns_server_ipv6.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_dns_server_ipv6_error.py
Labels: cla-signed, bugfix

#5942 Fix mypy issues in `misc`, `mounts` and `os` modules
  supervisor/dbus/manager.py
  supervisor/misc/tasks.py
  supervisor/mounts/manager.py
  supervisor/mounts/mount.py
  supervisor/mounts/validate.py
  supervisor/os/data_disk.py
  supervisor/os/manager.py
  supervisor/utils/sentry.py
Labels: cla-signed, refactor

#5945 Bump cosign to v2.4.3
  .github/workflows/builder.yml
  .github/workflows/ci.yaml
  build.yaml
Labels: cla-signed, dependencies

#5953 Expose machine ID
  supervisor/api/root.py
  supervisor/const.py
  supervisor/coresys.py
Labels: cla-signed, missing-documentation, new-feature, need-client-library

#5954 Remove AES cipher from backup
  supervisor/backups/backup.py
Labels: cla-signed, chore

#5969 Add mypy to ci and precommit
  .github/workflows/ci.yaml
  .github/workflows/matchers/mypy.json
  .pre-commit-config.yaml
  requirements_tests.txt
  script/run-in-env.sh
  supervisor/addons/addon.py
  supervisor/addons/model.py
  supervisor/api/auth.py
  supervisor/coresys.py
  supervisor/dbus/network/__init__.py
  supervisor/dbus/network/interface.py
  supervisor/homeassistant/core.py
  supervisor/host/configuration.py
  supervisor/plugins/audio.py
  supervisor/plugins/base.py
  supervisor/plugins/cli.py
  supervisor/plugins/dns.py
  supervisor/plugins/multicast.py
  supervisor/plugins/observer.py
  supervisor/resolution/checks/network_interface_ipv4.py
  supervisor/supervisor.py
  tests/api/test_auth.py
  tests/dbus/network/test_interface.py
  tests/test_supervisor.py
Labels: cla-signed, refactor

#5965 Add code documentation for Jobs decorator
  supervisor/jobs/decorator.py
Labels: cla-signed, chore

#5979 Fix `docker.run_command()` needing `detach` but not enforcing it
  supervisor/docker/homeassistant.py
  supervisor/docker/manager.py
  tests/docker/test_manager.py
Labels: cla-signed, refactor

#5976 Refactor builtin repositories to enum
  supervisor/store/git.py
  supervisor/store/repository.py
  supervisor/store/validate.py
  tests/conftest.py
  tests/store/test_repository_git.py
Labels: cla-signed, refactor
