Repository home-assistant/supervisor, pull requests merged in 2025-08, with the labels that each got.

#6054 Update to Alpine 3.22
  build.yaml
Labels: cla-signed, dependencies

#6063 Return optimistic life time estimate for eMMC storage
  supervisor/hardware/disk.py
  tests/hardware/test_disk.py
Labels: cla-signed, chore

#6041 Add unsupported reason os_version and evaluation
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/os_version.py
  tests/resolution/evaluation/test_evaluate_os_version.py
Labels: cla-signed, missing-documentation, new-feature

#6067 Use actual latest version of OS in os version check
  supervisor/const.py
  supervisor/os/manager.py
  supervisor/resolution/evaluations/os_version.py
  supervisor/updater.py
  supervisor/validate.py
  tests/resolution/evaluation/test_evaluate_os_version.py
Labels: cla-signed, bugfix

#6069 Add an issue for disk lifetime >=90%
  supervisor/resolution/checks/disk_lifetime.py
  supervisor/resolution/const.py
  tests/resolution/check/test_check_disk_lifetime.py
Labels: cla-signed, new-feature, needs-client-library, needs-core

#6073 Use path for actions/download-artifact to fix coverage report
  .github/workflows/ci.yaml
Labels: cla-signed, ci

#6074 Improve JobGroup locking with external ownership tracking
  supervisor/jobs/decorator.py
  supervisor/jobs/job_group.py
  tests/jobs/test_job_decorator.py
Labels: cla-signed, new-feature, refactor

#6075 Avoid race condition on add-on installation
  supervisor/addons/manager.py
Labels: cla-signed, bugfix

#6076 Ignore UTF-8 errors in addon docs
  supervisor/addons/model.py
Labels: cla-signed, chore

#6095 Improved error handling for docker image pulls
  supervisor/const.py
  supervisor/docker/interface.py
  supervisor/docker/manager.py
  supervisor/exceptions.py
  tests/addons/test_addon.py
  tests/addons/test_manager.py
  tests/conftest.py
  tests/docker/test_interface.py
  tests/homeassistant/test_core.py
  tests/plugins/test_plugin_base.py
Labels: cla-signed, bugfix

#6099 Propagate timezone setting to host in OS 16.2 and newer
  supervisor/api/supervisor.py
  supervisor/core.py
  supervisor/dbus/timedate.py
  supervisor/host/control.py
  tests/dbus/test_timedate.py
  tests/host/test_control.py
  tests/test_core.py
Labels: cla-signed, new-feature

#6126 Handle malformed addon map entries gracefully
  supervisor/addons/validate.py
  tests/addons/test_config.py
Labels: cla-signed, bugfix

#6129 Do not skip messages in pull progress log due to rounding
  supervisor/jobs/__init__.py
  tests/docker/test_interface.py
Labels: cla-signed, bugfix
