Repository home-assistant/supervisor, pull requests merged in 2025-05, with the labels that each got.

#5862 Recreate aiohttp ClientSession after DNS plug-in load
  pyproject.toml
  supervisor/api/middleware/security.py
  supervisor/const.py
  supervisor/core.py
  supervisor/coresys.py
  supervisor/plugins/dns.py
  tests/addons/test_manager.py
  tests/api/test_auth.py
  tests/api/test_backups.py
  tests/api/test_discovery.py
  tests/api/test_security.py
  tests/api/test_store.py
  tests/api/test_supervisor.py
  tests/common.py
  tests/conftest.py
  tests/misc/test_tasks.py
  tests/os/test_manager.py
  tests/plugins/test_plugin_manager.py
  tests/resolution/check/test_check_docker_config.py
  tests/resolution/fixup/test_system_execute_integrity.py
  tests/test_core.py
  tests/test_coresys.py
  tests/test_supervisor.py
  tests/test_updater.py
Labels: cla-signed, bugfix

#5869 Handle ClientPayloadError in advanced logging
  supervisor/api/host.py
Labels: cla-signed, bugfix

#5871 Handle non-existing addon config dir
  supervisor/addons/addon.py
  tests/addons/test_addon.py
Labels: cla-signed, bugfix

#5878 Fix pytests to make them run in isolation
  tests/addons/test_addon.py
  tests/backups/test_manager.py
  tests/resolution/check/test_check_addon_pwned.py
  tests/resolution/check/test_check_dns_server_failure.py
  tests/resolution/check/test_check_dns_server_ipv6_error.py
  tests/resolution/fixup/test_store_execute_reload.py
  tests/resolution/fixup/test_store_execute_reset.py
  tests/resolution/test_resolution_manager.py
  tests/store/test_custom_repository.py
  tests/store/test_store_manager.py
Labels: cla-signed, test

#5882 Fallback to threaded resolver in case AsyncResolver fails
  supervisor/coresys.py
Labels: enhancement, cla-signed

#5884 Log DNS resolver initialization errors with critical severity
  supervisor/coresys.py
Labels: cla-signed, chore

#5880 Delete Backup files on error
  supervisor/backups/backup.py
  supervisor/backups/manager.py
  tests/backups/test_manager.py
Labels: cla-signed, breaking-change

#5898 Fix container image detection for aarch64
  supervisor/docker/interface.py
Labels: cla-signed, bugfix

#5896 Trigger auto-update through Core WebSocket call
  supervisor/homeassistant/const.py
  supervisor/misc/tasks.py
  tests/misc/test_tasks.py
Labels: cla-signed, new-feature

#5892 Add IPv6 address generation mode & privacy extensions
  supervisor/api/network.py
  supervisor/const.py
  supervisor/dbus/const.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/host/configuration.py
  supervisor/host/const.py
  tests/api/test_network.py
  tests/dbus/network/setting/test_generate.py
  tests/dbus/network/setting/test_init.py
Labels: cla-signed, new-feature

#5900 Stop reading advanced logs on ConnectionError
  supervisor/api/host.py
Labels: cla-signed, bugfix

#5903 Process NetworkManager PrimaryConnection changes
  supervisor/dbus/network/__init__.py
  tests/dbus/network/test_network_manager.py
Labels: cla-signed, bugfix

#5904 Bump pre-commit ruff to 0.11.10
  .pre-commit-config.yaml
  supervisor/coresys.py
  supervisor/docker/manager.py
  tests/misc/test_filter_data.py
Labels: cla-signed, chore

#5901 Avoid initializing Blockbuster on Supervisor info call
  supervisor/__main__.py
  supervisor/api/supervisor.py
  supervisor/utils/blockbuster.py
Labels: cla-signed, chore

#5906 Use s6-overlay read-only mode by default
  Dockerfile
Labels: cla-signed, build

#5909 Fix add-on config parse messages
  supervisor/store/data.py
Labels: cla-signed, bugfix

#5910 Ignore missing backup file on error
  supervisor/backups/manager.py
Labels: cla-signed, bugfix

#5915 Bump aiohttp to 3.12.2
  requirements.txt
Labels: cla-signed, dependencies

#5922 Avoid early DNS plug-in start
  supervisor/host/network.py
  supervisor/plugins/dns.py
  tests/host/test_connectivity.py
Labels: cla-signed, bugfix

#5925 Revert "Do not backup add-on being uninstalled (#5917)"
  supervisor/addons/addon.py
  tests/addons/test_addon.py
  tests/conftest.py
Labels: cla-signed, bugfix
