Repository home-assistant/supervisor, pull requests merged in 2025-09, with the labels that each got.

#6153 Make test_job_decorator tests timezone agnostic
  tests/jobs/test_job_decorator.py
Labels: cla-signed, test

#6144 Fix WebSocket proxy for add-ons not forwarding ping/pong frame data
  supervisor/api/ingress.py
Labels: cla-signed, bugfix

#5520 Add network interface settings for mDNS/LLMNR
  supervisor/api/network.py
  supervisor/const.py
  supervisor/dbus/const.py
  supervisor/dbus/network/configuration.py
  supervisor/dbus/network/setting/__init__.py
  supervisor/dbus/network/setting/generate.py
  supervisor/host/configuration.py
  supervisor/host/const.py
  tests/api/test_network.py
  tests/dbus/network/setting/test_generate.py
  tests/host/test_configuration.py
Labels: cla-signed, new-feature

#6133 Avoid duplicate evaluate_system() calls during resolution manager setup
  supervisor/core.py
  supervisor/resolution/module.py
Labels: cla-signed, refactor

#6169 Avoid setup failure on missing timedatectl
  supervisor/host/control.py
Labels: cla-signed, bugfix

#6154 Write cidfiles of Docker containers and mount them individually to /run/cid
  supervisor/bootstrap.py
  supervisor/config.py
  supervisor/docker/manager.py
  tests/conftest.py
  tests/docker/test_addon.py
  tests/docker/test_manager.py
  tests/plugins/test_plugin_base.py
Labels: cla-signed, new-feature

#6171 Allow deeply nested dicts and lists in addon config schemas
  supervisor/addons/options.py
  supervisor/addons/validate.py
  tests/addons/test_config.py
  tests/addons/test_options.py
Labels: cla-signed, new-feature

#6179 Persistent notifications to repairs and fix free_space check
  supervisor/resolution/checks/free_space.py
  supervisor/resolution/const.py
  supervisor/resolution/notify.py
  tests/jobs/test_job_decorator.py
  tests/resolution/check/test_check.py
  tests/resolution/check/test_check_free_space.py
  tests/store/test_store_manager.py
Labels: cla-signed, new-feature

#6148 Check Core version and raise unsupported if older than 2 years
  supervisor/jobs/const.py
  supervisor/jobs/decorator.py
  supervisor/misc/tasks.py
  supervisor/resolution/const.py
  supervisor/resolution/evaluations/home_assistant_core_version.py
  supervisor/resolution/evaluations/os_version.py
  supervisor/store/__init__.py
  supervisor/updater.py
  tests/jobs/test_job_decorator.py
  tests/resolution/evaluation/test_evaluate_home_assistant_core_version.py
Labels: cla-signed, new-feature, needs-client-library, needs-core
